fix: added numeric size values to Button,Input,Select,SliderInput,Tag…
core-ds/core-components pull request #1021
Opened 2023-12-05 10:23 UTC by Valeri8888

2023-12-08 06:29 UTC, v-gevak requested changes

2023-12-08 06:29 UTC, v-gevak commented on packages/attach/src/Component.tsx
> +            if (['size-40', 'size-32'].includes(SIZE_TO_CLASSNAME_MAP[size])) {
```[40, 32].inclues(size)```

2023-12-08 06:29 UTC, v-gevak commented on packages/attach/src/Component.tsx
>  Attach.defaultProps = {
Выпили вообще defaultProps

2023-12-08 06:29 UTC, v-gevak commented on packages/attach/src/__image_snapshots__/attach-dark-preview-snap.png
Почему размер изменился?

2023-12-08 06:29 UTC, v-gevak commented on packages/button/src/components/base-button/Component.tsx
> +        const showHint = hint && ['size-56', 'size-64', 'size-72'].includes(SIZE_TO_CLASSNAME_MAP[size]);
[56, 64, 72].includes(size);

2023-12-08 06:29 UTC, v-gevak commented on packages/custom-picker-button/src/field/Component.tsx
> +        SIZE_TO_CLASSNAME_MAP[buttonSize],
buttonSize

2023-12-08 06:29 UTC, v-gevak commented on packages/filter-tag/src/components/base-filter-tag/Component.tsx
> +                        {['size-40', 'size-32'].includes(SIZE_TO_CLASSNAME_MAP[size]) ? (
[40,32].includes

2023-12-08 06:29 UTC, v-gevak commented on packages/filter-tag/src/components/base-filter-tag/Component.tsx
> +                            {SIZE_TO_CLASSNAME_MAP[size] === 'size-32' ? (
size === 32 ?

2023-12-08 06:29 UTC, v-gevak commented on packages/textarea/src/consts.ts
> +export const SIZE_TO_CLASSNAME_MAP = {
Может действительно стоит это вынести? Ну эта мапа же в каждом компоненте почти будет:))
Если хочешь, то можешь вынести в shared/src/consts.ts какой-нибудь

2023-12-08 07:58 UTC, Valeri8888 commented on packages/attach/src/__image_snapshots__/attach-dark-preview-snap.png
потому что у attach максимальный размер l (64) , а в превью был указан xl (72) 
я исправила на 64

2023-12-13 10:00 UTC, Valeri8888 commented on packages/attach/src/__image_snapshots__/attach-dark-preview-snap.png
потому что у attach максимальный размер l (64) , а в превью был указан xl (72)
я исправила на 64

2023-12-13 12:23 UTC, Valeri8888 commented on packages/attach/src/__image_snapshots__/attach-interactions-tests-attach-file-snap.png
да, все ок 
недавно обновляли же цвета, наверно этот скриншот "залип" тогда и не обновился

2024-01-15 07:32 UTC, SiebenSieben commented on .changeset/perfect-ties-shout.md
> +Добавлены новые размеры - 32, 40, 48, 56, 64, 72
Кажется, такая формулировка может запутать

Такие же размеры уже были

Т.е. значения вроде и новые, но не то чтобы это новые размеры, это новый способ указания размеров

2024-01-15 07:32 UTC, SiebenSieben commented on .changeset/big-gifts-exist.md
> +"@alfalab/core-components-button": minor
Кнопка в отдельном ченджсете

2024-01-15 07:36 UTC, SiebenSieben commented on packages/attach/src/component.screenshots.test.tsx
> +                size: 64,
Влад попросил 72 на 64 поменять?

2024-01-15 07:39 UTC, SiebenSieben commented on packages/attach/src/index.module.css
>  /* TODO обновить типографику на новую, когда ее зарелизят */
Актуальный ли коммент

2024-01-15 07:59 UTC, SiebenSieben commented on packages/form-control/src/__image_snapshots__/form-control-screenshots-disabled-prop-mobile-theme-snap.png
Почему меняются ещё и цвета?

2024-01-15 08:10 UTC, Valeri8888 commented on packages/form-control/src/__image_snapshots__/form-control-screenshots-disabled-prop-mobile-theme-snap.png
<img width="648" alt="Снимок экрана 2024-01-15 в 11 07 16" src="https://github.com/core-ds/core-components/assets/87258678/c4d1c26f-99f1-4ac4-920b-c52af9b04628">

Бывает что скриншот 'залипает' и не обновляется при изменениях
вероятно этот тот случай
выше скрин как выглядит компонент в мобильной теме с disabled

2024-01-15 08:14 UTC, SiebenSieben approved these changes

2024-01-15 08:34 UTC, Valeri8888 commented on packages/attach/src/index.module.css
>  /* TODO обновить типографику на новую, когда ее зарелизят */
если посмотреть в фигме, то актуальный 
https://www.figma.com/file/cdNnkh2QdxuvYLrBm4cubM/branch/UbjMvmChTdD8nhHMCJ2End/Web-%3A%3A-Core-Default-Components?node-id=8960%3A61077&mode=dev

надо у влада уточнить @Oladii

2024-01-15 08:34 UTC, Valeri8888 commented on packages/attach/src/component.screenshots.test.tsx
> +                size: 64,
нет, влад не просил, но это странно использовать размер компонента кт у него нет

2024-01-15 08:34 UTC, Valeri8888 commented on .changeset/big-gifts-exist.md
> +"@alfalab/core-components-button": minor
да, в другом ченджсете
исправила

2024-01-15 08:34 UTC, Valeri8888 commented on .changeset/perfect-ties-shout.md
> +Добавлены новые размеры - 32, 40, 48, 56, 64, 72
исправила на "Добавлены новые способы указать размеры"

2024-02-08 11:52 UTC, merged