feat: added ability remove text from back button
core-ds/core-components pull request #1077
Opened 2024-01-19 11:19 UTC by Valeri8888

2024-01-22 09:32 UTC, v-gevak requested changes

2024-01-22 09:32 UTC, v-gevak commented on .changeset/proud-dolls-applaud.md
> +Добавили возможность скрывать текст для кнопки назад (заголовок) в модальных компонентах (BottomSheet, Modal, SidePanel). Для того чтобы скрыть текст кнопки назад, необходимо указать backButtonProps=
Мне подход прятать кнопку через textOpacity не нравится, textOpacity - это внутреннее приватное свойство, его никто трогать не должен. Да это и не очевидный вариант, это все равно что на размер элемента через цвет влиять.

На text лучше влиять через проп text. Сделать ему тип string | null и не рендерить если он falsy

2024-01-23 08:49 UTC, v-gevak commented on packages/navigation-bar/src/components/back-arrow-addon/Component.tsx
> +                        [styles.iconOnly]: !text && !isMobileView,
Это же костыль какой-то. Давай без доп класса это решить попробуем.
Можно, например, попробовать вот тут styles.component указать min-width: 48px; justify-conternt: left

2024-01-23 10:38 UTC, Valeri8888 commented on packages/navigation-bar/src/components/back-arrow-addon/Component.tsx
> +                        [styles.iconOnly]: !text && !isMobileView,
фикс

2024-01-24 04:10 UTC, v-gevak approved these changes

2024-01-24 11:10 UTC, v-gevak approved these changes

2024-01-24 11:46 UTC, SiebenSieben approved these changes

2024-01-25 04:38 UTC, merged