feat(circular-progress-bar): added new sizes and props
core-ds/core-components pull request #122
Opened 2022-07-04 07:22 UTC by Valeri8888

Добавила новые размеры и props

2022-07-04 08:36 UTC, SiebenSieben commented on packages/circular-progress-bar/src/Component.tsx
> +    direction?: 'ClockWise' | 'ClockOtherwise';
Clockwise | CounterClockwise?

2022-07-04 08:37 UTC, SiebenSieben commented on packages/circular-progress-bar/src/docs/Component.stories.mdx
> +                    direction={boolean('direction', false)}
Тут не работает

2022-07-04 08:40 UTC, Lacronts commented on packages/circular-progress-bar/src/index.module.css
> +        stroke-width: 4;
Может сразу атрибутом svg это задать, без css?

2022-07-04 08:43 UTC, SiebenSieben commented
Решили не добавлять возможность указать размер (width/height)?

Чтобы можно было переопределить size аналогично badge, и оставить в продуктах старый размер

2022-07-04 08:45 UTC, Lacronts commented on packages/circular-progress-bar/src/Component.tsx
> +                    SIZES[size] > 64 ? (
не понятно почему для SIZES[size] > 64 используется Typography.TitleMobile, а для остальных случаев Typography.Text

2022-07-04 08:47 UTC, Lacronts commented on packages/circular-progress-bar/src/Component.tsx
> +                            view={size === 'l' ? 'xsmall' : 'medium'}
Тут тоже непонятно почему если size === l, то view 'xsmall', а иначе 'medium'. Для таких случаев лучше мапу использовать - VIEW[size]

2022-07-04 08:47 UTC, Lacronts commented on packages/circular-progress-bar/src/Component.tsx
> +                            view={size === 'm' ? 'secondary-large' : 'secondary-small'}
Тоже самое

2022-07-04 12:12 UTC, Valeri8888 commented on packages/circular-progress-bar/src/index.module.css
> +        stroke-width: 4;
можно и так

2022-07-04 12:19 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +                    SIZES[size] > 64 ? (
потому что так в макете 
для ProgressBar размером больше 64 (l, xl и xxl) стили title указаны как для Typography.TitleMobile, для остальных размеров - Typography.Text
@Oladii

2022-07-04 12:56 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +                            view={size === 'l' ? 'xsmall' : 'medium'}
Варианты начертания у Typography.TitleMobile и Typography.Text разные, мне кажется лучше оставить тернарку

2022-07-04 12:57 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +    direction?: 'ClockWise' | 'ClockOtherwise';
> Решили не включать возможность установки размера (ширины/высоты)?
> 
> Чтобы можно было переопределить размер аналогично значку, и оставить в продукции старый размер


добавила возможность установки размера через высоту

2022-07-04 13:02 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +    direction?: 'ClockWise' | 'ClockOtherwise';
исправила

2022-07-05 03:36 UTC, reme3d2y requested changes

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +     * Направление прогресса (true - справа налево, false - слева направо)
Коммент не тот. 

Может быть так?
`direction?: 'forward' | 'backward';`

В любом случае, надо нейминг поменять, мы PascalCase не юзаем нигде

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +        /* eslint-disable */
🙀

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +        /* eslint-disable */
Надо упростить функцию, вынести в конфиг и\или разбить на части

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +        /* eslint-disable */
🙀

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +                {IconComplete && isComplete ? (
мб так?
IconComponent = isComplete ? IconComplete : Icon;

2022-07-05 03:36 UTC, reme3d2y commented on packages/circular-progress-bar/src/index.module.css
> +    --circular-progress-bar-primary-inverted-color: var(--color-light-graphic-primary-inverted);
А для чего тут темизация, если view и так жестко завязан на эти токены?

2022-07-05 07:56 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +                {IconComplete && isComplete ? (
'+'

2022-07-05 08:19 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +        /* eslint-disable */
"+"

2022-07-05 08:19 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +        /* eslint-disable */
"+"

2022-07-05 08:33 UTC, Valeri8888 commented on packages/circular-progress-bar/src/index.module.css
> +    --circular-progress-bar-primary-inverted-color: var(--color-light-graphic-primary-inverted);
исправила

2022-07-05 09:27 UTC, reme3d2y commented on packages/circular-progress-bar/src/index.module.css
> +    --circular-progress-bar-primary-inverted-color: var(--color-light-graphic-primary-inverted);
не вижу нового коммита

2022-07-05 12:08 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +                            view={size === 'm' ? 'secondary-large' : 'secondary-small'}
исправила

2022-07-05 12:08 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +     * Направление прогресса (true - справа налево, false - слева направо)
исправила

2022-07-06 04:44 UTC, Lacronts approved these changes

2022-07-15 12:41 UTC, vladislavyushev approved these changes

2022-07-15 12:47 UTC, Oladii approved these changes

2022-07-18 00:44 UTC, reme3d2y requested changes

2022-07-18 00:44 UTC, reme3d2y commented on .eslintrc.js
> +        'no-nested-ternary': 'off'
не, давай вернем обратно. Вложенные тернарки это не ок

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +            <React.Fragment>
Тут разве нужен фрагмент?

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +            <React.Fragment>
тут тоже

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +    const renderContent = () => {
отступ

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/Component.tsx
> +    height?: number;
А когда и зачем это нужно? Типа я могу поставить size="xxl" и height={24}  ? 
@Oladii

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/index.module.css
> +@import '../../themes/src/default.css';
default.css уже содержит импорт typography, как и colors-indigo

2022-07-18 00:44 UTC, reme3d2y commented on packages/circular-progress-bar/src/index.module.css
> +    font-feature-settings: 'ss01';
мы вроде нигде отдельно это не задаем

2022-07-18 07:59 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +    height?: number;
теоретически можешь, но есть дока с пояснением, что, например, для высоты 70 необходимо указывать размер m
я обсуждала это с Евгением, было решено так сделать для того чтобы не дублировать много кода

2022-07-18 08:01 UTC, Valeri8888 commented on packages/circular-progress-bar/src/index.module.css
> +    font-feature-settings: 'ss01';
Евгений сказал, что необходимо указывать для шрифта Styrene

2022-07-18 11:33 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +            <React.Fragment>
исправила

2022-07-18 11:34 UTC, Valeri8888 commented on packages/circular-progress-bar/src/Component.tsx
> +    const renderContent = () => {
исправила

2022-07-18 11:35 UTC, Valeri8888 commented on .eslintrc.js
> +        'no-nested-ternary': 'off'
исправила

2022-07-18 13:04 UTC, Valeri8888 commented on packages/circular-progress-bar/src/index.module.css
> +@import '../../themes/src/default.css';
исправила

2022-07-20 08:52 UTC, reme3d2y approved these changes

2022-07-22 08:06 UTC, merged