fix/input-autocomplete_search
core-ds/core-components pull request #1261
Opened 2024-06-21 16:17 UTC by fulcanellee

2024-06-27 07:06 UTC, Valeri8888 approved these changes

2024-06-27 07:54 UTC, hextion requested changes

2024-06-27 07:54 UTC, hextion commented on packages/select/src/components/base-select/components/list-desktop/hooks/use-list-popover-desktop-props.tsx
> +export const useListPopoverDesktopProps = (props: ComponentProps) => {
технически это не хук, предлагаю переименовать соответствующе

2024-07-18 07:48 UTC, hextion approved these changes

2024-07-18 14:05 UTC, merged