fix/slider-input_sync
core-ds/core-components pull request #1304
Opened 2024-07-18 13:30 UTC by fulcanellee

2024-07-19 08:32 UTC, SiebenSieben approved these changes

2024-07-22 07:52 UTC, hextion requested changes

2024-07-22 07:52 UTC, hextion commented on packages/slider-input/src/Component.tsx
> +        const lockLimitValidate = useCallback(
выглядит как лишняя и излишне усложненная функция. предлагаю все посчитать в `handleInputBlur` и вызвать там же с соответствующими `callback`

2024-07-22 07:52 UTC, hextion commented on packages/slider-input/src/Component.tsx
> +            (event: ChangeEvent<HTMLInputElement>) => {
при `blur` эмитится FocusEvent, поэтому формально ошибка в типе

предлагаю отдавать `null`

2024-07-24 06:42 UTC, fulcanellee commented on packages/slider-input/src/Component.tsx
> +        const lockLimitValidate = useCallback(
исправил

2024-07-24 06:42 UTC, fulcanellee commented on packages/slider-input/src/Component.tsx
> +            (event: ChangeEvent<HTMLInputElement>) => {
исправил

2024-07-29 14:27 UTC, hextion requested changes

2024-07-29 14:27 UTC, hextion commented on packages/slider-input/src/types/propTypes.ts
> +    event: ChangeEvent<HTMLInputElement> | FocusEvent | null,
FocusEvent не подходит по семантике

2024-07-29 14:27 UTC, hextion commented on packages/slider-input/src/Component.tsx
> +                        onChange(event, { value: getEventPayloadValue(validValue) });
event -> null

2024-07-29 14:27 UTC, hextion commented on packages/slider-input/src/Component.tsx
> +                        onInputChange(event, { value: getEventPayloadValue(validValue) });
event -> null

2024-08-16 09:33 UTC, hextion approved these changes

2024-08-19 13:37 UTC, fulcanellee commented on packages/slider-input/src/Component.tsx
> +    lockLimit?: boolean;
думаю лучше отдельной пропсой

2024-08-19 13:42 UTC, fulcanellee commented on packages/slider-input/src/types/propTypes.ts
> +    event: ChangeEvent<HTMLInputElement> | null,
исправил changeset

2024-11-15 11:22 UTC, SiebenSieben approved these changes

2024-11-18 09:38 UTC, merged