feat(gallery): supported video in gallery
core-ds/core-components pull request #1317
Opened 2024-07-25 12:28 UTC by temss-front

Добавлена поддержка видео в галерее

2024-08-12 12:49 UTC, fulcanellee requested changes

2024-08-12 12:49 UTC, fulcanellee commented on packages/gallery/package.json
> +        "hls.js": "^1.5.13",
hls.js не поддерживается на айфонах

2024-08-12 12:49 UTC, fulcanellee commented on packages/gallery/package.json
> +      "@alfalab/core-components-button": "^11.5.3",
форматирование уехало

2024-08-12 12:49 UTC, fulcanellee commented on packages/gallery/package.json
> +      "@alfalab/core-components-button": "^11.5.3",
нужно разобраться с упавшими ci job'ами

2024-08-26 12:14 UTC, temss-front commented on packages/gallery/package.json
> +        "hls.js": "^1.5.13",
Да, но там hls поддерживается нативно, для этого тут проверяется поддерживается или нет 
![image](https://github.com/user-attachments/assets/691c9f75-d086-433a-8f1b-3ef29674feb2)

2024-08-28 12:37 UTC, Valeri8888 commented on packages/gallery/src/components/navigation-bar/Component.tsx
> +                        className={cn(styles.preview)}
а зачем это нужно?

2024-08-28 12:38 UTC, Valeri8888 commented on packages/gallery/src/components/info-bar/index.ts
пустой файл

2024-08-28 12:43 UTC, Valeri8888 commented on packages/gallery/src/components/image-viewer/video/index.module.css
> +    border-radius: var(--border-radius-3xl);
мы перешли на новый нейминг для переменных cкругления , можно посмотреть в файле vars/src/border-radius.css

2024-08-29 06:55 UTC, fulcanellee approved these changes
Исправь скриншоты

2024-08-29 07:57 UTC, Oladii reviewed
точно ли кнопка паузы должна всегда отображаться на экране?
<img width="590" alt="image" src="https://github.com/user-attachments/assets/6eaffa3c-deab-4604-8101-8936e2c41597">

Необходимо добавить в доксы пример видео в существующую галерею с несколькими изображениями

2024-08-29 07:57 UTC, Oladii commented on packages/gallery/src/__image_snapshots__/gallery-interactions-tests-full-screen-snap.png
А что здесь произошло?

2024-08-29 07:57 UTC, Oladii commented on packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-single-image-snap.png
и здесь)

2024-08-29 08:06 UTC, Oladii commented
в мобильных превьюхах есть какие-то странные белые обводки
<img width="104" alt="image" src="https://github.com/user-attachments/assets/37412642-2cc5-4b94-a9f7-374832a4b24c">

2024-08-29 08:07 UTC, Oladii commented on packages/gallery/src/__image_snapshots__/gallery-interactions-tests-full-screen-snap.png
<img width="386" alt="image" src="https://github.com/user-attachments/assets/608f238e-631c-410e-b4bf-b3b11c070501">

2024-08-29 08:20 UTC, Oladii commented
К воспроизведению видео много вопросов. 
Передал комментарии дизайнеру

2024-08-29 09:32 UTC, fulcanellee requested changes

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/Component.tsx
> +    const [mutedVideo, setMutedVideo] = useState(false);
желательно указывать дженерики

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/Component.tsx
> +        if (isCurrentVideo && !hideNavigation) {
таймер нужно сбрасывать непосредственно перед вызовом

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/Component.tsx
> +    const galleryContext = useMemo<GalleryContext>(
сомнительное решение, оно здесь нужно?

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/Component.tsx
> +                            [styles.navigationVideo]: isCurrentVideo && view === 'mobile',
добавить переменную isMobile = view === 'mobile' (или что-то типа того), так как встречается несколько раз

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/components/buttons/index.tsx
все компоненты желательно растащить по разным файлам (BackArrow, Play, Pause, MuteVideo, UnmuteVideo). В общем все новые которые добавил. Которые были пока можно не трогать.

2024-08-29 09:32 UTC, fulcanellee commented on packages/gallery/src/components/header-mobile/Component.tsx
> +        singleSlide || !images.length ? '' : `${currentSlideIndex + 1} из ${images.length}`;
это условие сложно воспринимается, дай ему описание

2024-08-29 09:45 UTC, temss-front commented on packages/gallery/src/types.ts
> +export type ImageMeta =
можно подробнее, слышал только про перегрузку функций и методов?

2024-08-29 12:42 UTC, fulcanellee commented on packages/gallery/src/types.ts
> +export type ImageMeta =
сорри за невнимательность, мне показалось что это функа)

2024-08-29 13:39 UTC, hextion requested changes

2024-08-29 13:39 UTC, hextion commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +            playerRef.current.src = url;
может декларативно сделаем?
```
<video ...src={Hls.isSupported() ? undefined : url} />
```

2024-08-29 13:39 UTC, hextion commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +    useEffect(() => {
предлагаю переделать работу с состоянием воспроизведения

убрать этот эффект и добавить

```
<video ...onPlay={...} ...onPause={...} />
```

потому что по разным причинам видео может останавливаться/запускаться. чтобы состояние отражало действительность нужно слушать непосредственно эвенты

и для `handleClick` сделать
```
handleClick = () => {
if (playingVideo) {
  playerRef.current.play();
} else {
  playerRef.current.pause();
}
```

2024-08-29 13:39 UTC, hextion commented on packages/gallery/src/Component.tsx
> +    useEffect(() => {
может это завязать на логику видео?

при начале воспроизведения через `n` секунд скрыть и тп

2024-08-30 13:36 UTC, temss-front commented on packages/gallery/src/components/navigation-bar/Component.tsx
> +                        className={cn(styles.preview)}
убрал

2024-08-30 13:37 UTC, temss-front commented on packages/gallery/src/components/info-bar/index.ts
добавил импорт

2024-08-30 13:37 UTC, temss-front commented on packages/gallery/src/components/info-bar/index.module.css
> +    padding: 0 var(--gap-xs);
поменял на новый токен

2024-08-30 13:37 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.module.css
> +    border-radius: var(--border-radius-3xl);
поменял на новый токен

2024-08-30 13:38 UTC, temss-front commented on packages/gallery/src/__image_snapshots__/gallery-interactions-tests-full-screen-snap.png
поправил

2024-08-30 13:38 UTC, temss-front commented on packages/gallery/src/Component.tsx
> +    const [mutedVideo, setMutedVideo] = useState(false);
указал

2024-08-30 13:38 UTC, temss-front commented on packages/gallery/src/Component.tsx
> +        if (isCurrentVideo && !hideNavigation) {
поправил

2024-08-30 13:39 UTC, temss-front commented on packages/gallery/src/Component.tsx
> +    const galleryContext = useMemo<GalleryContext>(
убрал мемо, но там линтер ругается на это. я хз как лучше

2024-08-30 13:39 UTC, temss-front commented on packages/gallery/src/Component.tsx
> +                            [styles.navigationVideo]: isCurrentVideo && view === 'mobile',
добавил

2024-08-30 13:40 UTC, temss-front commented on packages/gallery/src/components/buttons/index.tsx
там стили для всех кнопок одинаковые, поэтому удобно хранить в одном месте. да и прошлые сделаны по такому же принципу. Не хочется копировать один css файл для всех кнопок, поэтому оставил как есть

2024-08-30 13:41 UTC, temss-front commented on packages/gallery/src/components/header-mobile/Component.tsx
> +        singleSlide || !images.length ? '' : `${currentSlideIndex + 1} из ${images.length}`;
упростил его, прошлая реализация была избыточна

2024-08-30 13:41 UTC, temss-front commented on packages/gallery/src/components/image-preview/Component.tsx
> +    const previewWidth = isMobile ? 36 : 56;
вынес в константы

2024-08-30 13:41 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +    const handleClick = (event: React.MouseEvent) => {
добавил импорт

2024-08-30 13:41 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +            playerRef.current.muted = mutedVideo;
поправил

2024-08-30 13:43 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +        /* eslint-disable-next-line react-hooks/exhaustive-deps */
ответил выше

2024-08-30 13:44 UTC, temss-front commented on packages/gallery/src/components/header-mobile/index.ts
добавил импорт

2024-08-30 13:44 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +            playerRef.current.src = url;
вынес логику в нативную пропсу

2024-08-30 13:49 UTC, temss-front commented on packages/gallery/src/Component.tsx
> +    useEffect(() => {
По дизайну при переходе на слайд скрывается навигация через 2 сек сразу и в следующих итерациях так же будет и у изображения, поэтому логичнее это делать тут, а не завязываться на проигрывании видео

2024-08-30 13:53 UTC, temss-front commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +    useEffect(() => {
я понял посыл, попробовал так. но из-за того что добавилась логика того, что при открытии слайда с видео оно должно включаться сразу, у меня не получилось это реализовать. Потому что при autoplay=true в нативном теге video все видео включаются сразу в галерее из-за реализации swiper (там все слайды рендерятся сразу но скрываются, и видео играет как-бы на фоне, но не отображается). Поэтому мне нужно глобальное состояние и по нему включать и отключать видео и ориентироваться на isActive пропс от свайпера. Если я не так понял, можешь плз накидать пример реализации в комментах. У меня не получилось норм сделать, всегда вылазило старанное поведение

2024-08-30 14:14 UTC, fulcanellee approved these changes

2024-09-02 08:40 UTC, Valeri8888 approved these changes

2024-09-02 15:27 UTC, EvKravcov approved these changes

2024-09-23 20:31 UTC, hextion commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +    useEffect(() => {
понимаю, что возможно есть проблема со swiper. несмотря на это возникают баги, потому что react не понимает _действительное_ состояние видео. например после окончания видео его невозможно включить заново, при изменении громкости видео кнопками телефона иконка показывает "без звука" и звук не активируется, хотя наверное должен. именно для этого нужны подписки на соответствушие эвенты. я настоятельно рекомендую исправить это

2024-09-24 08:32 UTC, temss-front commented
> Чет у меня на айфоне ни в сафари, ни в хроме демка не запустилась

я проверил, у меня вроде норм все открылось

2024-09-24 09:20 UTC, hextion approved these changes

2024-09-24 09:23 UTC, hextion commented on packages/gallery/src/components/image-viewer/video/index.tsx
> +    useEffect(() => {
@temss-front поставил апрув, заведи пож-та задачу на доработку. можешь оставить ссылку на комментарий выше в задачу

2024-09-24 10:03 UTC, merged