feat/calendar_month_period
core-ds/core-components pull request #1319
Opened 2024-07-25 14:49 UTC by fulcanellee

2024-07-29 13:25 UTC, hextion requested changes

2024-07-29 13:25 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +        if (clickableMonth && !maxDateTimestamp) {
откуда такая логика? выбор месяца может происходить из месяцев в будущем, не?

2024-07-29 13:25 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +    const [currentActiveMonth, setCurrentActiveMonth] = useState('');
это значение должно выводиться из значения, выбранного в календаре - пропс `value`

2024-07-30 11:24 UTC, Oladii reviewed
<img width="479" alt="image" src="https://github.com/user-attachments/assets/5db3e329-d2e3-4947-85c1-3c6ff65e65aa">
чет не то со скруглениями

2024-07-30 11:25 UTC, Oladii reviewed
еще у нас оказалась поломанной логика кнопок в футере, ее бы тоже починить и привести к макету, и раз в реквесте есть что доделать, я бы в нём же это и сделал

2024-08-12 06:25 UTC, fulcanellee commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +        if (clickableMonth && !maxDateTimestamp) {
все верно, последующие нельзя выбирать

2024-08-12 10:05 UTC, fulcanellee commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +    const [currentActiveMonth, setCurrentActiveMonth] = useState('');
этот стейт нужен для работы с заголовком месяца. value в этом случае будет пустым. переименовал чтобы более понятно было к чему относится.

2024-08-15 08:52 UTC, Oladii approved these changes

2024-08-15 12:19 UTC, SiebenSieben commented on packages/calendar/src/components/calendar-mobile/index.module.css
> +        border-radius: 999px;
Для этого есть переменная border-radius-pill

2024-08-15 12:20 UTC, SiebenSieben approved these changes

2024-08-15 12:55 UTC, hextion approved these changes

2024-08-15 13:41 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +    const [activeMonthLabel, setActiveMonthLabel] = useState('');
```
clickableMonth ? computed selected month : null

click month -> range (start, min(end, maxDate)) month
```

2024-08-15 16:26 UTC, alex-iatsenko approved these changes

2024-08-16 06:34 UTC, merged