Fix/tabs dependency
core-ds/core-components pull request #1322
Opened 2024-07-26 11:41 UTC by stovv

# Опишите проблему
@alfalab/core-components-tabs использует скелетон из @alfalab/core-components, вместо @alfalab/core-components-skeleton напрямую

# Тестовый стенд

## Десктоп (если данных нет оставте блок пустым):
 - OS: MacOS
 - Browser: Safari
 - Version: 10

2024-07-26 11:47 UTC, Valeri8888 commented on .changeset/sour-jeans-report.md
> +Добавлен слот снизу
опиши подробнее плиз 
что-то типа добавлено новое свойство bottomAddons, отвечающее...

2024-07-27 10:09 UTC, stovv commented on .changeset/sour-jeans-report.md
> +Добавлен слот снизу
Извиняюсь, пятничный кормит был 😅, лишний коммит в ветку притащил, поправил

2024-07-29 13:21 UTC, hextion requested changes

2024-07-29 13:21 UTC, hextion commented on .changeset/new-doors-peel.md
> +Поправлен импорт компонента skeleton
кажется нужно зависимость в `package.json` нужно указать еще

2024-07-29 21:15 UTC, stovv commented on .changeset/new-doors-peel.md
> +Поправлен импорт компонента skeleton
В `package.json` верная зависимость
https://github.com/core-ds/core-components/blob/1b2d9544025f9342c8e8ac926aa2acdffa7faa49/packages/tabs/package.json#L25

2024-07-30 07:16 UTC, Valeri8888 approved these changes

2024-07-30 08:56 UTC, hextion approved these changes

2024-08-01 09:09 UTC, stovv commented
@reme3d2y @fulcanellee @SiebenSieben, гляньте плс

2024-08-12 12:51 UTC, fulcanellee approved these changes

2024-08-22 12:55 UTC, stovv commented
@SiebenSieben, посмотри пжлст

2024-09-04 08:22 UTC, SiebenSieben approved these changes

2024-09-04 08:26 UTC, merged