feat(select): added new prop groupOptionsProp to SelectProps, setHighlightedIndex prop to OptgroupProps
core-ds/core-components pull request #1336
Opened 2024-08-16 08:33 UTC by NikitaRodyukov

Добавил пропс groupOptionsProp для прокидки дополнительных пропсов в компонент  Optgroup
Добавил возможность использования setHighlightedIndex внутри Optgroup

2024-08-16 08:52 UTC, SiebenSieben approved these changes

2024-08-16 11:57 UTC, hextion requested changes

2024-08-16 11:57 UTC, hextion commented on packages/select/src/components/options-list/Component.tsx
> +            groupOptionProps = {},
следует добавить еще в `VirtualOptionsList`

2024-08-16 12:42 UTC, NikitaRodyukov commented on packages/select/src/components/options-list/Component.tsx
> +            groupOptionProps = {},
Добавил

2024-08-19 20:02 UTC, hextion approved these changes

2024-08-20 09:28 UTC, merged