Fix/clickable month improve
core-ds/core-components pull request #1337
Opened 2024-08-19 11:54 UTC by fulcanellee

2024-08-19 19:58 UTC, hextion requested changes

2024-08-19 19:58 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +                firstAvailableDayOfMonth === dateFrom &&
isSameDay

2024-08-19 19:58 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +    const isActiveMonthLabel = (currentMonthIndex: number) => {
`isMonthActive` кажется лучше подходит

2024-08-19 19:58 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +            firstAvailableDayOfMonth: startOfMonth(new Date(item.date)).getTime(),
не совсем ясно, зачем его тут считать. можно в месье использования посчитать

2024-09-02 07:37 UTC, hextion approved these changes

2024-09-02 07:37 UTC, hextion commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +            lastAvailableDayOfMonth: isThisMonth(item.date)
давай тоже в месте использования посчитаем?

2024-09-02 10:35 UTC, fulcanellee commented on packages/calendar/src/components/calendar-mobile/Component.tsx
> +            lastAvailableDayOfMonth: isThisMonth(item.date)
исправил

2024-09-02 12:03 UTC, merged