chore: update codeowners
core-ds/core-components pull request #1383
Opened 2024-09-18 12:35 UTC by fulcanellee

2024-09-18 17:18 UTC, hextion requested changes

2024-09-18 17:18 UTC, hextion commented on .storybook/pages/intro/index.tsx
> +const MAINTAINERS = ['reme3d2y', 'Oladii', 'SiebenSieben', 's_gizatov', 'm_lukin'];
здесь должны быть github никнеймы, иначе ссылки неверно строятся

2024-09-19 06:10 UTC, fulcanellee commented on .storybook/pages/intro/index.tsx
> +const MAINTAINERS = ['reme3d2y', 'Oladii', 'SiebenSieben', 's_gizatov', 'm_lukin'];
точно, не проверил переход по ссылке. поправил

2024-09-19 10:10 UTC, hextion approved these changes

2024-09-20 09:24 UTC, SiebenSieben approved these changes

2024-09-20 11:00 UTC, Oladii approved these changes

2024-09-20 11:00 UTC, merged