Icon-view: оптимизация кривых
core-ds/core-components pull request #1384
Opened 2024-09-18 12:56 UTC by denisx

# Опишите проблему
Произвёл автоматическую оптимизацию кривых

# Внешний вид
Практически не поменялся

# Тестовый стенд

2024-09-18 17:21 UTC, hextion requested changes

2024-09-18 17:21 UTC, hextion commented on .changeset/pretty-squids-tease.md
> +small refactoring: inner utils, types, fix story
не соответствует содержанию PR и желательно на русском

2024-09-20 08:53 UTC, Oladii commented
визуально разницы не вижу, поэтому ок

2024-09-20 08:53 UTC, Oladii approved these changes

2024-09-20 08:58 UTC, fulcanellee approved these changes

2024-09-20 09:21 UTC, denisx commented on .changeset/pretty-squids-tease.md
> +small refactoring: inner utils, types, fix story
поправил

2024-09-20 09:22 UTC, hextion approved these changes

2024-09-23 07:51 UTC, SiebenSieben approved these changes

2024-09-23 07:51 UTC, merged