feat(space): add current key for Item
core-ds/core-components pull request #1395
Opened 2024-09-25 17:51 UTC by VladislavNsk

# Опишите проблему
При использовании компонента Space, если удалить дочерний элемент, то все остальные элементы размонитруются и смонтируются заново, при условии что key никак не меняется при этом

# Шаги для воспроизведения
Добавить в Space несколько элементов и после удалить первый
```
<Space>
  {rows.map(({text, id}) => (
      <Component key={id}>
        {text}
      </Component>        
  ))}
</Space>
<button>
 Удалить первую строку
</button>
```

Пример можно посмотреть тут
https://codesandbox.io/s/infallible-water-27jjg5?file=/src/index.js

# Ожидаемое поведение
Удалится первый элемент, остальные никак не среагируют на это

# Чек лист
- [ ] Тесты
- [ ] Документация

2024-09-27 08:40 UTC, hextion requested changes

2024-09-27 08:40 UTC, hextion commented on packages/space/src/Component.tsx
> +            key={(child as ReactElement).key}
```
import {isValidElement} from 'react';

key={isValidElement(child) ? child.key : `${itemClassName}-${i}`}
```

2024-10-14 08:34 UTC, hextion approved these changes

2024-10-14 09:10 UTC, fulcanellee approved these changes

2024-10-29 07:19 UTC, closed without merging