feat(pure-cell): для Amount и AmountTitle добавлено состояние hidden
core-ds/core-components pull request #1397
Opened 2024-10-01 12:44 UTC by temss-front

2024-10-02 08:42 UTC, hextion requested changes

2024-10-02 08:42 UTC, hextion commented on packages/pure-cell/src/components/amount-title/component.tsx
>          <Typography.TitleResponsive
`showSkeleton` не подходит?

2024-10-02 08:42 UTC, hextion commented on packages/pure-cell/src/components/amount/component.tsx
>              view={textView}
`showSkeleton` не подходит?

2024-10-02 09:16 UTC, temss-front commented on packages/pure-cell/src/components/amount-title/component.tsx
>          <Typography.TitleResponsive
нет, команде потребовалась доработка, чтоб было скрытие, а не скелетон. в skeletonProps нет нужных настроек, чтоб настроить его под нужный вид. я пробовал

2024-10-02 09:27 UTC, hextion commented on packages/pure-cell/src/components/amount-title/component.tsx
>          <Typography.TitleResponsive
давай занеймим по-другому, потому что это не скелетон по факту)

2024-10-02 09:42 UTC, hextion commented on packages/pure-cell/src/components/amount-title/component.tsx
> +                    styles[`skeletonWrapper-${titleProps?.view ?? titleDefaultProps.view}`],
`titleDefaultProps.view` достаточно

выше `titleProps` подмешиваются в `titleDefaultProps`
может заодно поправишь этот момент, потому что по факту это не дефолтные пропсы

```
titleProps: titlePropsFromProps = {}
...
const titleProps = {
        tag: 'h4',
        view: 'small',
        color,
        ...titlePropsFromProps,
    } as Omit<TitleProps, 'className' | 'dataTestId'>;
```

2024-10-02 13:31 UTC, temss-front commented on packages/pure-cell/src/components/amount-title/component.tsx
>          <Typography.TitleResponsive
поменял

2024-10-02 13:31 UTC, temss-front commented on packages/pure-cell/src/components/amount-title/component.tsx
> +                    styles[`skeletonWrapper-${titleProps?.view ?? titleDefaultProps.view}`],
исправил

2024-10-02 14:13 UTC, hextion approved these changes

2024-10-02 14:13 UTC, hextion commented on packages/pure-cell/src/components/amount-title/component.tsx
> +            className={cn(styles.component, titlePropsFromProps?.className)}
`titleProps` можно было оставить)

2024-10-02 14:14 UTC, hextion approved these changes

2024-10-02 14:14 UTC, hextion commented on .changeset/serious-clouds-reply.md
> +Для Amount и AmountTitle добавлено состояние hidden, когда значение скрывается скелетоном
описание не совсем корректное - опять упоминание скелетона

2024-10-03 06:02 UTC, fulcanellee approved these changes

2024-10-03 11:30 UTC, temss-front commented on packages/pure-cell/src/components/amount-title/component.tsx
> +            className={cn(styles.component, titlePropsFromProps?.className)}
У него в типе omit classnames поэтому ругался ts

2024-10-04 09:06 UTC, SiebenSieben approved these changes

2024-10-04 09:46 UTC, merged