Fix/base modal unlock scroll
core-ds/core-components pull request #1419
Opened 2024-10-17 19:02 UTC by renbrek

Решает проблему, когда скролл не разблокируется при закрытии модального окна при помощи свойства `open={false}`

https://github.com/core-ds/core-components/issues/1325

2024-10-22 07:11 UTC, renbrek commented
@reme3d2y @fulcanellee @SiebenSieben @hextion

2024-10-22 10:19 UTC, fulcanellee approved these changes

2024-10-29 06:30 UTC, renbrek commented
@reme3d2y @SiebenSieben @hextion, ребят, посмотрите, пожалуйста, хочется в спринт успеть таску закрыть)

2024-11-01 07:21 UTC, hextion requested changes

2024-11-01 07:21 UTC, hextion commented on packages/base-modal/src/Component.tsx
> +            if (!open && isScrollLocked()) {
может перенесем проверку `isScrollLocked ` в `unlockScroll`, чтобы не писать проверку каждый при его использовании?

2024-11-01 07:30 UTC, renbrek commented on packages/base-modal/src/Component.tsx
> +            if (!open && isScrollLocked()) {
Звучит логично)

2024-11-02 09:23 UTC, hextion commented
залито в https://github.com/core-ds/core-components/pull/1434

2024-11-02 09:23 UTC, closed without merging