feat(input): prevent input of [eE] characters
core-ds/core-components pull request #1422
Opened 2024-10-21 11:02 UTC by fulcanellee

https://rc.alfa-bank.net/channel/core-components-support/thread/JWgyzxj2PG7pT9cW7?msg=JWgyzxj2PG7pT9cW7

Предотвращает ввод символов [eE] в input[type=number]

2024-10-21 11:48 UTC, hextion requested changes

2024-10-21 11:48 UTC, hextion commented on packages/input/src/components/base-input/Component.tsx
> +            [restProps],
бесполезный useCallback получается, пропсы постоянно меняются

2024-10-21 11:48 UTC, hextion commented on packages/input/src/components/base-input/Component.tsx
> +            (e: KeyboardEvent<HTMLInputElement>) => {
event?

2024-10-22 07:14 UTC, fulcanellee commented on packages/input/src/components/base-input/Component.tsx
> +            [restProps],
исправил

2024-10-22 07:14 UTC, fulcanellee commented on packages/input/src/components/base-input/Component.tsx
> +            (e: KeyboardEvent<HTMLInputElement>) => {
исправил

2024-10-23 08:17 UTC, hextion approved these changes

2024-11-07 08:14 UTC, fulcanellee commented
> вставить 2e5 все еще можно

Исправил

2024-11-08 08:09 UTC, fulcanellee commented on packages/input/src/components/base-input/Component.tsx
> +                const inInputTypeNumber = target.getAttribute('type') === 'number';
опечатался, подразумевал isInputTypeNumber. Исправлю

2024-12-04 08:27 UTC, SiebenSieben approved these changes

2024-12-26 10:00 UTC, merged