feat: add core-config
core-ds/core-components pull request #1426
Opened 2024-10-24 10:17 UTC by reme3d2y

2024-10-24 10:27 UTC, hextion commented on .github/workflows/core-config-publish.yml
> +        if: ${{ contains(fromJSON('["reme3d2y","Valeri8888","SiebenSieben","fulcanellee"]'), github.actor) == false }}
Valeri8888 не актуально, а я актуален)

2024-10-24 10:31 UTC, fulcanellee approved these changes

2024-10-28 21:01 UTC, hextion approved these changes

2024-11-01 11:14 UTC, hextion approved these changes

2024-11-05 12:54 UTC, hextion requested changes

2024-11-05 12:54 UTC, hextion commented on packages/textarea/src/Component.tsx
> +        const [textareaNode, setTextareaNode] = useState<HTMLTextAreaElement | null>(null);
нельзя в стейт положить реф, некорректно с точки зрения react. подробнее и варианты решений [тут](https://github.com/facebook/react/issues/21903)

2024-11-15 09:19 UTC, hextion commented on packages/textarea/src/Component.tsx
> +        const [textareaNode, setTextareaNode] = useState<HTMLTextAreaElement | null>(null);
@reme3d2y поправь пож-та)

2024-11-18 09:38 UTC, SiebenSieben approved these changes

2024-11-18 12:32 UTC, hextion approved these changes

2024-11-18 13:06 UTC, merged