Fix/ampay 6720
core-ds/core-components pull request #1437
Opened 2024-11-05 11:52 UTC by mikhail-yurin

# Опишите проблему
Не отображается флаг для кодов номеров Абхазии

# Шаги для воспроизведения
1. ввести код `+7840` или `+7940`

# Ожидаемое поведение
Отображается флаг Абхазии

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

2024-11-05 13:09 UTC, hextion requested changes

2024-11-05 13:09 UTC, hextion commented on packages/international-phone-input/src/data/country-data.ts
> +    ['Абхазия', ['europe'], 'ge-ab', '7', '... ... .. ..', 1, ['840', '940']],
добавим changeset?

2024-11-05 14:22 UTC, mikhail-yurin commented on packages/international-phone-input/src/data/country-data.ts
> +    ['Абхазия', ['europe'], 'ge-ab', '7', '... ... .. ..', 1, ['840', '940']],
добавлю, только расскажи что это?)) ченджлог какой-то?))

2024-11-05 17:05 UTC, hextion commented on packages/international-phone-input/src/data/country-data.ts
> +    ['Абхазия', ['europe'], 'ge-ab', '7', '... ... .. ..', 1, ['840', '940']],
да) `npx changeset` открывает визард в котором формируется ченджлог

2024-11-06 08:49 UTC, mikhail-yurin commented on packages/international-phone-input/src/data/country-data.ts
> +    ['Абхазия', ['europe'], 'ge-ab', '7', '... ... .. ..', 1, ['840', '940']],
сделал

2024-11-06 08:51 UTC, mikhail-yurin commented
> упал скриншот-тест, для обновления запусти `yarn test:screenshots -u` (предварительно можешь еще `yarn clean` для удаления артефактов сборки, если вдруг ты билдил проект)

а вот тут странно. Почему может упасть тест для компонента, который не затронут в МР?
+локальный запуск тестов на Linux выдал вот такое
```
Test Suites: 105 failed, 1 skipped, 105 of 106 total
Tests:       1143 failed, 5 skipped, 4 passed, 1152 total
```

2024-11-06 09:29 UTC, mikhail-yurin commented
> > упал скриншот-тест, для обновления запусти `yarn test:screenshots -u` (предварительно можешь еще `yarn clean` для удаления артефактов сборки, если вдруг ты билдил проект)
> 
> а вот тут странно. Почему может упасть тест для компонента, который не затронут в МР? +локальный запуск тестов на Linux выдал вот такое
> 
> ```
> Test Suites: 105 failed, 1 skipped, 105 of 106 total
> Tests:       1143 failed, 5 skipped, 4 passed, 1152 total
> ```

попутал насчет незатронутого компонента :)

2024-11-07 13:37 UTC, hextion approved these changes

2024-11-08 06:05 UTC, fulcanellee approved these changes

2024-11-08 09:17 UTC, merged