feat(table): add forward ref to TExpandableRow
core-ds/core-components pull request #1462
Opened 2024-11-22 08:33 UTC by PONYAWKA

# Опишите проблему
У компонента TExpandableRow отсутствовал ref

# Ожидаемое поведение
у TExpandableRow есть ref

2024-11-22 12:30 UTC, fulcanellee approved these changes

2024-11-26 09:12 UTC, hextion requested changes
добавь пож-та changeset

```
npx changeset
```

2024-11-27 09:58 UTC, hextion requested changes

2024-11-27 09:58 UTC, hextion commented on .changeset/chilled-maps-press.md
> +add forawrdRef to TExpandableRow
Описание на русском пож-та

2024-11-27 10:06 UTC, hextion approved these changes

2024-11-28 10:03 UTC, SiebenSieben approved these changes

2024-11-28 11:56 UTC, merged