feat: pure-sell - add atoms exports
core-ds/core-components pull request #1467
Opened 2024-11-26 16:24 UTC by denisx

# Опишите проблему
Для лучшего тришейка:

-   Добавлены атомарные экспорты
-   В package.json добавлено sideEffects:false

# Внешний вид
Без изменений. Дополнена документация:

2024-11-27 15:11 UTC, reabiliti approved these changes

2024-11-28 04:30 UTC, fulcanellee approved these changes

2024-12-03 15:12 UTC, hextion requested changes

2024-12-03 15:12 UTC, hextion commented on packages/pure-cell/src/component.tsx
> +const ExtraSubtitle = FooterText as React.FC<FooterTextProps>;
зачем кастинг типа? все же корректно должно быть

2024-12-03 16:17 UTC, denisx commented on packages/pure-cell/src/component.tsx
> +const ExtraSubtitle = FooterText as React.FC<FooterTextProps>;
откуда мне знать, я не трогаю код в этом пр ) вынес как было

2024-12-05 08:29 UTC, denisx commented on packages/pure-cell/src/component.tsx
> +const ExtraSubtitle = FooterText as React.FC<FooterTextProps>;
@hextion ping

2024-12-25 09:40 UTC, hextion approved these changes

2024-12-25 09:40 UTC, merged