feat(custom-button): slit custom button by desktop / mobile
core-ds/core-components pull request #1472
Opened 2024-11-29 08:26 UTC by fulcanellee

Добавляет возможность использовать custom button для desktop / mobile по отдельности

2024-11-29 18:08 UTC, denisx commented
добавь плез `sideEffects: false` в package.json этого пакета. ему полегче станет

2024-12-03 14:27 UTC, hextion requested changes

2024-12-03 14:27 UTC, hextion commented on packages/custom-button/src/Component.tsx
> +        <Button
здесь разве не должен быть вилка десктоп или мобилка?

2024-12-03 15:41 UTC, denisx commented on .changeset/tall-mugs-clap.md
> +'@alfalab/core-components-custom-button': patch
minor

2024-12-03 15:41 UTC, denisx commented on packages/custom-button/src/Component.tsx
> +        <Button
тут вилка внутри той button, без разницы (если нет других оснований)

2024-12-03 15:41 UTC, denisx commented on packages/custom-button/src/mobile/Component.mobile.tsx
> +        <ButtonMobile
не критично, но 3 раза дублируется тело компонент.
как по мне - я бы сделал customButtonBase где будет вся логика, и 3 внешних DI точки входа, где будете готовить импорты и передавтаь в пропсы
т.к. desktop/mobile/responsive -> base

2024-12-03 15:42 UTC, denisx commented on packages/custom-button/src/mobile/Component.mobile.tsx
> +        <ButtonMobile
т.е. base вариант сам по себе светиться наружу не будет, т.к. у него не будет импортов

2024-12-03 15:44 UTC, denisx commented on packages/custom-button/src/desktop/Component.desktop.tsx
> +    CustomButtonProps
если разницы между desktop/mobile по внешнему интерфейсу нет - то можно оставлять единый базовый (только без DI пропсов) тут смотрите по требованию

2024-12-11 08:06 UTC, fulcanellee commented
Переделал реализацию. Теперь разделение проходит через базовый (base) компонент. Просьба проверить заново.

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/Component.test.tsx
> +import { CustomButton, CustomButtonDesktop, CustomButtonMobile } from './index';
тут вопрос к обсуждению: надо ли придерживаться стратегии, что десктоп должен быть доступен из сustom-button/desktop?
или ЕЩЁ и из index? или только в индекс?
чтобы единообразно было. привычно. я не знаю как принято

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { Button } from '@alfalab/core-components-button';
```suggestion
import { type Button } from '@alfalab/core-components-button';
```

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { ButtonDesktop } from '@alfalab/core-components-button/desktop';
```suggestion
import { type ButtonDesktop } from '@alfalab/core-components-button/desktop';
```

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { ButtonMobile } from '@alfalab/core-components-button/mobile';
```suggestion
import { type ButtonMobile } from '@alfalab/core-components-button/mobile';
```

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +                styles[`disableType-${disableType}`],
```suggestion
                styles[`disableType_${disableType}`],
```

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/docs/Component.stories.tsx
> +            </CustomButtonMobile>
вопрос к обсуждению: не нужно ли сделать common/base -стори, и также через DI кидать туда зависимости? а то копипасты 20 строк

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +        component: typeof Button | typeof ButtonDesktop | typeof ButtonMobile;
может так и обозвать пропсу? ComponentButton?

2024-12-11 08:45 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +                styles[`disableType-${disableType}`],
при обновлении линтеры приедут, там правило нижнего регистра

2024-12-11 10:36 UTC, fulcanellee commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +                styles[`disableType-${disableType}`],
когда добавлял disableType изначально делал в snake_case, но на ревью попросили kebab-kase по аналогии с другими классами.

2024-12-11 10:38 UTC, fulcanellee commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +        component: typeof Button | typeof ButtonDesktop | typeof ButtonMobile;
назавал base по аналогии с другими компонентами в библиотеке

2024-12-11 10:41 UTC, fulcanellee commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +        component: typeof Button | typeof ButtonDesktop | typeof ButtonMobile;
поправлю

2024-12-20 06:17 UTC, fulcanellee commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { Button } from '@alfalab/core-components-button';
в данном случае мы достаем именно компонент, потом делаем от него typeof

2024-12-20 06:17 UTC, fulcanellee commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { ButtonMobile } from '@alfalab/core-components-button/mobile';
в данном случае мы достаем именно компонент, потом делаем от него typeof

2024-12-20 06:19 UTC, fulcanellee commented on packages/custom-button/src/docs/Component.stories.tsx
> +            </CustomButtonMobile>
пока такого не видел у нас в либе

2024-12-20 06:43 UTC, denisx commented on packages/custom-button/src/components/base-custom-button/base-custom-button.tsx
> +import { Button } from '@alfalab/core-components-button';
посмотрю билд попозже. по идее так тоже должен схлопнуть.

2024-12-21 22:21 UTC, denisx commented on packages/custom-button/src/Component.test.tsx
> +import { CustomButton, CustomButtonDesktop, CustomButtonMobile } from './index';
нужно ли добавлять в корневой индекс? или привычней будет стандартно из /desktop и /mobile доставать?

2024-12-23 06:02 UTC, fulcanellee commented on packages/custom-button/src/Component.test.tsx
> +import { CustomButton, CustomButtonDesktop, CustomButtonMobile } from './index';
исправил

2024-12-23 07:46 UTC, denisx approved these changes

2024-12-25 17:27 UTC, SiebenSieben commented
@Oladii

2024-12-25 17:30 UTC, SiebenSieben commented on packages/custom-button/src/constants/default-colors.ts
> +export const DEFAULT_BUTTON_COLOR = '#FF45C3';
Какой смысл по дефолту делать кнопку такого цветом? Предлагаю поменять на accent-secondary

2024-12-26 06:53 UTC, fulcanellee commented on packages/custom-button/src/constants/default-colors.ts
> +export const DEFAULT_BUTTON_COLOR = '#FF45C3';
этот цвет там был изначально, я просто вынес его в отельный файл

https://github.com/core-ds/core-components/blob/master/packages/custom-button/src/Component.tsx#L8-L9

2024-12-26 09:05 UTC, SiebenSieben approved these changes

2024-12-26 11:16 UTC, merged