feat: move to common lodash package;
core-ds/core-components pull request #1477
Opened 2024-12-01 22:22 UTC by denisx

# Опишите проблему
Переход на единый lodash пакет. В продуктовом использовании единый пакет доставляем меньше нагрузки на бандл, чем атомарные, т.к. устанавливается множество несинхронный версий, в отличие от lodash в resolution
Сами импорты из пакета не дают лишний вес сборки, при использовании таким образом: "import foo from lodash/foo"

# Ожидаемое поведение
Без изменений

2024-12-03 07:20 UTC, fulcanellee approved these changes

2024-12-03 15:23 UTC, hextion requested changes

2024-12-03 15:23 UTC, hextion commented on .changeset/beige-kangaroos-try.md
> +'@alfalab/core-components-collapse': minor
патч, не минор

2024-12-03 16:16 UTC, denisx commented on .changeset/beige-kangaroos-try.md
> +'@alfalab/core-components-collapse': minor
х о р о ш о

2024-12-05 13:14 UTC, denisx commented on .changeset/beige-kangaroos-try.md
> +'@alfalab/core-components-collapse': minor
@hextion done

2024-12-11 10:46 UTC, merged