feat: classname update to 2.5.1
core-ds/core-components pull request #1478
Opened 2024-12-01 23:10 UTC by denisx

# Опишите проблему
В последних версиях вендора произведена оптимизация по скорости работы.

# Ожидаемое поведение
Без изменений

2024-12-01 23:15 UTC, denisx commented on packages/card-image/package.json
> +        "classnames": "^2.5.1",
Нашлось одно место, где не общепринятый подход. Сделал как везде

2024-12-03 07:21 UTC, fulcanellee approved these changes

2024-12-03 15:22 UTC, hextion requested changes

2024-12-03 16:14 UTC, denisx commented on .changeset/chilly-badgers-hear.md
> +'@alfalab/core-components-accordion': minor
я колебался. ну патч так патч

2024-12-05 13:13 UTC, denisx commented on .changeset/chilly-badgers-hear.md
> +'@alfalab/core-components-accordion': minor
@hextion done

2024-12-11 08:19 UTC, hextion approved these changes

2024-12-11 08:19 UTC, merged