fix: product-cover: исправлено название пропса numberOfCards
core-ds/core-components pull request #1489
Opened 2024-12-10 22:05 UTC by denisx

# Опишите проблему
Исправлено название пропса numberOfCards. Старый пропс (numberOfСards с русской C) оставлен для обратной совместимости, но помечен как деприкейт. При использовании сразу обоих, новый имеет приоритет.

## Если есть визуальные изменения
Без изменений https://core-ds.github.io/core-components/fix_product_cover_11_12_2024_7c6f4c4e928a5fa99d748231cfd8ec220f6e7974/?path=/docs/productcover--docs

2024-12-25 17:00 UTC, SiebenSieben approved these changes

2025-01-09 07:56 UTC, hextion requested changes

2025-01-09 07:56 UTC, hextion commented on .changeset/big-apples-vanish.md
> +   - Микро-оптимизация: импорт кнопки заменён с десктоной на мобильный. (Мобильная сборка имеет приоритет по размеру, поэтому не нужно тащить туда десктопные импорты.)
сделай пож-та в другом PR, к этому изменению отношения не имеет

2025-01-09 10:32 UTC, fulcanellee approved these changes

2025-01-10 09:24 UTC, hextion approved these changes

2025-02-07 08:39 UTC, fulcanellee commented
Поправь плиз скриншоты и зарелизим

2025-04-11 09:56 UTC, merged