feat(typography): organize folders
core-ds/core-components pull request #1498
Opened 2024-12-14 20:47 UTC by denisx

# Опишите проблему
Структура папок и файлов осталась от старой версии коммон-версии компонента.
Привёл в порядок к стандартному сплит д/м

# Внешний вид
Без изменений

2024-12-14 20:51 UTC, denisx commented on packages/typography/src/component.ts
> +import type { FC, ForwardRefExoticComponent, RefAttributes } from 'react';
файл переименован tsx -> ts

2024-12-17 06:40 UTC, fulcanellee approved these changes

2024-12-26 11:24 UTC, hextion requested changes

2024-12-26 11:24 UTC, hextion commented on packages/typography/src/title/desktop/component.tsx
> +        styles={Object.assign(commonStyles, styles)}
`Object.assign({}, commonStyles, styles)`

2025-09-19 11:21 UTC, fulcanellee commented
Пинговал по доработкам, 3 месяца назад. На данном этапе PR закрываю. Если потребуется дотащить - переоткройте или создайте новый.

2025-09-19 11:21 UTC, closed without merging