feat(status-badge): add StatusBadgeBlank; without preload icons
core-ds/core-components pull request #1500
Opened 2024-12-15 20:44 UTC by denisx

# Опишите проблему
   - Добавлен StatusBadgeBlank, без предзагрузки иконок
   - Расширен пропс customIcons, теперь он принимает не только структуру иконок, но и массив таких структур (для загрузки сразу нескольких сетов)

# Чек лист
- [х] Документация

# Внешний вид
Без изменений

2024-12-15 20:45 UTC, denisx commented on packages/status-badge/src/hooks/useStatusBadgeIcon.ts
> +export const combineIcons = (
Просто вытащил ф-ию из хука

2024-12-17 06:28 UTC, fulcanellee requested changes

2024-12-17 06:28 UTC, fulcanellee commented on packages/status-badge/src/consts/iconMap.ts
>      'positive-checkmark': {
Если единая мапка делится на несколько разных, которые содержат перечисления единственного размера то теряется смысл в цифре `16:` , `20:` и т. д.  
```
16: CheckmarkCompactSIcon
```

```suggestion
    'positive-checkmark': CheckmarkCompactSIcon
```

2025-09-19 11:21 UTC, fulcanellee commented
Пинговал по доработкам, 3 месяца назад. На данном этапе PR закрываю. Если потребуется дотащить - переоткройте или создайте новый.

2025-09-19 11:22 UTC, fulcanellee commented
Пинговал по доработкам, 3 месяца назад. На данном этапе PR закрываю. Если потребуется дотащить - переоткройте или создайте новый.

2025-09-19 11:22 UTC, closed without merging