feat(vars): add dark colors generator
core-ds/core-components pull request #1501
Opened 2024-12-16 11:18 UTC by fulcanellee

Добавляет генерацию для dark тем

https://jira.moscow.alfaintra.net/browse/DS-8450

2024-12-19 11:41 UTC, SiebenSieben commented on .changeset/gold-jobs-dress.md
> +Добавлены `-dark.css` файлы для цветовых палитр
Предлагаю перечислить для каких

2024-12-19 11:43 UTC, SiebenSieben commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
colors-bluetint-dars.css это тот же набор, который в dark.css?

2024-12-19 13:20 UTC, fulcanellee commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
> colors-bluetint-dars.css это тот же набор, который в dark.css?

не знаю, просто сгенерил по тем файлам что лежали в vars в приставкой color-. как образован dark.css и на основе каких цветов мне не ведомо

2024-12-20 06:05 UTC, fulcanellee commented on .changeset/gold-jobs-dress.md
> +Добавлены `-dark.css` файлы для цветовых палитр
добавил

2024-12-20 06:11 UTC, fulcanellee commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
> вот я не понимаю что лежит тут https://github.com/core-ds/core-components/tree/master/packages/themes/src
> 
> а что тут, и по какому принципу https://github.com/core-ds/core-components/tree/master/packages/vars/src

в переменных лежат наборы, в темах переопределения переменных. по хорошему старый файл dark.css должен лежать в vars, но он находится в themes

2024-12-20 07:55 UTC, SiebenSieben commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
@fulcanellee 

Предлагаю пока исключить, при необходимости позже добавим

И как будто нужно исключить indigo-dark, файлик должен быть идентичен bluetint-dark (+ indigo депрекейтед палитра)

2024-12-20 07:56 UTC, SiebenSieben approved these changes

2024-12-20 08:57 UTC, Oladii commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
то есть всё равно они будут раскиданы по разным папкам, а в этом точно есть смысл, может попробовать перенести всё в одну?

2024-12-20 09:49 UTC, Oladii approved these changes

2024-12-23 07:58 UTC, hextion requested changes

2024-12-23 07:58 UTC, hextion commented on tools/dark-colors-generator.js
может на синхронный код или на промисы перепишем. колбэки это по-моему самое неудобное решение)

2024-12-26 09:54 UTC, fulcanellee commented on docs/colors.stories.mdx
> +- [core-components/vars/colors-bluetint-dark.css](https://github.com/core-ds/core-components/blob/master/packages/vars/src/colors-bluetint-dark.css).
добавил исключения для bluetint и indigo

2024-12-26 09:54 UTC, fulcanellee commented on tools/dark-colors-generator.js
переписал на синхронный код

2025-01-31 11:10 UTC, hextion approved these changes

2025-02-07 12:07 UTC, merged