fix(link): replace component with a button in pseudo mode
core-ds/core-components pull request #156
Opened 2022-07-18 22:05 UTC by CrybabyDanChan

Был заменен тэг "a" на "button" при pseudo режиме.
Для "button" обнулены дефолтные стили.

2022-07-27 09:25 UTC, EGNKupava approved these changes

2022-07-29 07:42 UTC, reme3d2y requested changes

2022-07-29 07:42 UTC, reme3d2y commented on packages/link/src/Component.tsx
> +        const LinkComponent = pseudo ? 'button' : Component;
Стоит это убрать в 86ую строчку. 

Component = pseudo ? 'button' : 'a',

2022-08-01 06:49 UTC, reme3d2y approved these changes

2022-08-01 08:42 UTC, Valeri8888 approved these changes

2022-08-19 11:46 UTC, SiebenSieben approved these changes

2022-09-06 15:46 UTC, merged