fix(filter-tag): fix closer icon colors
core-ds/core-components pull request #167
Opened 2022-07-21 18:49 UTC by AlexZJScript

Подправил цвета у иконки крестика в fillter-tag

2022-07-22 01:22 UTC, reme3d2y requested changes

2022-08-01 07:12 UTC, reme3d2y commented
@Oladii 
1. У крестика normal, hover и active цвета одинаковые?
2. Крестик скукожился
<img width="212" alt="image" src="https://user-images.githubusercontent.com/9968618/182092550-0650ae3a-294c-492a-83ce-712360e8a5bc.png">

2022-08-17 12:55 UTC, SiebenSieben commented
Да, как будто отступ не ок, ждём Влада, добавил в ревьюеры

2022-08-23 10:56 UTC, Oladii approved these changes

2022-08-26 08:37 UTC, SiebenSieben approved these changes

2022-08-26 08:38 UTC, SiebenSieben commented
Но не только ведь цвета поправил)

2022-08-29 01:59 UTC, reme3d2y approved these changes

2022-08-31 10:03 UTC, merged