feat(side-panel): add props imageUrl  and fix doc
core-ds/core-components pull request #168
Opened 2022-07-22 10:22 UTC by Valeri8888

Добавила пропсу imageUrl - для фона в шапке 
Обновила документацию

2022-07-28 08:25 UTC, Lacronts approved these changes

2022-07-29 07:44 UTC, reme3d2y requested changes
Отвалились скриншоты с футером

2022-08-01 08:38 UTC, Valeri8888 commented
> Отвалились скриншоты с футером

исправила

2022-08-17 12:53 UTC, SiebenSieben approved these changes

2022-08-18 07:40 UTC, EGNKupava approved these changes

2022-08-22 11:44 UTC, Valeri8888 commented
Локально тесты проходят

2022-08-23 11:49 UTC, NatalyaZ commented
Подскажите, пожалуйста, как можно посмотреть в стори фоновое изображение для Header?

2022-08-23 12:06 UTC, Valeri8888 commented
> Подскажите, пожалуйста, как можно посмотреть в истории фоновое изображение для заголовка?

Открыть "Показать код" в доке ->  в подкомпоненте SidePanelComponent.Header добавить пропсу imageUrl='https...'

2022-08-29 01:54 UTC, reme3d2y approved these changes

2022-08-30 11:55 UTC, NatalyaZ approved these changes

2022-09-01 10:12 UTC, merged