fix(progress-bar): mechanics of progress line fixed
core-ds/core-components pull request #169
Opened 2022-07-22 11:04 UTC by sadwizard

Пофиксил баг, проявлялся когда значение value превышало 100
<img width="1212" alt="Снимок экрана 2022-07-22 в 14 01 56" src="https://user-images.githubusercontent.com/7994677/180426322-6654bbe1-9d9c-4cb8-9cda-3b1d7420a86a.png">

2022-07-25 07:14 UTC, EGNKupava commented on packages/progress-bar/src/Component.tsx
> +        const restrictedValue = value < 0 ? 0 : value;
Можно было оставить TranslateX и ограничить максимальное значение. Плавнее анимируется вроде 
`restrictedMaxValue = value > 100 ? 100 : value`

2022-07-28 13:15 UTC, sadwizard commented on packages/progress-bar/src/Component.tsx
> +        const restrictedValue = value < 0 ? 0 : value;
Да, transition в свойствах не заметил. Но можно поменять в целом чтобы ширина анимировалась. А на width поменял потомучто кажется так компонент более очевидно работает.

2022-07-29 07:51 UTC, reme3d2y requested changes

2022-07-29 07:51 UTC, reme3d2y commented on packages/progress-bar/src/Component.tsx
> +                    style={{ width: `${restrictedMaxValue}%` }}
А для чего потребовалось менять transform на width? 
Почти никогда не стоит анимировать width\height\margin\padding, это лагает

2022-07-29 07:51 UTC, reme3d2y commented on packages/progress-bar/src/Component.tsx
> +        const restrictedMaxValue = value < 0 ? 0 : value;
```tsx
const translateX = Math.min(100, Math.max(0, value - 100));
```

2022-08-01 11:57 UTC, sadwizard commented on packages/progress-bar/src/Component.tsx
> +                    style={{ width: `${restrictedMaxValue}%` }}
Хм почитал, действительно бывают траблы c reflow. Переписал на трансформ обратно

2022-08-04 08:37 UTC, reme3d2y approved these changes

2022-08-04 08:45 UTC, Lacronts approved these changes

2022-08-04 10:53 UTC, merged