feat(BottonSheet): improved bottomSheet component
core-ds/core-components pull request #185
Opened 2022-08-08 09:37 UTC by mikhail-yurin

# [задача AMPAY-3174](http://jira.moscow.alfaintra.net/browse/AMPAY-3174)
на мобилках все еще были глюки c анимацией у компонента bottomSheet, ревертнул предыдущие правки с пропсом ignoreScreenChange, вместо этого добавил обертку для шторки т.к. этот вариант работает как надо, да и реализация гораздо проще чем с пропсом

2022-08-08 10:11 UTC, EGNKupava commented on packages/bottom-sheet/src/component.tsx
> -    ignoreScreenChange?: boolean;
А это у нас уже мажорка полчучается, если кто-то уже использует этот проп.

2022-08-08 10:26 UTC, mikhail-yurin commented on packages/bottom-sheet/src/component.tsx
> -    ignoreScreenChange?: boolean;
маловероятно, но проверить точно нужно. Есть у нас какие-то более быстрые способы проверить кроме как поиском по репам?

2022-08-08 10:48 UTC, mikhail-yurin commented on packages/bottom-sheet/src/component.tsx
> -    ignoreScreenChange?: boolean;
или оставить пропс но пометить что deprecated?

2022-08-08 11:27 UTC, SiebenSieben commented
Как увидеть глюк с анимацией? Есть какой-то скринкаст как было?
Хочется как-то потестить на айос/андроид девайсе, пытаюсь понять как)

2022-08-08 11:33 UTC, EGNKupava commented on packages/bottom-sheet/src/component.tsx
> -    ignoreScreenChange?: boolean;
:fire: так и хотел предложить

2022-08-08 11:33 UTC, EGNKupava approved these changes

2022-08-08 18:57 UTC, Lacronts commented
Такой вот баг теперь появился))
https://user-images.githubusercontent.com/40845033/183493239-7ec96aed-6ab1-4ae9-84d4-c23e8768febe.mov

2022-08-10 04:56 UTC, Lacronts commented on packages/bottom-sheet/src/component.tsx
> +     * DEPRECATED: данный проп больше не используется, временно оставлен для обратной совместимости
Чтобы IDE подсвечивала проп как deprecated нужно через собаку писать с маленькой буквы @deprecated

2022-08-10 10:41 UTC, reme3d2y requested changes
Скролл сломался :/

<img width="866" alt="image" src="https://user-images.githubusercontent.com/9968618/183882172-14158674-3385-4bd0-a6c1-7eb1e0d14f95.png">

2022-08-11 07:25 UTC, mikhail-yurin commented
> Как увидеть глюк с анимацией? Есть какой-то скринкаст как было? Хочется как-то потестить на айос/андроид девайсе, пытаюсь понять как)

прикрепил видосы к ПР

2022-08-11 07:25 UTC, mikhail-yurin commented on packages/bottom-sheet/src/component.tsx
> +     * DEPRECATED: данный проп больше не используется, временно оставлен для обратной совместимости
Поправил

2022-08-11 07:25 UTC, mikhail-yurin commented
> Такой вот баг теперь появился)) https://user-images.githubusercontent.com/40845033/183493239-7ec96aed-6ab1-4ae9-84d4-c23e8768febe.mov

поправил

2022-08-11 07:25 UTC, mikhail-yurin commented
> Скролл сломался :/
> 
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/9968618/183882172-14158674-3385-4bd0-a6c1-7eb1e0d14f95.png">

поправил

2022-08-12 07:20 UTC, Lacronts commented
Тесты падают, нужно пофиксить

2022-08-12 08:11 UTC, Lacronts approved these changes

2022-08-12 09:30 UTC, reme3d2y approved these changes

2022-08-12 10:13 UTC, merged