fix: renamed default classnames
core-ds/core-components pull request #198
Opened 2022-08-16 15:05 UTC by blackraydev

Переименованы default классы в компонентах PureCell и Spinner

2022-08-17 11:39 UTC, SiebenSieben approved these changes

2022-08-18 07:08 UTC, EGNKupava commented on packages/pure-cell/src/component.tsx
>                          styles[verticalPadding],
Но default все равно пытается взяться у styles. Может `verticalPaddingPaddingClass = verticalPadding === 'default'  ? defaultPadding : verticalPadding`, и тоже самое у horizontal. Или я что-то упускаю?

2022-08-18 07:12 UTC, EGNKupava commented on packages/spinner/src/Component.tsx
> +            className={cn(styles.spinner, colorStyles[colors].spinner, styles[sizeProp], className, {
класс spiner spiner, какое-то тонкое место

2022-08-18 07:12 UTC, EGNKupava commented on packages/pure-cell/src/components/footer/component.tsx
> +        className={cn(styles.component, styles[footerPadding], {
Тут пытается взять default класс, а его нет

2022-08-19 06:33 UTC, Lacronts approved these changes

2022-08-19 07:40 UTC, reme3d2y requested changes

2022-08-19 07:40 UTC, reme3d2y commented on packages/pure-cell/src/components/footer/component.tsx
> +            [styles.none]: footerPadding === 'none',
хм, а зачем styles.none если он ничего не меняет?

2022-08-19 07:40 UTC, reme3d2y commented on packages/pure-cell/src/components/addon/index.module.css
>          padding-left: var(--gap-m);
тут тоже странно. Есть дефолтный padding-left: var(--gap-m);, а при defaultPadding точно такой же паддинг

2022-08-19 07:40 UTC, reme3d2y commented on packages/pure-cell/src/component.tsx
> +                        { [styles.defaultPadding]: verticalPadding === 'default' },
выше ведь остался  styles[verticalPadding]? Давай вынесем формирование классов отдельно. Они ведь совпадают в 118й, 137й и 159й строчке

2022-08-29 01:37 UTC, reme3d2y approved these changes

2022-09-01 09:23 UTC, EGNKupava requested changes
Мы же можем не делать мажорных изменений?!

2022-09-01 09:23 UTC, EGNKupava commented on packages/pure-cell/src/component.tsx
> +            horizontalPadding = 'none',
А это норм что у кого-то были по дефолту отступы, а теперь они исчезнут?

2022-09-01 09:23 UTC, EGNKupava commented on packages/pure-cell/src/components/addon/component.tsx
> +    addonPadding?: boolean;
APi поменялось, Мажорка

2022-09-01 09:23 UTC, EGNKupava commented on packages/pure-cell/src/components/footer/component.tsx
> +    footerPadding?: boolean;
Мажорные изменения

2022-09-08 04:50 UTC, blackraydev commented on packages/pure-cell/src/component.tsx
> +            horizontalPadding = 'none',
У horizontalPadding могут быть только следующие значения: 'left' | 'right' | 'both' | 'none', не знаю почему там 'default' был указан

2022-09-08 09:13 UTC, Lacronts approved these changes

2022-09-08 09:42 UTC, EGNKupava approved these changes

2022-09-12 06:59 UTC, Valeri8888 approved these changes

2022-09-12 09:56 UTC, SiebenSieben approved these changes

2022-09-12 11:55 UTC, reme3d2y approved these changes

2022-09-12 15:45 UTC, merged