docs: добавил ссылки для компонентов в figma
core-ds/core-components pull request #202
Opened 2022-08-18 20:49 UTC by EGNKupava

:chart_with_upwards_trend: Добавил ссылки в figma для компонентов в соответствии с [таблицей](https://docs.google.com/spreadsheets/d/1s4LTGkL7pBfRh_KCbzF5UFRsV-L4M54tbt3kyf96IUY/edit#gid=0)

2022-08-19 05:30 UTC, SiebenSieben commented
Для каких нет ссылок?

2022-08-19 07:27 UTC, EGNKupava commented
> Для каких нет ссылок?

AmountInput
Backdrop
BankCard
BaseModal
CalendarInput
CalendarWithSkeleton
CardImage
CDNIcon
Chart
CodeInput
Collapse
Divider
Drawer
FormControl
Gallery
Grid
IntlPhoneInput
KeyboardFocusable
ListHeader
MaskedInput
Mq
NotificationManager
Pagination
PasswordInput
PhoneInput
Popover
Portal
PureInput
Skeleton
Space
Stack
Table
ToastPlate
withSuffix

2022-08-22 10:59 UTC, Oladii commented on packages/cdn-icon/src/docs/Component.stories.mdx
>  />
https://www.figma.com/file/ZcdUPebEhHfSZ91zgmv2cK/Icons?node-id=7392%3A10

2022-08-22 11:04 UTC, Oladii requested changes

2022-08-22 11:04 UTC, Oladii commented on packages/list/src/docs/description.mdx
> -
Можно поидее заменить ссылку на это
https://www.figma.com/file/2qkmYHFmV1rEmJyb6cEsW9/Web-%3A%3A-Mobile-Components?node-id=1153%3A300671

2022-08-22 11:04 UTC, Oladii commented on packages/cdn-icon/src/docs/Component.stories.mdx
>  />
https://www.figma.com/file/ZcdUPebEhHfSZ91zgmv2cK/Icons?node-id=7392%3A10

2022-08-22 11:43 UTC, Oladii commented on packages/cdn-icon/src/docs/Component.stories.mdx
>  />
На компоненты Alert и Plate над вот эту ссылку прицепить (только залили в фигму)
https://www.figma.com/file/cdNnkh2QdxuvYLrBm4cubM/Web-%3A%3A-Core-Default-Components?node-id=60647%3A87135

2022-08-23 11:12 UTC, Oladii approved these changes
Для кейсов где нет ссылок будем их добавлять по мере причесывания демок.

2022-09-01 08:49 UTC, Valeri8888 approved these changes

2022-09-01 10:07 UTC, SiebenSieben approved these changes

2022-09-01 10:11 UTC, merged