feat(code-input): update mobile version
core-ds/core-components pull request #230
Opened 2022-08-30 11:51 UTC by Valeri8888

Обновила мобильную (компактную) версию code-input
Добавила обработчик для клавиши Delete

2022-08-31 05:33 UTC, Lacronts commented on packages/code-input/src/component.tsx
> +                    } else {
Чтобы два раза не вызывалась focusOnInput
```               } else {
                        newValues[index] = '';
     
                        if (nextRef) {
                            focusOnInput(nextRef);
                        } else {
                            focusOnInput(curtRef);
                        }
                    }
```

2022-08-31 06:33 UTC, reme3d2y requested changes

2022-08-31 06:33 UTC, reme3d2y commented on packages/code-input/src/component.tsx
> +                    if (values[nextIndex]) {
Что-то тут странное написано. Можешь плз словами тут описать алгоритм действий?

2022-08-31 06:58 UTC, Valeri8888 commented on packages/code-input/src/component.tsx
> +                    if (values[nextIndex]) {
Если есть следующий символ от инпута в фокусе (так как удаление идет слева направо), то удали текущий символ и переключи фокус на след инпут 
в другом случае  удали текущий символ и оставить фокус на текущем инпуте - для кейса когда необходимо удалить символ с последнего инпута 
и для кейса когда инпуты заполнены через один, два и тд (1 _ 23 _ 45) чтобы чтобы фокус не останавливался на пустом инпуте

2022-08-31 09:48 UTC, reme3d2y commented on packages/code-input/src/component.tsx
> +                    if (values[nextIndex]) {
Сейчас много повторов в коде. Почему не так например?

```tsx
newValues[index] = "";

if (!values[nextIndex]) {
  focusOnInput(curtRef);
}

if (nextRef) {
  focusOnInput(nextRef);
}
```

2022-09-01 07:45 UTC, Valeri8888 commented on packages/code-input/src/component.tsx
> +                    } else {
Пофиксила

2022-09-01 07:45 UTC, Valeri8888 commented on packages/code-input/src/component.tsx
> +                    if (values[nextIndex]) {
Пофиксила

2022-09-08 11:14 UTC, Oladii commented on packages/code-input/src/component.tsx
> +                            compact={fields > 8}
Сейчас получается, что вне зависимости от доступной ширины под весь кодинпут мы регулируем размер самих инпутиков в зависимости от их количества. Насколько это правильно не учитывать доступную ширину под весь компонент? Кажется что если отобразаили кодинпут в большой модалке то туда и 20 инпутов влезут в большом размере без проблем :)

2022-09-09 10:39 UTC, Valeri8888 commented on packages/code-input/src/component.tsx
> +                            compact={fields > 8}
Так было и раньше, надо обсудить с ребятами как будем делать 
оставим так или будем фиксить

2022-09-12 06:03 UTC, Lacronts approved these changes

2022-09-12 10:25 UTC, SiebenSieben approved these changes

2022-09-13 08:19 UTC, reme3d2y approved these changes

2022-09-13 08:19 UTC, reme3d2y commented on packages/code-input/src/components/input/index.module.css
> +    margin-right: var(--gap-2xs);
Может сбросим правый отступ для последнего инпута?

2022-09-13 10:23 UTC, merged