feat(confirmation): added mobile version screens
core-ds/core-components pull request #233
Opened 2022-09-01 07:31 UTC by Valeri8888

пр еще в работе 
добавлены мобильные и десктопные версии экранов

2022-09-05 07:21 UTC, reme3d2y reviewed
А зачем разделять внутренние компоненты на desktop\mobile, если там единственное отличие — пропса mobile, а весь код все равно общий?

2022-09-05 07:21 UTC, reme3d2y commented on packages/confirmation/package.json
> +        "@alfalab/core-components-loader": "^3.0.1",
почему лоудер откатился?

2022-09-05 07:21 UTC, reme3d2y commented on packages/confirmation/src/components/screens/initial/desktop.module.css
> +    margin-bottom: 44px;
@Oladii норм?

2022-09-05 07:21 UTC, reme3d2y commented on packages/confirmation/src/component.desktop.tsx
> +export const ConfirmationDesktop: FC<BaseConfirmationProps> = ({ ...restProps }) => (
Зачем rest и spread тут?

2022-09-05 07:37 UTC, Valeri8888 commented on packages/confirmation/package.json
> +        "@alfalab/core-components-loader": "^3.0.1",
при фиксе конфликтов 
откатила обратно

2022-09-05 07:47 UTC, Valeri8888 commented
> А зачем разделять круглые компоненты на рабочем столе\мобильном, если там единственное отличие — свойство мобильного, а код все равно общий?

Потому что у нас есть объект, где ключ - название экрана (screen), значение - компонент для экрана
поэтому сделала разделение десктоп/мобайл

2022-09-05 08:22 UTC, Valeri8888 commented on packages/confirmation/src/component.desktop.tsx
> +export const ConfirmationDesktop: FC<BaseConfirmationProps> = ({ ...restProps }) => (
исправила

2022-09-08 12:20 UTC, Oladii commented on packages/confirmation/src/components/screens/initial/desktop.module.css
> +    margin-bottom: 44px;
вроде не должно быть таких отступов, нипанятна

2022-09-08 12:31 UTC, Oladii commented
Чуть скачет высота блоков при смене состояния, вот это хотелось бы полечить в обоихверсиях

https://user-images.githubusercontent.com/70276579/189122115-be97b787-8c2d-4e3f-9d77-104a68327a1a.mov

2022-09-08 12:34 UTC, Oladii commented
Еще непонятно, нужно ли нам как то обрабатывать такую историю, очевидно что так использовать нельзя, но нужно ли нам мешать собрать такое, если да то как
<img width="634" alt="image" src="https://user-images.githubusercontent.com/70276579/189122854-4d153cc9-2698-4319-92b8-078e8674c6cc.png">

2022-09-12 06:07 UTC, Lacronts commented on packages/confirmation/src/component.mobile.tsx
> +        {...props}
Переданный в пропсах класснейм будет перетирать класс компонента styles.container

2022-09-12 06:11 UTC, Lacronts commented on packages/confirmation/src/components/screens/initial/component.mobile.tsx
> +export const InitialMobile: FC<InitialMobileProps> = ({ inputClassName, ...restProps }) => (
inputClassName не используется. Не понятно почему так сделано

2022-09-12 06:16 UTC, Lacronts commented on packages/confirmation/src/index.ts
> +// export * from './component';
удалить закомменченую строку

2022-09-12 06:23 UTC, Lacronts commented on packages/confirmation/src/types.ts
> +    confirmationScreens?: ConfirmationScreens;
А разве должен подобный пропс быть открыт? Должны ли им пользоваться разработчики? Выглядит так, что это некое приватное свойство, о котором никто ничего знать не должен и менять его тем более

2022-09-12 10:15 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/initial/desktop.module.css
> +    margin-bottom: 44px;
исправила

2022-09-12 10:15 UTC, Valeri8888 commented
> Чуть скачет высота блоков при смене состояния, вот это хотелось бы полечить в обоих версиях
> 
>  default.mov

исправила

2022-09-12 10:40 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/initial/component.mobile.tsx
> +export const InitialMobile: FC<InitialMobileProps> = ({ inputClassName, ...restProps }) => (
исправила

2022-09-12 10:46 UTC, SiebenSieben commented
![image](https://user-images.githubusercontent.com/109410/189635090-2a492fb1-e4a2-4b16-8197-088551153055.png)

В мобильной версии не всё выравнивается по левому краю

2022-09-12 10:55 UTC, SiebenSieben commented on packages/confirmation/src/component.responsive.tsx
> +            ['desktop', '(min-width: 768px)'],
В других компонентах уже меняли на 1024, надо уточнить

2022-09-12 10:57 UTC, Valeri8888 commented on packages/confirmation/src/index.ts
> +// export * from './component';
исправила

2022-09-12 10:59 UTC, SiebenSieben commented on packages/confirmation/src/components/screens/fatal-error/component.tsx
> +    mobile?: boolean;
Не понимаю, для каких это случаев?

2022-09-12 12:05 UTC, Valeri8888 commented on packages/confirmation/src/types.ts
> +    confirmationScreens?: ConfirmationScreens;
исправила

2022-09-12 12:17 UTC, Valeri8888 commented on packages/confirmation/src/component.mobile.tsx
> +        {...props}
исправила

2022-09-13 07:50 UTC, Valeri8888 commented on packages/confirmation/src/component.responsive.tsx
> +            ['desktop', '(min-width: 768px)'],
исправила пока на 1024

2022-09-14 07:24 UTC, reme3d2y commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                        {mobile ? (
Здесь только текст отличается

2022-09-14 07:24 UTC, reme3d2y commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                            <Typography.Text
Тут тоже

2022-09-14 08:27 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                        {mobile ? (
исправила

2022-09-14 08:27 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                            <Typography.Text
исправила

2022-09-14 09:15 UTC, reme3d2y approved these changes

2022-09-15 05:33 UTC, Lacronts approved these changes

2022-09-16 10:01 UTC, Lacronts commented on .changeset/twelve-suits-flow.md
> +"@alfalab/core-components-confirmation": minor
В themes тоже есть значительные изменения.

2022-09-16 10:38 UTC, Valeri8888 commented on .changeset/twelve-suits-flow.md
> +"@alfalab/core-components-confirmation": minor
добавила

2022-09-16 11:24 UTC, DenisLipin approved these changes

2022-09-19 09:56 UTC, EGNKupava commented on packages/confirmation/src/components/header/index.module.css
> +    margin-bottom: var(--gap-xl);
А вот эта переменная же берется из глобальных переменных, Может надо добавить `@import '../../themes/src/default.css';`. Хотя тест на переменные проходит

2022-09-19 09:57 UTC, EGNKupava approved these changes

2022-09-22 09:28 UTC, Oladii approved these changes

2022-09-26 19:02 UTC, SiebenSieben requested changes

2022-09-26 19:02 UTC, SiebenSieben commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                                <>&mdash;&nbsp;для звонков по&nbsp;России</>
<img width="460" alt="image" src="https://user-images.githubusercontent.com/109410/192358164-6ec8e9e7-2408-418b-8d59-8f60538afa4e.png">

Тут прилипли тирешки

И раньше цвет текста секондари был, а сейчас праймари, всё ок?

@Oladii

2022-09-27 02:52 UTC, Valeri8888 commented on packages/themes/src/mixins/confirmation/mobile.css
> -    --confirmation-title-font-size: 18px;
исправила

2022-09-27 03:00 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/initial/index.module.css
> +    height: 80px;
исправила

2022-09-27 03:08 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                                <>&mdash;&nbsp;для звонков по&nbsp;России</>
тирешки - исправила

2022-09-27 03:31 UTC, Valeri8888 commented on packages/confirmation/src/components/header/index.module.css
> +    font-feature-settings: 'ss01';
исправила

2022-09-27 09:09 UTC, Oladii commented on packages/confirmation/src/components/screens/hint/component.tsx
> +                                <>&mdash;&nbsp;для звонков по&nbsp;России</>
вроде ок

2022-09-27 09:20 UTC, SiebenSieben commented on .changeset/twelve-suits-flow.md
> +Добавлены новые компоненты ConfirmationMobile, ConfirmationResponsive
Надо добавить, что обновлены стили для соответствия актуальным макетам

2022-09-27 09:25 UTC, SiebenSieben approved these changes

2022-09-28 05:11 UTC, Valeri8888 commented on .changeset/twelve-suits-flow.md
> +Добавлены новые компоненты ConfirmationMobile, ConfirmationResponsive
добавила

2022-09-29 09:52 UTC, merged