fix(input, form-control): change colors in intranet theme
core-ds/core-components pull request #236
Opened 2022-09-01 16:24 UTC by leetvig

2022-09-02 11:03 UTC, Lacronts commented on packages/form-control/src/default.module.css
> +    color: var(--form-control-disabled-filed-label-color);
Аналогичный изменения должны быть в inverted.module.css

2022-09-02 13:21 UTC, leetvig commented on packages/form-control/src/default.module.css
> +    color: var(--form-control-disabled-filed-label-color);
Хорошо, новым комитом заливать или старый подправить?

2022-09-02 19:42 UTC, Lacronts approved these changes

2022-09-05 07:06 UTC, reme3d2y requested changes
<img width="544" alt="image" src="https://user-images.githubusercontent.com/9968618/188385240-9983b66e-8b4f-45a8-b21b-df2072bb1a77.png">

2022-09-06 14:53 UTC, funkyscum commented
Почему-то у состояния ошибки появилась обводка
<img width="286" alt="Screenshot 2022-09-06 at 17 52 38" src="https://user-images.githubusercontent.com/111768885/188667280-dcf02919-70e0-4093-a2bf-9bb758ca37bf.png">

2022-09-08 14:48 UTC, funkyscum approved these changes

2022-09-09 13:23 UTC, funkyscum approved these changes

2022-09-12 06:55 UTC, Valeri8888 approved these changes

2022-09-12 09:46 UTC, SiebenSieben commented on packages/form-control/src/vars.css
> +    --form-control-disabled-filed-label-color: var(--form-control-disabled-color);
Опечатка filed → filled

2022-09-13 07:25 UTC, merged