chore: update ui-primitives
core-ds/core-components pull request #282
Opened 2022-09-22 12:29 UTC by Valeri8888

Обновила до последней версии ui-primitives

2022-09-23 10:01 UTC, EGNKupava reviewed
Надо посмотреть почему Hint под инпутами потерял отступ

2022-09-23 10:01 UTC, EGNKupava commented on packages/form-control/src/index.module.css
> +    @mixin paragraph_component_secondary display: block;
криво заменилось

2022-09-23 11:07 UTC, SiebenSieben commented on packages/themes/src/mixins/dark.css
> +    --color-light-bg-info-old: var(--color-dark-bg-info-old);
Забыли про это. Надо дописать скрипт, чтобы игнорировал цвета с _old в названии, это такой аналог депрекейтед, в вебе не нужны.

2022-09-26 05:21 UTC, Valeri8888 commented on packages/themes/src/mixins/dark.css
> +    --color-light-bg-info-old: var(--color-dark-bg-info-old);
дописала

2022-09-26 05:23 UTC, Valeri8888 commented on packages/input/src/index.module.css
> +    @mixin paragraph_component position: relative;
исправила

2022-09-26 05:24 UTC, Valeri8888 commented on packages/form-control/src/index.module.css
> +    @mixin paragraph_component_secondary display: block;
исправила

2022-09-26 06:35 UTC, Valeri8888 commented
> Надо посмотреть почему Hint под инпутами потерял отступ

исправила

2022-09-26 07:27 UTC, Valeri8888 commented
локально тесты проходят

2022-09-29 11:44 UTC, Valeri8888 commented
> packages/typography/src/text/**image_snapshots**/typography-text-colors-sprite-snap.png packages/typography/src/title/**image_snapshots**/typography-title-colors-sprite-snap.png
> 
> Исчезли пару скринов

пофиксили

2022-09-29 12:02 UTC, reme3d2y approved these changes

2022-09-29 12:10 UTC, EGNKupava approved these changes

2022-09-29 12:26 UTC, Oladii approved these changes

2022-09-29 19:31 UTC, SiebenSieben requested changes

2022-09-29 19:31 UTC, SiebenSieben commented on packages/themes/src/mixins/dark.css
> +    --color-light-specialbg-secondary-transparent: var(
Всё ок или эти цвета должны были добавиться и в themes/src/dark.css?

2022-09-29 19:31 UTC, SiebenSieben commented on .changeset/tall-rabbits-lie.md
> +"@alfalab/core-components-form-control": major
Кажется, тут не хватает core-components-vars и core-components-themes, а мажоркой нужно катить только vars, другие патчи

2022-09-29 19:31 UTC, SiebenSieben commented on .changeset/tall-rabbits-lie.md
> +chore: обновила ui-primitives до последней версии
→ Обновление vars из последней версии ui-primitives, удалены deprecated цвета и миксины типографики

2022-09-30 02:40 UTC, Valeri8888 commented on packages/themes/src/mixins/dark.css
> +    --color-light-specialbg-secondary-transparent: var(
автоматом только в themes/src/mixins/src/dark.css
themes/src/dark.css добавляем ручками

2022-09-30 02:43 UTC, Valeri8888 commented on packages/themes/src/mixins/dark.css
> +    --color-light-specialbg-secondary-transparent: var(
Добавила

2022-09-30 02:49 UTC, Valeri8888 commented on .changeset/tall-rabbits-lie.md
> +"@alfalab/core-components-form-control": major
добавила

2022-09-30 02:49 UTC, Valeri8888 commented on .changeset/tall-rabbits-lie.md
> +chore: обновила ui-primitives до последней версии
исправила

2022-09-30 06:10 UTC, SiebenSieben approved these changes

2022-09-30 06:36 UTC, merged