feat(pure-cell): resolves #285
core-ds/core-components pull request #288
Opened 2022-10-04 07:52 UTC by NatalyaZ

Описание в https://github.com/core-ds/core-components/issues/285

2022-10-05 05:42 UTC, Valeri8888 approved these changes

2022-10-05 06:06 UTC, SiebenSieben requested changes

2022-10-05 06:07 UTC, SiebenSieben commented
Надо проверить скрины, упали:
![pure-cell-screenshots-direction-horizontal-direction-0-diff](https://user-images.githubusercontent.com/109410/193992436-6cf7a8d5-ccb3-4a83-977f-a9ad509ebed6.png)

2022-10-05 07:39 UTC, Lacronts commented
<img width="562" alt="Снимок экрана 2022-10-05 в 14 38 48" src="https://user-images.githubusercontent.com/40845033/194006470-7b69e874-e919-4947-ad4a-4d29ce2d1f68.png">
Value и SubValue уехали за границу экрана

2022-10-05 07:43 UTC, Lacronts commented on packages/pure-cell/src/components/addon/component.tsx
> +    verticalAlign?: 'top' | 'center' | 'bottom';
Это изменение ни на что не влияет, поправлены только пропсы. Нужно доделать

2022-10-05 07:47 UTC, Lacronts commented on packages/pure-cell/src/components/category/index.module.css
> +    word-break: break-all;
Зачем тут word-break, если line-clamp == 1?

2022-10-05 07:51 UTC, Lacronts commented on packages/pure-cell/src/components/amount/component.tsx
> +    textView?: 'component' | 'primary-small';
Тут и удаление из пропсов amount тоже мажорка

2022-10-05 07:54 UTC, Lacronts commented on packages/pure-cell/src/components/amount-title/component.tsx
> +    currency,
Предлагаю через restProps передавать пропсы, чтобы ничего не забыть и чтобы код был проще

2022-10-05 07:55 UTC, Lacronts commented on packages/pure-cell/src/components/amount/component.tsx
> +    currency,
тоже через restProps

2022-10-05 07:56 UTC, Lacronts commented on packages/pure-cell/src/components/text/index.module.css
> +    word-break: break-all;
Лишнее

2022-10-06 10:10 UTC, NatalyaZ commented on packages/pure-cell/src/components/category/component.tsx
> +    rightAddon?: ReactNode;
исправила

2022-10-06 10:11 UTC, NatalyaZ commented
> <img alt="Снимок экрана 2022-10-05 в 14 38 48" width="562" src="https://user-images.githubusercontent.com/40845033/194006470-7b69e874-e919-4947-ad4a-4d29ce2d1f68.png">
> 
> Value и SubValue уехали за границу экрана

Спасибо! Исправила. Добавила кейс в тест

2022-10-06 10:11 UTC, NatalyaZ commented on packages/pure-cell/src/components/addon/component.tsx
> +    verticalAlign?: 'top' | 'center' | 'bottom';
Спасибо, что заметил. Исправила, добавила классы к компоненту

2022-10-06 10:11 UTC, NatalyaZ commented on packages/pure-cell/src/components/amount-title/component.tsx
> +    currency,
Исправила

2022-10-06 10:11 UTC, NatalyaZ commented on packages/pure-cell/src/components/amount/component.tsx
> +    currency,
Исправила

2022-10-06 10:13 UTC, NatalyaZ commented
> Надо проверить скрины, упали: ![pure-cell-screenshots-direction-horizontal-direction-0-diff](https://user-images.githubusercontent.com/109410/193992436-6cf7a8d5-ccb3-4a83-977f-a9ad509ebed6.png)

Да, картинка пододвинулась, потому что отображение минорной части было зашито в компонент AmountTitle, а блоки рисуются флексом (ширина блока уменьшилась). Обновила скриншот

2022-10-07 03:27 UTC, Lacronts commented on packages/pure-cell/src/components/amount-title/component.tsx
> +                bold='none'
bold никогда не переопределяем? Если да, тогда нужно в описании пропсов это учесть - 
& Omit<AmountType, 'bold'>

2022-10-07 03:30 UTC, Lacronts commented on updates branch
> +Merge branch 'master' of github.com:core-ds/core-components into feat/pure-cell
Этот файл удалить нужно

2022-10-07 11:22 UTC, NatalyaZ commented on updates branch
> +Merge branch 'master' of github.com:core-ds/core-components into feat/pure-cell
Удалила

2022-10-10 05:37 UTC, Lacronts commented on updates branch
> +Merge branch 'master' of github.com:core-ds/core-components into feat/pure-cell
Нет, файл остался))

2022-10-10 08:15 UTC, NatalyaZ commented on updates branch
> +Merge branch 'master' of github.com:core-ds/core-components into feat/pure-cell
Не поняла, как так вышло. Сейчас точно удалила

2022-10-10 08:56 UTC, Lacronts commented on packages/pure-cell/src/components/addon/component.tsx
> +    verticalAlign?: 'top' | 'center' | 'bottom';
Вертикальное выравнивание не работает
top - <img width="529" alt="Снимок экрана 2022-10-10 в 15 54 07" src="https://user-images.githubusercontent.com/40845033/194830449-71e9f579-dd54-408a-8cfa-1011b88c9e7e.png">

bottom - 
<img width="604" alt="Снимок экрана 2022-10-10 в 15 53 47" src="https://user-images.githubusercontent.com/40845033/194830541-c913cfa4-2771-412e-8ee9-5ad7ccd03bf5.png">

2022-10-10 14:52 UTC, NatalyaZ commented on packages/pure-cell/src/components/addon/component.tsx
> +    verticalAlign?: 'top' | 'center' | 'bottom';
Спасибо! Исправила

2022-10-11 04:30 UTC, Lacronts approved these changes

2022-10-11 04:59 UTC, Valeri8888 approved these changes

2022-10-11 05:52 UTC, SiebenSieben approved these changes

2022-10-11 09:05 UTC, Oladii approved these changes

2022-10-12 08:21 UTC, vladislavyushev approved these changes

2022-10-18 13:57 UTC, merged