fix(intl-phone-input): fix format outside value
core-ds/core-components pull request #311
Opened 2022-10-19 09:17 UTC by igorokFront

Исправлено форматирование номера в intl-phone-input, который передаётся снаружи компонента в props value

2022-10-20 03:47 UTC, Lacronts approved these changes

2022-10-20 08:27 UTC, igorokFront commented
Добавил детект флага после вставки значения извне

2022-10-31 15:01 UTC, EGNKupava commented on packages/base-modal/src/utils.ts
> +    const index = modalRestoreStyles.findIndex((s) => s.container === container);
Как-то линтер не правильно отработал. Должно было остаться без скобок. И остальные изменения тоже странные

2022-10-31 15:17 UTC, EGNKupava commented on packages/base-modal/src/utils.ts
> +    const index = modalRestoreStyles.findIndex((s) => s.container === container);
Хотя, и у меня тоже стало также...

2022-10-31 17:00 UTC, Lacronts requested changes
Откати все лишние изменения и подлей мастер ветку

2022-11-01 06:31 UTC, igorokFront commented
> Откати все лишние изменения и подлей мастер ветку

готово

2022-11-01 08:36 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
Почему ты форматируешь значение внутри компонента? Так в инпут попадает отформатированное значение, а в стейте остается неотформатированное

2022-11-01 08:39 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
На каждый рендер прилетает новое значение countries, смысла с этого useCallback тут нет. Соответственно useEffect ниже на каждый рендер вызывается

2022-11-01 09:06 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
eslint-ом бы еще пройтись по файлу

2022-11-01 12:59 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
форматирую внутри компонента, потому что тут задача уже решается внутри компонента. А если снаружи отформатировать и форматирование будет отличаться от внутреннего - будут скачки. Более того тут используется библиотека для форматирования, которая не используется в других приложениях банка. Это внутренняя задача компонента, если значение пришло не отформатированным - его нужно форматировать

2022-11-01 13:07 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
а почему прилетает новое значение countries? из-за дефолтного значения с вызовом функции? для чего это сделано?

2022-11-01 13:11 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
и как это лучше разрулить? в голову приходит только убрать тут countries из зависимостей

2022-11-01 13:46 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
Я понимаю, я о том, что так получается рассинхрон со внешним стейтом, такого быть не должно. У тебя во внешнем стейте будет номер +79991111111, а в инпуте +7 999 111-11-11. Хотя на onChange улетает отформатированный номер. Это нужно исправить - либо там и там отформатированный номер, либо всегда внутри компонента отформатированный, а во внешнем стейте нет. Сейчас рандом полный

2022-11-01 13:52 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
Убрать все useCallback и из зависимостей useEffect убрать getCountryByNumber и отключить eslint -       eslint-disable-next-line react-hooks/exhaustive-deps ))

2022-11-01 14:00 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
выглядит как мажорные изменения. Что если при получении неотформатированного значения просто вызывать onChange. Тогда и внешний и внутренний стейт будут в норме

2022-11-01 14:04 UTC, Lacronts commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
"Что если при получении неотформатированного значения просто вызывать onChange с отформатированным номером?" - вроде это сделать и нужно

2022-11-02 08:45 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +            [countries, countryIso2],
спасибо, поправил

2022-11-02 08:45 UTC, igorokFront commented on packages/intl-phone-input/src/component.tsx
> +        const formatedValue = useMemo(() => {
спасибо, сразу не сообразил. Поправил

2022-11-03 07:38 UTC, Lacronts approved these changes

2022-11-03 09:32 UTC, reme3d2y commented on packages/intl-phone-input/src/component.tsx
> +            if (value && value.length > 1 && !value.includes(' ')) {
Было бы неплохо описать эту логику в комментах

2022-11-03 09:38 UTC, reme3d2y approved these changes

2022-11-03 16:02 UTC, merged