fix(calendar-range): fix divider margin
core-ds/core-components pull request #315
Opened 2022-10-21 08:02 UTC by KoVaL0

# Опишите проблему
Divider в CalendarRange уплывает вверх при наличии label у CalendarInput

# Шаги для воспроизведения
1. Добавить label в пропсы inputFromProps и inputToProps
2. Так же указать label внешним = labelView: 'outer'

# Ожидаемое поведение
Ожидается что Divider будет находится по середине с инпутом

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый     
<img width="529" alt="Снимок экрана 2022-10-20 в 21 15 24" src="https://user-images.githubusercontent.com/56194853/197030546-7f14ad99-1281-48b5-b4df-5a0c6881c581.png">
Фактический
<img width="526" alt="Снимок экрана 2022-10-20 в 21 36 38" src="https://user-images.githubusercontent.com/56194853/197030590-a7e43b3b-ff85-445c-a437-69424ef2ab4f.png">

# Дополнительная информация
Реализация не идеальна, можно подумать над более элегантной реализацией

2022-10-27 08:15 UTC, reme3d2y requested changes

2022-10-27 08:15 UTC, reme3d2y commented on packages/calendar-range/src/views/index.module.css
> +    margin-top: 24px;
Надо подумать, как сделать так, чтобы учитывался размер инпута, иначе опять съедет

2022-10-27 08:15 UTC, reme3d2y commented on packages/calendar-range/src/views/popover.tsx
> +    const checkForLabel = () => {
Стоит вынести в хелпер

2022-11-03 07:11 UTC, SiebenSieben approved these changes

2022-11-08 05:19 UTC, SiebenSieben commented on packages/calendar-range/src/views/index.module.css
> +    margin-top: 24px;
@KoVaL0 будет возможность дотащить?

2022-11-23 05:13 UTC, reme3d2y commented
https://github.com/core-ds/core-components/pull/379

2022-11-23 05:13 UTC, closed without merging