style(intl-phone-input): замена иконок флагов на новые
core-ds/core-components pull request #364
Opened 2022-11-15 08:51 UTC by KnyazevSV

# Опишите проблему
В компоненте используются старые иконки флагов

# Шаги для воспроизведения

# Ожидаемое поведение
Новые иконки флагов

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Десктоп (если данных нет оставте блок пустым):

## Смартфон (если данных нет оставте блок пустым):

# Дополнительная информация
Отсутствуют файлы с флагами стран: 
West Sahara
guiana France
Guadeloupe
Guyana
caribbean netherlands
Cyprus
kuwait
mayotte
Malaysia
new caledonia
saint helena
reunion island
svalbard and jan mayen
sao tome and principe
st barthélemy
Saint-Martin
st pierre and miquelon
wallis and futuna
Faroe islands

Пока не разобрался как перенести папку с моками непосредственно в компонент

2022-11-17 06:57 UTC, Lacronts requested changes

2022-11-17 06:57 UTC, Lacronts commented on yarn.lock
yarn lock откатить надо

2022-11-18 08:56 UTC, SiebenSieben commented
Надо добавить ченджсет

2022-11-25 10:11 UTC, SiebenSieben commented
<img width="228" alt="image" src="https://user-images.githubusercontent.com/109410/203958096-9f4ada11-cc3a-4d3f-89ea-cb68236f40cf.png">

Плейсхолдер на 2px ниже других флагов

2022-11-30 10:27 UTC, SiebenSieben commented
Хм, всё равно чуть сдвинут, странно

![image](https://user-images.githubusercontent.com/109410/204772132-69a0aafe-4032-42c2-ab4d-bc9ed0d0030a.png)

(это ретиновый пиксель, т.е. как полпикселя)

2022-11-30 10:29 UTC, SiebenSieben approved these changes

2022-11-30 16:08 UTC, Lacronts approved these changes

2022-12-01 12:09 UTC, EGNKupava approved these changes

2022-12-01 13:14 UTC, merged