feat(input-autocomplete): added props multiple in InputAutocompleteMo…
core-ds/core-components pull request #375
Opened 2022-11-22 03:58 UTC by Valeri8888

Добавлен пропс multiple (Возможность выбрать несколько значений) в компонент InputAutocompleteMobile

2022-11-22 07:16 UTC, Lacronts commented on packages/select/src/components/base-select-mobile/Component.tsx
> +                                showFooter={showFooter ?? multiple}
Предлагаю не добавлять тут дополнительную пропсу. Можно вынести этот параметр выше рест пропсов, а в компоненте переопределить через optionsListProps.showFooter

2022-11-23 11:04 UTC, Valeri8888 commented on packages/select/src/components/base-select-mobile/Component.tsx
> +                                showFooter={showFooter ?? multiple}
fix

2022-11-28 06:44 UTC, SiebenSieben commented
В демку тоже бы добавить, сейчас там только для десктопа включается

2022-11-29 03:57 UTC, Oladii commented
И шеврончик на мобилке добавить, а то кнопка есть но не работает
<img width="808" alt="image" src="https://user-images.githubusercontent.com/70276579/204435126-e232d7c9-7556-45af-998f-026ad33e27db.png">

2022-11-30 06:42 UTC, Valeri8888 commented
> И шеврончик на мобилке добавить, а то кнопка есть но не работает <img alt="изображение" width="808" src="https://user-images.githubusercontent.com/70276579/204435126-e232d7c9-7556-45af-998f-026ad33e27db.png">

исправила

2022-11-30 06:43 UTC, Valeri8888 commented
> В демку тоже бы добавить, сейчас там только для десктопа включается

добавила

2022-11-30 10:22 UTC, SiebenSieben approved these changes

2022-11-30 15:55 UTC, Lacronts requested changes

2022-11-30 15:55 UTC, Lacronts commented on packages/input-autocomplete/src/docs/description.mdx
> -                size='m'
Надо вернуть размер m

2022-11-30 15:55 UTC, Lacronts commented on packages/input-autocomplete/src/docs/description.mdx
> -                placeholder='Начните вводить название'
Вернуть лейбл и плейсхолдер какой был

2022-11-30 15:55 UTC, Lacronts commented on packages/input-autocomplete/src/docs/description.mdx
> +                closeOnSelect={false}
closeOnSelect должен быть в true для одиночного выбора

2022-11-30 15:55 UTC, Lacronts commented
<img width="407" alt="Снимок экрана 2022-11-30 в 22 52 37" src="https://user-images.githubusercontent.com/40845033/204845809-b439e38e-5dba-407d-b217-88503dd56143.png">
При одиночном выборе добавляется запятая

2022-12-01 04:13 UTC, Valeri8888 commented on packages/input-autocomplete/src/docs/description.mdx
> -                size='m'
fix

2022-12-01 04:13 UTC, Valeri8888 commented on packages/input-autocomplete/src/docs/description.mdx
> -                placeholder='Начните вводить название'
fix

2022-12-01 04:14 UTC, Valeri8888 commented on packages/input-autocomplete/src/docs/description.mdx
> +                closeOnSelect={false}
fix

2022-12-01 04:14 UTC, Valeri8888 commented
> <img alt="Снимок экрана 2022-11-30 в 22 52 37" width="407" src="https://user-images.githubusercontent.com/40845033/204845809-b439e38e-5dba-407d-b217-88503dd56143.png">
> 
> При одиночном выборе добавляется запятая

исправила

2022-12-01 10:40 UTC, Lacronts approved these changes

2022-12-01 12:02 UTC, EGNKupava approved these changes

2022-12-09 10:26 UTC, merged