feat(icon-view): omponent update
core-ds/core-components pull request #396
Opened 2022-12-05 14:16 UTC by Valeri8888

https://jira.moscow.alfaintra.net/browse/PDS-658

2022-12-06 04:11 UTC, Lacronts commented on packages/icon-view/src/components/base-shape/component.tsx
> +    icon?: ElementType<{ width?: number; height?: number }>;
Если это фон, тогда может назвать backgroundicon?

2022-12-06 05:36 UTC, Valeri8888 commented on packages/icon-view/src/components/base-shape/component.tsx
> +    icon?: ElementType<{ width?: number; height?: number }>;
хорошо 
исправила

2022-12-06 11:35 UTC, SiebenSieben commented
Нужен ченджсет

2022-12-06 11:39 UTC, SiebenSieben commented
<img width="324" alt="image" src="https://user-images.githubusercontent.com/109410/205901986-c6b9f3d2-2a07-4df2-8ee7-5f6ed3a406c2.png">
Не отображается картинка

2022-12-06 11:40 UTC, SiebenSieben commented
<img width="421" alt="image" src="https://user-images.githubusercontent.com/109410/205902178-ef24edd8-a51f-4459-a590-b761b98451d7.png">
Разный размер у иконки Альфы и бейджа, всё ок?

2022-12-06 12:04 UTC, Valeri8888 commented
> <img alt="image" width="421" src="https://user-images.githubusercontent.com/109410/205902178-ef24edd8-a51f-4459-a590-b761b98451d7.png">
> 
> Разный размер у иконки Альфы и бейджа, всё ок?

Просто бейдж с обводкой 
@Oladii Влад, обводку убрать ?

2022-12-06 15:01 UTC, Oladii commented
> > <img alt="image" width="421" src="https://user-images.githubusercontent.com/109410/205902178-ef24edd8-a51f-4459-a590-b761b98451d7.png">
> > Разный размер у иконки Альфы и бейджа, всё ок?
> 
> Просто бейдж с обводкой @Oladii Влад, обводку убрать ?

в адоне должен быть айконвью размера 24х24 с картинкой вместо фона. А в демке похоже иконвью 20х20)
<img width="527" alt="image" src="https://user-images.githubusercontent.com/70276579/205946504-72621c9c-fd3b-4974-a19b-9cdf9efa8fe0.png">

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/70276579/205946636-fae07a13-53e4-49ee-95cc-fb0127d91dff.png">

Вот тут тоже иконвью 24х24 должен быть в аддоне
<img width="523" alt="image" src="https://user-images.githubusercontent.com/70276579/205947263-8106428f-64c6-4860-9f97-ae197e8a9b6f.png">

2022-12-06 15:42 UTC, Oladii commented
<img width="367" alt="image" src="https://user-images.githubusercontent.com/70276579/205957142-220d8ca5-caf0-4770-965f-7892cd3d57b9.png">
Бэйдж надо раскормить до 24рх в высоту

2022-12-06 15:47 UTC, Oladii commented
с иконками у бейджей-статусов что-то не так, не понимаю правда что. Их вроде не меняли, размер бейджа правильны, 24рх, но иконки как будто меньше чем должны быть.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/70276579/205958085-81c3b216-8f2f-476b-9161-037194109068.png">

2022-12-06 15:57 UTC, Oladii commented
Проверить мобильную версию, чтоб небыло горизонтального скролла.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/70276579/205960426-cd2bf215-3e92-48ca-980c-ab75689dac19.png">

2022-12-08 06:29 UTC, Valeri8888 commented
> Нужен ченджсет

добавила

2022-12-08 06:33 UTC, Valeri8888 commented
> В канвасе что-то не так с позиционированием адонов.
> 
> 48 <img alt="image" width="303" src="https://user-images.githubusercontent.com/70276579/205979494-18098df8-35f2-4adf-905a-853efdf9468f.png">
> 
> 64 <img alt="image" width="416" src="https://user-images.githubusercontent.com/70276579/205980354-db2d0f28-e4ce-4d5c-a467-5770ae34060d.png">
> 
> 80 c позиционированием ок, не хватает обводки похоже <img alt="image" width="381" src="https://user-images.githubusercontent.com/70276579/205980739-8e010a09-0ec7-4494-9a20-29ea1005ad0c.png">
> 
> 128 <img alt="image" width="580" src="https://user-images.githubusercontent.com/70276579/205981181-27c3ee89-080b-456a-856c-231b508ba77e.png">

исправила

2022-12-08 06:37 UTC, Valeri8888 commented
Все замечания по аддонам и иконкам в бейдже 
исправлены или фиксится вот этим [пр](https://github.com/core-ds/core-components/pull/397)

2022-12-12 08:27 UTC, Oladii approved these changes

2022-12-14 04:55 UTC, Lacronts requested changes

2022-12-14 04:55 UTC, Lacronts commented on package.json
> +        "@alfalab/icons-glyph": "^2.89.0",
Это точно нужно? Если да, то во всех пакетах нужно обновить

2022-12-15 04:53 UTC, Valeri8888 commented on package.json
> +        "@alfalab/icons-glyph": "^2.89.0",
обновила

2022-12-19 06:52 UTC, SiebenSieben commented
<img width="909" alt="image" src="https://user-images.githubusercontent.com/109410/208365311-cd7457ea-be16-4747-8341-2750f22d2c02.png">

На скринах пропала иконка это ок?

2022-12-19 06:55 UTC, SiebenSieben approved these changes

2022-12-19 08:38 UTC, Lacronts commented on packages/bank-card/package.json
> -        "@alfalab/icons-glyph": "^2.71.0",
Все пакеты с обновленными версиями нужно добавить в отдельный changeset

2022-12-20 05:13 UTC, Valeri8888 commented
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/109410/208365311-cd7457ea-be16-4747-8341-2750f22d2c02.png">
> 
> На скринах пропала иконка это ок?

исправила

2022-12-20 05:36 UTC, Valeri8888 commented on packages/bank-card/package.json
> -        "@alfalab/icons-glyph": "^2.71.0",
добавила

2022-12-20 07:59 UTC, Lacronts approved these changes

2022-12-20 14:09 UTC, merged