fix(slider-input): fixed hiding pips on error and hint
core-ds/core-components pull request #439
Opened 2023-01-09 08:58 UTC by Valeri8888

Исправлено скрытие pips при ошибке и подсказке

2023-01-09 09:23 UTC, Lacronts requested changes

2023-01-09 09:23 UTC, Lacronts commented on packages/slider-input/src/Component.tsx
> +                                    { [styles.hidePips]: error || hint },
Ты скрываешь тут через css, это на костыль похоже. А есть понимание почему через пропс это не работает?

2023-01-09 09:23 UTC, Lacronts commented on packages/date-time-input/src/Component.test.tsx
> +            console.log(dateAsString, 'dateAsString');
Убрать

2023-01-09 12:14 UTC, Valeri8888 commented on packages/slider-input/src/Component.tsx
> +                                    { [styles.hidePips]: error || hint },
как я поняла, метод updateOptions не отрабатывает потому что при ошибке - pips = undefined, а согласно доке pips можно скрыть предав null, но если изменить условие на "!error && !hint ? pips : null" , то ререндер происходит слишком заметно , если скрывать через css то все происходит плавнее , поэтому решила скрывать через css

2023-01-09 12:26 UTC, Valeri8888 commented on packages/date-time-input/src/Component.test.tsx
> +            console.log(dateAsString, 'dateAsString');
убрала

2023-01-10 05:31 UTC, Lacronts commented on packages/date-range-input/src/Component.test.tsx
> +            const monthTo = '0' + (dateTo.getMonth() + 1);
Откати плиз в этом ПРе фиксы тестов и подлей мастер, это неправильный фикс. Я пофиксил в мастере уже

2023-01-10 05:53 UTC, closed without merging