feat(number-input): added new component NumberInput
core-ds/core-components pull request #455
Opened 2023-01-13 08:05 UTC by Valeri8888

Добавлен новый компонент NumberInput

2023-01-13 09:55 UTC, Lacronts commented
Было бы здорово, если бы еще разделитель ставился при нажатии и на запятую и на точку.

2023-01-13 10:00 UTC, Lacronts requested changes

2023-01-13 10:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +        const [value, setValue] = useState(propValue);
С моей точки зрения компонент должен быть неконтролируемым в том случае, если не передано value снаружи. Одновременно изменять состояния внутри компонента и состояние родительского компонента считаю плохим подходом.

Т.е если передано value, то вызываем только onChange,  внутренний стейт не меняем.
@reme3d2y хочется услышать твое мнение по этому поводу, возможно я не прав:)

2023-01-13 10:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            setValue(value.replace(/[,]0+$/, '').replace(/,$/, ''));
Почему на блюр меняешь только внутренний стейт? Приложение об этих изменениях не узнает

2023-01-13 10:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const dotIndex = valueInput.indexOf(',');
Почему разделителем выбрана запятая? Никто точку не захочет? Может пропсой разделитель задавать?

2023-01-13 10:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +                inputMode='tel'
Выглядит странно, зачем это?

2023-01-13 10:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +                pattern='[+-]?[0-9]+[,][0-9]*'
Кажется так правильнее будет - '^([+-]?\d+)(\,\d*)?$'

2023-01-13 10:10 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +                inputMode='tel'
decimalне подходит?

2023-01-13 10:18 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            setValue(value.replace(/[,]0+$/, '').replace(/,$/, ''));
Когда такое вижу, то складывается мнение, что мы компоненты пишем только для сторибука:)) В демках нужно стараться описывать более реальные кейсы, преимущественно с внешним состоянием. А то иногда даже забываем onChange добавить в компонент:))

2023-01-16 04:09 UTC, Oladii commented on packages/number-input/src/Component.tsx
> +            const dotIndex = valueInput.indexOf(',');
В эмаунте у нас разделитель запятая. Но кажется тип разделителя должен быть быть пропсой. Значение этой пропсы по умолчанию запятая, но при необходимости можно будет выбрать точку. При вводе компонент должен воспринимать оба символа, и при необходимости заменять точку на запятую и наоборот в зависимости от значения пропсы. 

Пропсой предлагаю делать потому, что для разных кейсов разные разделители. Это могут быть уже тонкости до которых пользователю нет дела и он не будет знать как правильно.

2023-01-16 04:29 UTC, Oladii commented on packages/number-input/src/Component.tsx
> +            const dotIndex = valueInput.indexOf(',');
Еще кажется хорошей идеей была бы пропса на количество знаков после запятой. По дефолту не ограничиваем, но можно было бы указывать.

2023-01-17 12:04 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +                inputMode='tel'
исправила на decimal

2023-01-17 12:07 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const dotIndex = valueInput.indexOf(',');
добавила пропсу и для разделителя и для количества знаков после разделителя

2023-01-17 12:07 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            setValue(value.replace(/[,]0+$/, '').replace(/,$/, ''));
исправила

2023-01-17 12:07 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +        const [value, setValue] = useState(propValue);
исправила

2023-01-17 13:12 UTC, Lacronts commented
https://user-images.githubusercontent.com/40845033/212907521-e7bf7327-a086-4b00-9ff2-68a9f36aecca.mov
Думаю стоит просто запрещать ввод запятой, если она уже есть, а не стирать все после нее. @Oladii ты как считаешь?

2023-01-17 13:22 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +    minority?: number;
исправила

2023-01-17 13:23 UTC, Valeri8888 commented
> <img alt="Снимок экрана 2023-01-17 в 20 02 34" width="582" src="https://user-images.githubusercontent.com/40845033/212907920-4d77a21f-13b2-4e93-9a5f-e89d6ff80609.png">
> 
> Не смог точку поставить. Ну и разделитель ставится только при нажатии на запятую, на точку ничего не происходит

исправила

2023-01-17 14:27 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +                .replace(new RegExp(`\\${separator}0+$`), '')
Можно, но я бы предложил без пропсы сначала попробовать обойтись. Удалить нули в коллбэке onBlur можно будет, если потребуется

2023-01-18 06:38 UTC, Lacronts commented
> > > > Не смог точку поставить. Ну и разделитель ставится только при нажатии на запятую, на точку ничего не происходит
> > > 
> > > 
> > > исправила
> > 
> > 
> > Все еще на точку не ставится запятая и наоборот
> 
> не поняла тебя сейчас если открыть демку и выбрать запятую , то будет ставится запятая, но точку будет поставить нельзя и наоборот, если выбрать точку, то поставить запятую нельзя будет

Я о другом. Если в качестве разделителя выбрана запятая, но мы нажали на клавиатуре точку, то должна поставиться запятая. Аналогично с точкой

2023-01-19 05:41 UTC, SiebenSieben commented
Сейчас можно смещать разделитель левее, но правее не получается:
https://user-images.githubusercontent.com/109410/213364435-19911724-20cf-448a-a325-f0051609f7f2.mp4

2023-01-19 08:47 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +                .replace(new RegExp(`\\${separator}0+$`), '')
исправила

2023-01-19 08:47 UTC, Valeri8888 commented
> https://user-images.githubusercontent.com/40845033/212907521-e7bf7327-a086-4b00-9ff2-68a9f36aecca.mov Думаю стоит просто запрещать ввод запятой, если она уже есть, а не стирать все после нее. @Oladii ты как считаешь?

исправила

2023-01-19 08:48 UTC, Valeri8888 commented
> Сейчас можно смещать разделитель левее, но правее не получается:
> 
>  demo.mp4

решили запрещать ввод если разделитель уже есть

2023-01-19 08:48 UTC, Valeri8888 commented
> > > > > Не смог точку поставить. Ну и разделитель ставится только при нажатии на запятую, на точку ничего не происходит
> > > > 
> > > > 
> > > > исправила
> > > 
> > > 
> > > Все еще на точку не ставится запятая и наоборот
> > 
> > 
> > не поняла тебя сейчас если открыть демку и выбрать запятую , то будет ставится запятая, но точку будет поставить нельзя и наоборот, если выбрать точку, то поставить запятую нельзя будет
> 
> Я о другом. Если в качестве разделителя выбрана запятая, но мы нажали на клавиатуре точку, то должна поставиться запятая. Аналогично с точкой. Хочется, чтобы пользователь не думал, что там у нас выбрано в качестве разделителя

исправила

2023-01-19 17:05 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const sign = event.target.value.substring(event.target.value.length - 1) === separator;
Можно было короче event.target.value.slice(-1)

2023-01-19 17:16 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const isSignIndex = conformedValue.includes(separator);
hasSign? includes не возвращает index

2023-01-19 17:16 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const signComma = rawValue.substring(rawValue.length - 1) === '.';
Все это вычисления не нужны, если у нас нет разделителя

2023-01-19 19:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const signComma = rawValue.substring(rawValue.length - 1) === '.';
signComma, а проверяешь точку

2023-01-19 19:00 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const signDot = rawValue.substring(rawValue.length - 1) === ',';
signDot, а проверяешь запятую

2023-01-19 19:02 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +                return rawValue.replace(/\./g, ',');
Тут replace с регуляркой, ниже без. Почему так?

2023-01-19 19:08 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +            const isTwoSign = rawValue.length - conformedValue.length >= 1;
Перемененные должны объявляться как можно ближе к месту их использования. К тому же не нужно будет лишние вычисления делать

2023-01-20 08:25 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const sign = event.target.value.substring(event.target.value.length - 1) === separator;
исправила

2023-01-20 08:26 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const isSignIndex = conformedValue.includes(separator);
исправила

2023-01-20 08:26 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const signDot = rawValue.substring(rawValue.length - 1) === ',';
исправила

2023-01-20 08:26 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +                return rawValue.replace(/\./g, ',');
исправила

2023-01-20 08:26 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const isTwoSign = rawValue.length - conformedValue.length >= 1;
исправила

2023-01-20 08:26 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +            const signComma = rawValue.substring(rawValue.length - 1) === '.';
исправила

2023-01-20 08:28 UTC, Lacronts commented on packages/number-input/src/Component.tsx
> +     * Количество единицы после знака
Количество символов после разделителя

2023-01-20 08:29 UTC, Lacronts approved these changes

2023-01-20 08:38 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +     * Количество единицы после знака
исправила

2023-01-24 09:06 UTC, Oladii approved these changes

2023-01-24 15:12 UTC, SiebenSieben approved these changes

2023-01-27 08:06 UTC, reme3d2y reviewed
1. onChange и value всегда string, это ок? Компонент ведь предполагает работу с числами. Пытаюсь понять, каким образом получать из него число. Сейчас чтобы работать с дробными числами, придется держать одну переменную для строкового значения, и дополнительную, чтобы получить число. Может сделать такое же апи, как и в AmountInput?
2. Если стоит разделитель запятая и передать в value "1.5", то получим 15. Кажется, что запятую на входе лучше тоже превращать в точку

2023-01-30 13:01 UTC, Valeri8888 commented on packages/number-input/src/Component.tsx
> +                if (rawValue.length !== conformedValue.length && fractionLength) {
исправила

2023-01-31 08:40 UTC, reme3d2y commented
@Valeri8888 сейчас можно начать ввод с разделителя, `,123`. При блюре ничего не меняется

2023-01-31 09:32 UTC, Valeri8888 commented
> @Valeri8888 сейчас можно начать ввод с разделителя, `,123`. Нужно или запретить, или подставлять 0

исправила, выбрала вариант запретить

2023-02-01 09:04 UTC, reme3d2y approved these changes

2023-02-01 09:12 UTC, merged