feat(typography): added new props rowLimit
core-ds/core-components pull request #469
Opened 2023-01-19 11:42 UTC by Valeri8888

Добавлен новый пропс rowLimit отвечающий за ограничение максимального количества строк

2023-01-24 04:34 UTC, Lacronts requested changes

2023-01-24 04:34 UTC, Lacronts commented on packages/typography/src/text/index.module.css
> +.rowLimit1 {
Заиспользовать миксин row_limit

2023-01-24 07:19 UTC, Valeri8888 commented on packages/typography/src/text/index.module.css
> +.rowLimit1 {
исправила

2023-01-24 15:51 UTC, Lacronts commented
Есть ощущение, что с миксином сейчас некорректные переносы. Кажется, что word-break: break-all нужен только для rowLimit1, в остальных случаях лучше без него. Кажется стоит его выпилить:) Нужно посмотреть только как переносы работают в Plate и Pure-cell, там как раз этот миксин используется

2023-01-25 04:28 UTC, Lacronts commented
<img width="703" alt="Снимок экрана 2023-01-25 в 11 27 47" src="https://user-images.githubusercontent.com/40845033/214479992-69db6071-93e1-41f3-8f68-362ed688aaec.png">
В Plate оже не корректные переносы, нужно удалять этот word-break

2023-01-26 15:33 UTC, SiebenSieben commented on packages/vars/src/typography.css
> -    word-break: break-all;
Почему убираем?

2023-01-26 15:44 UTC, Valeri8888 commented on packages/vars/src/typography.css
> -    word-break: break-all;
потому что переносит слова некорректно 
<img width="724" alt="Снимок экрана 2023-01-26 в 18 43 17" src="https://user-images.githubusercontent.com/87258678/214880986-f08ee613-734f-412b-aade-f0ac2dc112f6.png">

2023-01-26 15:45 UTC, Valeri8888 commented on packages/vars/src/typography.css
> -    word-break: break-all;
так же в компоненте PureCell происходит

2023-01-27 04:45 UTC, SiebenSieben commented on packages/vars/src/typography.css
> -    word-break: break-all;
Добавили его по просьбе Наташи Зайцевой

С ним обрезается лучше, занимая всю ширину

Может попробовать другие значения word-break? Обсудите с Наташей

2023-01-27 08:13 UTC, Lacronts commented on packages/vars/src/typography.css
> -    word-break: break-all;
ИМХО его убирать надо, лучше человеческие переносы, чем ровное обрезание:))

2023-01-27 08:16 UTC, Valeri8888 commented on packages/vars/src/typography.css
> -    word-break: break-all;
я списалась с Наташей, она просит оставить его для лимита в одну строку 
предлагаю убрать из миксина, а для rowLimit1 просто добавить

2023-01-30 05:39 UTC, SiebenSieben approved these changes

2023-01-30 09:18 UTC, Lacronts approved these changes

2023-01-30 10:12 UTC, Oladii approved these changes

2023-01-30 11:52 UTC, merged