fix: fixed themes mobile and intranet in FormControl, Select, Calenda…
core-ds/core-components pull request #473
Opened 2023-01-20 11:46 UTC by Valeri8888

Исправлены темы mobile и intranet в  компонентах FormControl, Select, CalendarInput

2023-01-23 08:59 UTC, Oladii approved these changes

2023-01-26 16:09 UTC, Lacronts approved these changes

2023-01-26 16:11 UTC, Lacronts requested changes

2023-01-26 16:11 UTC, Lacronts commented on .changeset/stupid-crabs-leave.md
> +"@alfalab/core-components-calendar-input": minor
Думаю стоит оставить только themes, в остальных компонентах код не изменен

2023-01-26 16:11 UTC, Lacronts commented on .changeset/stupid-crabs-leave.md
> +"@alfalab/core-components-calendar-input": minor
Ну и это больше на фикс похоже, так что patch

2023-01-27 04:42 UTC, SiebenSieben approved these changes

2023-01-27 06:27 UTC, Valeri8888 commented on .changeset/stupid-crabs-leave.md
> +"@alfalab/core-components-calendar-input": minor
исправила

2023-01-27 07:33 UTC, Lacronts approved these changes

2023-01-27 07:34 UTC, merged