feat(date-range-input): added new props onClose
core-ds/core-components pull request #490
Opened 2023-01-30 14:03 UTC by Valeri8888

Добавлен новый пропс onClose - обработчик закрытия календаря в мобильной версии

2023-01-30 14:30 UTC, Lacronts requested changes

2023-01-30 14:30 UTC, Lacronts commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +    onClose?: () => void;
Через conditional props не получится?

```ts
type ConditionalProps = {picker: true; onClose?:() => void;} | {picker?: false; onClose?: never}

export type DateRangeInputProps = ConditionalProps & ...
```

2023-01-30 14:30 UTC, Lacronts commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +     * Обработчик закрытия календаря в мобильной версии
Неверное описание. Календарь и в десктопной используется

2023-01-31 05:27 UTC, Valeri8888 commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +     * Обработчик закрытия календаря в мобильной версии
исправила

2023-01-31 05:27 UTC, Valeri8888 commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +    onClose?: () => void;
исправила

2023-01-31 08:23 UTC, Lacronts approved these changes

2023-01-31 08:24 UTC, Valeri8888 commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +    onClose?: () => void;
исправила

2023-01-31 08:24 UTC, Valeri8888 commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +     * Обработчик закрытия календаря в мобильной версии
исправила

2023-02-08 10:47 UTC, Lacronts requested changes

2023-02-08 12:07 UTC, Valeri8888 commented on packages/date-range-input/src/components/date-range-input/Component.tsx
> +type ConditionalProps =
исправила

2023-02-09 05:03 UTC, Lacronts approved these changes

2023-02-14 08:20 UTC, reme3d2y commented
Тут конфликты появились

2023-02-14 08:20 UTC, reme3d2y approved these changes

2023-02-14 10:07 UTC, merged