feat(tag): added new props shape and view
core-ds/core-components pull request #498
Opened 2023-02-02 07:58 UTC by Valeri8888

Добавлены props shape и view отвечающие за форму и стиль тега

2023-02-03 05:40 UTC, Lacronts requested changes

2023-02-03 05:40 UTC, Lacronts commented on packages/filter-tag/src/Component.tsx
> +                    styles[shape],
Кажется shape должен иметь приоритет над variantClassName. Сейчас же одновременно можно и rounded и rectangular класс получить

2023-02-03 05:40 UTC, Lacronts commented on packages/filter-tag/src/Component.tsx
> +                    styles[shape],
Надо подумать как это разрулить. 
ИМХО надо сделать так -> если передали prop shape, то variant должен игнорироваться

2023-02-08 07:08 UTC, Valeri8888 commented on packages/filter-tag/src/Component.tsx
> +                    styles[shape],
исправила

2023-02-09 05:09 UTC, Lacronts approved these changes

2023-02-10 10:04 UTC, Oladii approved these changes

2023-02-14 08:19 UTC, reme3d2y approved these changes

2023-02-14 08:22 UTC, merged