feat(underlay-wrapper): added new component UnderlayWrapper
core-ds/core-components pull request #511
Opened 2023-02-07 11:24 UTC by Valeri8888

Добавлен новый компонент UnderlayWrapper

2023-02-08 06:18 UTC, Lacronts requested changes

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/types.ts
> +export const BORDER_COLOR = [
Это не относится к типам, лучше вынести в consts

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/types.ts
> +export type PaddingType = 0 | 2 | 4 | 8 | 12 | 16 | 20 | 24 | 32 | 40 | 48;
Лучше использовать названия переменных наших, посмотри как сделано в genericWrapper, предлагаю также

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +            style={{
Предлагаю убрать вообще этот объект и сделать пресечение типа пропсов с  React.HTMLAttribures<HtmlDivElement>. Пусть разрабы делают со style что хотят

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +            handleClick(event);
Это зачем?
Опять же, все обработчики можно убрать, если расширить тип пропов нативными аттрибутами

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +            role='button'
Почему подложка стала кнопкой?

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/border.module.css
> +.link {
Через цикл можно сделать, примеры можно посмотреть в generic-wrapper и gap

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/shadow.module.css
> +.shadow-xs {
Тоже через @each

2023-02-08 06:18 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +    height?: number | string;
Зачем эти свойства, если можно через класс это задать?

2023-02-10 06:30 UTC, Valeri8888 commented on packages/underlay-wrapper/src/types.ts
> +export const BORDER_COLOR = [
исправила

2023-02-10 06:30 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +            style={{
исправила

2023-02-10 06:30 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +            handleClick(event);
исправила

2023-02-10 06:31 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +            role='button'
исправила

2023-02-10 06:31 UTC, Valeri8888 commented on packages/underlay-wrapper/src/border.module.css
> +.link {
исправила

2023-02-10 06:31 UTC, Valeri8888 commented on packages/underlay-wrapper/src/shadow.module.css
> +.shadow-xs {
исправила

2023-02-10 06:31 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +    height?: number | string;
исправила

2023-02-10 06:31 UTC, Valeri8888 commented on packages/underlay-wrapper/src/types.ts
> +export type PaddingType = 0 | 2 | 4 | 8 | 12 | 16 | 20 | 24 | 32 | 40 | 48;
исправила

2023-02-10 06:37 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +    borderSize?: 1 | 2 | 4 | 'none';
чем none отличается от undefined?

2023-02-10 06:47 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +    borderSize?: 1 | 2 | 4 | 'none';
работает аналогично

2023-02-10 06:57 UTC, Oladii commented
обсудить еще раз имя, андерлей или андерлей враппер.

2023-02-10 07:54 UTC, Lacronts commented on packages/underlay-wrapper/src/Component.tsx
> +    borderSize?: 1 | 2 | 4 | 'none';
Тогда зачем none?

2023-02-10 07:56 UTC, Valeri8888 commented on packages/underlay-wrapper/src/Component.tsx
> +    borderSize?: 1 | 2 | 4 | 'none';
у влада в макете было, поэтому добавила 
исправлю в след фикс

2023-02-13 07:29 UTC, Valeri8888 commented
> обсудить еще раз имя, андерлей или андерлей враппер.

решили что будет андерлей

2023-02-13 08:44 UTC, Oladii approved these changes

2023-02-13 10:40 UTC, Lacronts approved these changes

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/Component.tsx
> +import { BackgroundColorType, BorderColorType, ShadowType, PaddingPropType } from './types';
Может это вынести вообще куда-то в общие типы?

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/Component.tsx
> +    padding?: PaddingPropType;
Остальные типы называются "SomethingType", а тут "SomethingPropType". Почему так?

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/Component.tsx
> +    borderRadius?: 'm' | 'xl' | 'xxl';
Может это тоже вынести в BorderRadiusType?

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/Component.tsx
> +
Может сразу реф добавить, тем более что он кликабельный может быть

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/Component.tsx
> +    const paddingStyles = padding && {
Не хотим сделать padding="m", чтобы для всех сторон применился?
@Oladii или это не частый кейс?

2023-02-14 08:27 UTC, reme3d2y commented on packages/underlay/src/consts.ts
> +export const BACKGROUND = [
Кажется этому место в пакете vars, а не тут

2023-02-15 06:38 UTC, SiebenSieben commented on packages/underlay/src/docs/Component.stories.mdx
> +            borderSize={borderSize}
В демке не работает

2023-02-15 06:39 UTC, SiebenSieben commented on packages/underlay/src/index.module.css
> +    }
Можешь сбилдить посмотреть сколько будет весить css компонента? Интересно)

2023-02-15 06:40 UTC, SiebenSieben approved these changes

2023-02-15 07:55 UTC, Valeri8888 commented on packages/underlay/src/Component.tsx
> +    borderRadius?: 'm' | 'xl' | 'xxl';
исправила

2023-02-15 07:55 UTC, Valeri8888 commented on packages/underlay/src/Component.tsx
> +    const paddingStyles = padding && {
исправила

2023-02-15 07:56 UTC, Valeri8888 commented on packages/underlay/src/consts.ts
> +export const BACKGROUND = [
исправила

2023-02-15 07:56 UTC, Valeri8888 commented on packages/underlay/src/Component.tsx
> +
исправила

2023-02-15 07:56 UTC, Valeri8888 commented on packages/underlay/src/Component.tsx
> +    padding?: PaddingPropType;
исправила

2023-02-15 07:56 UTC, Valeri8888 commented on packages/underlay/src/Component.tsx
> +import { BackgroundColorType, BorderColorType, ShadowType, PaddingPropType } from './types';
исправила

2023-02-15 15:34 UTC, reme3d2y approved these changes

2023-02-16 06:11 UTC, merged