fix(number-input): updated NumberInput
core-ds/core-components pull request #517
Opened 2023-02-08 09:46 UTC by Valeri8888

2023-02-08 10:08 UTC, Lacronts requested changes

2023-02-08 10:08 UTC, Lacronts commented on packages/number-input/src/Component.test.tsx
> +            expect(inputNumber.value).toBe('');
Тут что-то не то. Ввели +123б а получили ''? Надо разобраться

2023-02-08 10:08 UTC, Lacronts commented on packages/number-input/src/utils.ts
> +import { SEPARATORS } from './Component';
Плохая практика. У тебя A импортирует B и B импортирует A. Давай в константы вынесем SEPARATORS и SIGNS

2023-02-08 12:51 UTC, Valeri8888 commented on packages/number-input/src/utils.ts
> +import { SEPARATORS } from './Component';
давай может в utils вынесем 
я посмотрела по либе много где так

2023-02-08 14:15 UTC, Valeri8888 commented on packages/number-input/src/utils.ts
> +import { SEPARATORS } from './Component';
перенесла в utils

2023-02-08 14:15 UTC, Valeri8888 commented on packages/number-input/src/Component.test.tsx
> +            expect(inputNumber.value).toBe('');
исправила

2023-02-09 07:03 UTC, Lacronts approved these changes

2023-02-14 05:11 UTC, SiebenSieben approved these changes

2023-02-14 07:35 UTC, Oladii approved these changes

2023-02-14 07:39 UTC, merged