feat(segmented-control): add component
core-ds/core-components pull request #528
Opened 2023-02-12 13:28 UTC by AlexZJScript

Добавление компонента SegmentedControl

2023-02-13 05:04 UTC, SiebenSieben commented
Changeset

2023-02-13 12:15 UTC, Lacronts commented on packages/segmented-control/src/Component.tsx
> +        handler.current = onChange;
Не понял чего ты этим добился. Замемоизировал контекст? А смысл?

2023-02-13 12:34 UTC, Lacronts requested changes

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/Component.tsx
> +    }, [selectedId, children]);
children всегда новые будут, этот useMemo никогда не будет работать

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/Component.tsx
> +    }, [children, selectedId]);
Тоже самое, из-за children useEffect будет на каждый рендер срабатывать

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/Component.tsx
> +            <div className={cn(contentClassName)}>{content}</div>
content && <div.... Контента ведь может и не быть

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/index.module.css
> +    height: 40px;
Заюзать переменную --size-xs-height

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/index.module.css
> +    height: 32px;
Заюзать переменную --size-xxs-height

2023-02-13 12:34 UTC, Lacronts commented on packages/segmented-control/src/docs/description.mdx
> +Контрол может содержать от двух до пяти сегментов.
А если 6 указать?))

2023-02-15 06:44 UTC, SiebenSieben commented on packages/segmented-control/package.json
> +    "version": "1.0.0",
0.0.0

2023-02-15 06:46 UTC, SiebenSieben commented on packages/segmented-control/src/Component.tsx
> +    view?: 'rounded' | 'rect';
Сейчас у Tag есть shape (rounded/rectangular), может тут сделаем аналогично?

2023-02-15 07:10 UTC, Lacronts commented
Тесты нужно добавить

2023-02-15 07:10 UTC, Lacronts requested changes

2023-02-15 07:10 UTC, Lacronts commented on packages/segmented-control/src/docs/description.mdx
> +Контрол может содержать от двух до пяти сегментов.
Должно ли быть ограничение или нет? Если нет, то не ясно зачем в описании так написано

2023-02-17 09:40 UTC, Lacronts approved these changes

2023-02-17 09:40 UTC, Lacronts commented
Скриншоты бы еще)

2023-02-17 11:53 UTC, Oladii commented on packages/segmented-control/src/docs/description.mdx
> +Контрол может содержать от двух до пяти сегментов.
должно быть ограничение, если нужно больше вариантов, то нужно искать другой компонент. Не принято использовать эту штуку с больше чем пятью сегментами, да и 5 уже почти криминал))

2023-02-17 11:56 UTC, Oladii commented
На всю ширину тянем только в мобильной демке
<img width="816" alt="image" src="https://user-images.githubusercontent.com/70276579/219647533-082dc52d-0c4b-4a7e-a57c-32b1b1d9152c.png">

2023-02-17 14:11 UTC, AlexZJScript commented
> На всю ширину тянем только в мобильной демке <img alt="image" width="816" src="https://user-images.githubusercontent.com/70276579/219647533-082dc52d-0c4b-4a7e-a57c-32b1b1d9152c.png">

fixed

2023-02-17 14:11 UTC, AlexZJScript commented
> На всю ширину тянем только в мобильной демке <img alt="image" width="816" src="https://user-images.githubusercontent.com/70276579/219647533-082dc52d-0c4b-4a7e-a57c-32b1b1d9152c.png">

fixed

2023-02-20 09:10 UTC, Oladii approved these changes

2023-02-28 09:26 UTC, merged