feat/magnetic-bottom-sheet
core-ds/core-components pull request #538
Opened 2023-02-15 13:10 UTC by stovv

# Опишите проблему
1. Нет возможности выбора высоты в которой будет задерживаться bottom-sheet при закрытии/открытии
2. Нет возможности задать изначальную высоту bottom-sheet
3. Оверлей перехватывает все mouse эвенты, что не позволяет кликать по элементам на странице под bottom-sheet
4. Нет возможности скрыть скроллбар внутри bottom-sheet при помощи параметра

# Ожидаемое поведение
1. При заданных областях `magneticAreas` `bottom-sheet` должен
  1. Задерживаться(притягиваться) при свайпе вниз к самой ближайшему значению
  2. Отмагничиваться если свайп был наверх и дальность до самой верхней точки больше magneticThreshold
  3. При свайпе в самый низ, притягиваться к самой нижней точке
  4. Запустить коллбек `onMagnetic` индексом из массива `magneticAreas`
2. Если `visibleHeight` меняется, то должна меняться видимая высота `bottom-sheet` относительно высоты окна
3. Если `transparentBackdropClick` - истина, клик/ховер и любые другие действия на странице (которые ниже по `z-index` чем `bottom-sheet` и эго контейнер) не должны быть заблокированны
4.  Параметры `magneticAreas`, `magneticThreshold` можно задать в 3 форматах: `пиксели(string) - 10px`, `число(number) - 10, `процент(string) - 10%`

# Чек лист
- [x] Тесты
- [x] Документация

# Тестовый стенд

## Десктоп:
 - OS: MacOS
 - Browser: Safari
 - Version: 16.3

 - OS: MacOS
 - Browser: Chrome
 - Version: 100.0.4896.75

## Смартфон:
 - Device: iPhone 14 Pro
 - OS: iOS 16.3
 - Browser: Safari
 - Version: 16

# Дополнительная информация
Дополнительная информация

2023-02-15 13:15 UTC, stovv commented on packages/bottom-sheet/src/docs/description.mdx
> +        fixedContent: 'yes',
Тут была русская C

2023-02-15 13:18 UTC, stovv commented on package.json
> +        "react-swipeable": "^6.2.2",
С этой версии добавлен коллбек SheetSwipeStart и пофикшены проблемы с подсчетом deltaY

2023-02-15 14:26 UTC, SiebenSieben commented
Добавь changeset, пожалуйста

2023-02-16 04:58 UTC, Lacronts requested changes

2023-02-16 04:58 UTC, Lacronts commented on packages/base-modal/src/Component.tsx
> +                                            ...(backdropProps?.style ?? {})
?? {} лишнее, {...undefined} ничего не ломает

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/package.json
> -        "tslib": "^2.4.0"
Не понятно что тут произошло, нужно вернуть как было

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/package.json
> +        "react-swipeable": "^6.2.2",
Почему не последняя версия? Кажется если обновлять, то на последнюю, или там проблемы есть?

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/src/component.tsx
> +            if (['Left', 'Right'].includes(direction) || !sheetContainer?.current?.getBoundingClientRect()?.y){
1) current всегда есть в sheetContainer - лишняя проверка на undefined.
2) не нужно два раза вызывать sheetContainer.current.getBoundingClientRect(), лучше обойтись одним вызовом)

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/src/component.tsx
> +            setTimeout(handleChangeVisibleHeight, 1);
1 можно не указывать, там минимум 4мс

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/src/component.tsx
> +                        pointerEvents: transparentBackdropClick ? 'none': 'all'
Вместо transparentBackdropClick может hideOverlay использовать? 
Логично, что если нет оверлея, то должны работать клики

2023-02-16 04:58 UTC, Lacronts commented on packages/bottom-sheet/src/component.tsx
> +                            pointerEvents: 'all'
В css-класс добавить?

2023-02-16 06:39 UTC, Lacronts commented on packages/bottom-sheet/src/docs/description.mdx
> +        fixedContent: 'yes',
Недоисправлял тут, fixedContent не работает в демке

2023-02-16 06:46 UTC, Lacronts commented
Если кликать по бэкдропу с приоткрытой шторкой, то она не закрывается. Также после того как она приоткрыта, ее можно тащить вврех, при чем анимации нет, можно вытащить на сколько захотелось, это странно. Разве так должно быть?
[Screencast from 2023-02-16 13-45-26.webm](https://user-images.githubusercontent.com/40845033/219289019-cd677af3-3e9a-4b62-891f-2983b5fff01b.webm)

2023-02-16 06:57 UTC, Lacronts commented
С магнитными областями при клике на бэкдроп шторка пытается закрыться и пропадает бэкдроп + проблемы с анимацией

https://user-images.githubusercontent.com/40845033/219291065-52781a4a-0a1f-48cf-9cc1-59414c7f015d.mp4

2023-02-20 09:21 UTC, Lacronts commented
Скрыть скроллбар не работает

2023-02-21 04:56 UTC, Lacronts commented
С тестами нужно разобраться

2023-02-21 06:34 UTC, Oladii commented
В магнитном режиме непрозрачность оверлея зависит от степени открытия шторки, это не ок. Потому что теряется весь профит от отсутствия оверлея на промежуточных значениях открытия шторки. Давай попробуем вот так:

  Если шторка открыта на весь экран (100%+уже заложенный минимальный отступ до верха), то под ней всегда должен быть дефолтный оверлей. Без исключений.

Если шторка открыта не на всю высоту, под ней может быть, а может и не быть оверлея, за это отвечает пропса [hide overlay]. 

Соответственно, для растягиваемой шторки, у которой отключен оверлей поведение должно быть таким: 
Пока мы не тянем её в последней области (между  X% и 100%), оверлея нет, а в последней области он плавно появляется. 

Пример: изначально открываем штору на 25% без оверлея. Есть магнитные точки в 50% и 100%. Когда тянем между 25 и 50 оверлея всё еще нет, когда тянем между 50 и 100 он плавно появляется. 

Еще разик) Если в изначальном положении оверлей выключен, то он должен плавно появляться только если шторку можно растянуть на весь экран, и он плавно появляется только в пределах последнего промежутка, причем не важно, будь это промежуток от 10% до 100% или от 90% до 100%. Важно что он включает в себя максимальное значение 100% и ближайшую к нему магнитную точку. Если максимальное открытие нашей шторы не 100%, а 99%, то оверлей так и не появится.

2023-02-21 06:39 UTC, Oladii commented
(мобильная сафаря)
1. В демке, когда выбираю изначально заданную высоту в 50% внутри шторы не работает скролл.
2. В демке, когда выбираю изначально заданную высоту в 50% и возможность закрытия свайпом, почему то могу еще и открыть штору на 100% тоже свайпом, почему?

2023-02-21 06:40 UTC, Oladii commented
"Параметры magneticAreas, magneticThreshold можно задать в 3 форматах: пиксели(string) - 10px, число(number) - 10, процент(string) - 10%"

Надо оставить только один способ задавать высоту в пикселях, либо явно указывать px, либо не указывать px. Не должно быть двух способов сделать одно и тоже.

2023-02-21 06:49 UTC, Oladii commented
К самой механики свайпа тоже есть пожелание, сейчас нужно дотащить шапку до нужной половины зоны. То есть если у меня по умолчанию модалка открыта на 50% и есть возможность растянуть ее на 100% то я должен донести шапку до 76% чтобы ботомщит понял что я хочу растянуть его полностью. Думаю что движения на 40px должно быть достаточно чтобы обозначить желание перейти к следующей доступной магнитной точке. 

Пример. Штору можно свернуть полностью, изначально она открыта на 50% и ее можно растянуть на весь экран. 

Если я потяну ее на 40рх вверх она откроется на весь экран, если на 40рх вниз, то закроется.

2023-02-21 19:44 UTC, stovv commented
@Lacronts тесты bottom-sheet пофиксил, нужно ли остальные (не относящиеся к изменениям ) фиксить?)

2023-02-21 19:48 UTC, stovv commented
> (мобильная сафаря)
> 
> 1. В демке, когда выбираю изначально заданную высоту в 50% внутри шторы не работает скролл.
> 2. В демке, когда выбираю изначально заданную высоту в 50% и возможность закрытия свайпом, почему то могу еще и открыть штору на 100% тоже свайпом, почему?

@Oladii 
1. Да, скролл локается, так-как если скролл будет работать то при вытягивании шторы из изначального положения есть вероятность промахнуться и штора не поднимется, а отработает скролл внутри шторы ( могу как вариант добавить аргумент чтоб была возможность отключить лок скролла )
2. Изначальная высота - это высота на которую открыта штора, в изначальной идее она не должна мешать полному раскрытию шторы и закрытию ( могу добавить аргумент чтоб была возможность заблокировать открытие шторы выше значения, которое задал, тогда эта механика отработает)

2023-02-22 04:52 UTC, Lacronts commented
> @Lacronts тесты bottom-sheet пофиксил, нужно ли остальные (не относящиеся к изменениям ) фиксить?)

Нужно, так как они относятся к изменениям.

2023-02-27 09:19 UTC, Oladii commented
@stovv, да, добавь плз обе пропсы по обоим вопросам:)

2023-04-13 05:47 UTC, SiebenSieben commented
Реализовано в https://github.com/core-ds/core-components/pull/615

2023-04-13 05:47 UTC, closed without merging