feat(list): update component List
core-ds/core-components pull request #542
Opened 2023-02-17 10:09 UTC by Valeri8888

update component List

2023-02-21 04:53 UTC, Lacronts requested changes

2023-02-21 04:53 UTC, Lacronts commented on packages/list/src/Component.tsx
> +// eslint-disable-next-line @typescript-eslint/no-redeclare
Может тип просто по-другому назвать? TListContext?

2023-02-21 04:53 UTC, Lacronts commented on packages/list/src/Component.tsx
> +                <ListContext.Provider value={ComponentProviderValue}>
Давай один провайдер сделаем, зачем каждый элемент оборачивать?

2023-02-21 04:53 UTC, Lacronts commented on packages/list/src/components/item/index.module.css
> +    --list-marker-color: var(--color-light-text-primary);
А эти переменные точно нужны? тут инвертед темы нет, темизации тоже

2023-02-21 04:53 UTC, Lacronts commented on packages/list/src/Component.tsx
> +                    <ListContext.Provider value={ComponentProviderValue}>
А тут не получится для каждого ребенка проверять на isListItem?

2023-02-21 06:44 UTC, Valeri8888 commented on packages/list/src/components/item/index.module.css
> +    --list-marker-color: var(--color-light-text-primary);
не стала убирать потому что кто-то их может использовать

2023-02-21 06:50 UTC, Valeri8888 commented on packages/list/src/components/item/index.module.css
> +    --list-marker-color: var(--color-light-text-primary);
в битбакете нашла пару  файлов где их переопределяли 
с другой стороны у нас будет пропса кт можно назначить цвет маркера 
но кажется лучше оставить, предупредить что со след фиксом их выпилим чтобы никому ничего не сломать

2023-02-21 07:19 UTC, Valeri8888 commented on packages/list/src/Component.tsx
> +                    <ListContext.Provider value={ComponentProviderValue}>
скорее всего нет 
да и зачем? 
решили же что List можно использовать либо с ListItem либо без него

2023-02-21 07:54 UTC, Valeri8888 commented on packages/list/src/Component.tsx
> +                <ListContext.Provider value={ComponentProviderValue}>
исправила

2023-02-21 07:54 UTC, Valeri8888 commented on packages/list/src/Component.tsx
> +// eslint-disable-next-line @typescript-eslint/no-redeclare
исправила

2023-02-21 08:45 UTC, Lacronts commented on packages/list/src/components/item/index.module.css
> +    --list-marker-color: var(--color-light-text-primary);
Проблемы нужно решать по мере их поступления. Так что лучше сейчас их выпилить

2023-02-22 04:55 UTC, Lacronts commented on packages/list/src/Component.test.tsx
> +                <List.ListItem>List</List.ListItem>
Может просто Item назвать сабкомпонент, а то List.ListItem выглядит не очень

2023-02-22 07:23 UTC, Valeri8888 commented on packages/list/src/Component.test.tsx
> +                <List.ListItem>List</List.ListItem>
давай

2023-02-22 16:42 UTC, Lacronts approved these changes

2023-03-02 07:49 UTC, SiebenSieben commented
Тут бы дизайн-ревью от click/corp? @Oladii

2023-03-02 08:06 UTC, SiebenSieben commented on packages/list/src/index.module.css
> -    --list-item-margin: var(--gap-s);
Мажорка?

2023-03-02 08:22 UTC, SiebenSieben commented
Может нам добавить пример когда в List прокидывается Typography, а не List.Item?

2023-03-02 08:23 UTC, SiebenSieben approved these changes

2023-03-02 13:11 UTC, Oladii commented
Про тайпографи сделали коммент на странице "разработчику"

2023-03-03 05:23 UTC, Oladii approved these changes

2023-03-03 06:16 UTC, SiebenSieben commented on packages/list/src/Component.tsx
> +        styles.ui,
Что значит ui?

2023-03-03 06:25 UTC, Lacronts commented on packages/list/src/utils.ts
> +};
Исправь плиз eslint warnings

2023-03-03 06:30 UTC, Lacronts requested changes

2023-03-03 06:30 UTC, Lacronts commented on packages/list/src/utils.ts
> +    return item;
export const isItem = (child: ReactNode) =>  (isValidElement(child) && isItemElement(child, 'ListItem'));

2023-03-03 07:45 UTC, Valeri8888 commented on packages/list/src/utils.ts
> +    return item;
исправила

2023-03-03 07:45 UTC, Valeri8888 commented on packages/list/src/utils.ts
> +};
исправила

2023-03-03 07:45 UTC, Valeri8888 commented on packages/list/src/Component.tsx
> +        styles.ui,
исправила

2023-03-03 08:46 UTC, reme3d2y approved these changes

2023-03-03 09:29 UTC, Lacronts approved these changes

2023-03-03 10:18 UTC, merged