fix(button): fix dark theme button loader color
core-ds/core-components pull request #543
Opened 2023-02-20 10:47 UTC by hiraeth0

# Опишите проблему
Лоадер в компоненте Button типа primary в темных темах mobile, click, intranet сливался с белым цветом самой кнопки.

# Внешний вид

Было:
<img width="776" alt="Screenshot 2023-02-20 at 12 20 36" src="https://user-images.githubusercontent.com/56126128/220084007-f3c8099d-2efb-4391-a9ad-4a08fbf07cf5.png">

Стало:
<img width="264" alt="Screenshot 2023-02-20 at 14 39 54" src="https://user-images.githubusercontent.com/56126128/220084038-d48c16bf-62c0-4698-af49-fc6fded049da.png">

2023-02-21 04:25 UTC, Lacronts approved these changes

2023-02-21 04:31 UTC, Lacronts requested changes

2023-02-21 04:31 UTC, Lacronts commented on packages/themes/src/mixins/button/click.css
> +    --button-spinner-static-color: var(--color-light-graphic-primary-inverted);
<img width="1016" alt="Снимок экрана 2023-02-21 в 11 30 17" src="https://user-images.githubusercontent.com/40845033/220248220-0126e667-ea53-4a33-b3b6-760231d2ccaf.png">

Кажется тут белый должен быть спиннер
@Oladii

2023-02-22 05:29 UTC, Oladii commented on packages/themes/src/mixins/button/click.css
> +    --button-spinner-static-color: var(--color-light-graphic-primary-inverted);
Цвет спиннера должен совпадать с цветом текста. Да, в красной белый должен быть. Давайте и его починим)

2023-02-22 07:05 UTC, hiraeth0 commented on packages/themes/src/mixins/button/click.css
> +    --button-spinner-static-color: var(--color-light-graphic-primary-inverted);
<img width="749" alt="Screenshot 2023-02-21 at 15 35 21" src="https://user-images.githubusercontent.com/56126128/220547466-efd7c5b4-0206-4197-929f-b5e95a90dc6c.png">
Поправил

2023-02-22 09:27 UTC, Lacronts approved these changes

2023-02-22 10:48 UTC, Oladii approved these changes

2023-02-28 08:34 UTC, Valeri8888 approved these changes

2023-02-28 09:54 UTC, merged