feat(tag): добавление механики переполнения
core-ds/core-components pull request #558
Opened 2023-02-27 09:06 UTC by KnyazevSV

# Опишите проблему
Данные приходят с бэка, мы ими не управляем, приходят длиннющие юр имена 
Если такие имена приходят с пробелами, тег на 2 строчки расползается с выравниванием по центру. Выглядит плохо, но не ломает по крайней мере ничего
Но есть кейсы, где вместо пробелов нижнее подчеркивание, в таких кейсах тег растягивает сайд-панель и у нее появляется горизонтальный скролл

# Шаги для воспроизведения
Добавить максимальную ширину, например style={{maxWidth:'200px'}}
Добиться ширины children более максимального

# Ожидаемое поведение
Обрезается текст и при наведении показывается тултип

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Десктоп (если данных нет оставте блок пустым):

## Смартфон (если данных нет оставте блок пустым):

# Дополнительная информация

2023-03-10 06:56 UTC, Lacronts requested changes

2023-03-10 06:56 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
onOverflow - эта функция, чтобы этот эффект не срабатывал на каждый рендер она должна быть обернута снаружи в useCallback, с абсолютной уверенностью могу сказать, что в 99% этого не будет сделано. 

Предлагаю не затягивать это в коры, это можно сделать где-угодно, нужно просто дать доступ к рефам снаружи. 

Ожидаемое поведение - "Обрезается текст и при наведении показывается тултип"  - текст можно обрезать с помощью overflow: ellipsis, tooltip можно показывать с помощью аттрибута title. Этот вариан не подходит?

2023-03-10 07:31 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Так-как мы управляем обёрткой мы можем гарантировать что onOverflow будет обёрнут в useCallback, можно чтобы не грузить коры просто передавать в этот колбек рефы и вынести эту логику в обёртку, так норм будет?

2023-03-10 08:02 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
А почему вы на своей стороне это сделать не можете?

2023-03-10 08:04 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Вариант с title рассматривали?

2023-03-10 08:14 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
title нативный имеется ввиду? В референсе TooltipResponsive

2023-03-10 09:17 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
А почему тогда всегда нельзя всегда показывать тултип при наведении?

2023-03-10 09:45 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Если пользователь видит полностью текст зачем нужен тултип с этим же текстом?

2023-03-10 10:13 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Да ничего страшного в этом нет, это повсюду юзается. В общем я против подобной логики в корах
![Screenshot from 2023-03-10 17-12-12](https://user-images.githubusercontent.com/40845033/224289202-c8973e29-e6b4-472b-8922-4728c16550cd.png)

2023-03-10 10:27 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Ок, обсужу с дизайнерами

2023-03-13 06:04 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +            const handlerAndNodesExist = onOverflow && tagRef.current && tagRef.current;
Тут кажется ошибка, два раза tagRef.current.

И зачем тут onOverflow сейчас, не понимаю как это должно работать...

2023-03-13 13:39 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +            const handlerAndNodesExist = onOverflow && tagRef.current && tagRef.current;
Исправил

2023-03-13 13:41 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +        }, [onOverflow]);
Дизайнеры ответили что не нужно показывать тултип если тэг не переполнен

2023-03-14 08:17 UTC, Lacronts commented on packages/tag/src/Component.tsx
> +    nodesTransfer?: (tag: HTMLButtonElement, children: HTMLSpanElement) => void;
Зачем коллбэк? Доступ к рефам же извне есть(ну или добавить можно)

```
useLayoutEffect(() => {
  //...magic with refs
})

Так можем сделать?

<Tag ref={tagRef} contentRef={contentRef}/>
```

2023-03-22 07:03 UTC, Lacronts commented on .changeset/thin-carrots-pretend.md
> +Добавлена возможность обработки ситуации превышения ширины children
Изменить нужно changeset

2023-03-22 08:00 UTC, KnyazevSV commented on .changeset/thin-carrots-pretend.md
> +Добавлена возможность обработки ситуации превышения ширины children
Исправил

2023-03-22 09:27 UTC, Lacronts approved these changes

2023-03-22 15:36 UTC, reme3d2y commented on packages/tag/src/index.module.css
> +    white-space: nowrap;
Мы уверены, что хотим по дефолту такое поведение?

@Oladii

2023-03-23 05:29 UTC, KnyazevSV commented on packages/tag/src/Component.tsx
> +    childrenRef?: React.RefObject<HTMLSpanElement>;
Готово

2023-03-23 06:01 UTC, Oladii commented on packages/tag/src/index.module.css
> +    white-space: nowrap;
хм) если это свойство, то оно поидее должно быть описано на вкладке "разработчику", я не нашел описания и не понимаю что именно оно делает. В канвасе тоже нет такой пропсы, поэтому посмотреть как она что-то делает тоже не могу)

По поводу дефолтного состояния, реквест не должен его менять, если мы добавляем новое свойство то по дефолту оно должно быть отключено.

2023-03-23 06:34 UTC, Oladii commented on packages/tag/src/index.module.css
> +    white-space: nowrap;
Обсудили, вроде всё хорошо:)

2023-03-23 06:34 UTC, Oladii approved these changes

2023-03-23 09:09 UTC, reme3d2y approved these changes

2023-03-24 06:35 UTC, merged