feat(themes): change css variables for corp buttons
core-ds/core-components pull request #561
Opened 2023-02-27 18:28 UTC by CrybabyDanChan

2023-02-28 08:22 UTC, Lacronts commented on .changeset/dirty-carrots-deny.md
> +'@alfalab/core-components-themes': major
@SiebenSieben мажоркой это будем катить?

2023-03-01 05:39 UTC, Lacronts requested changes

2023-03-01 05:39 UTC, Lacronts commented on packages/themes/src/mixins/button/corp.css
> +    --button-primary-base-bg-color: var(--color-light-bg-accent);
![Screenshot from 2023-03-01 12-38-34](https://user-images.githubusercontent.com/40845033/222054482-37c8b768-1b29-4f49-a28a-3e3be2aff04e.png)
Нужно удалить отсюда переменные, которые дублируют переменные из default.css в кнопке

2023-03-01 08:44 UTC, OlegMeo approved these changes

2023-03-03 05:45 UTC, SiebenSieben commented on .changeset/dirty-carrots-deny.md
> +'@alfalab/core-components-themes': major
@CrybabyDanChan минорка тут норм ведь?

2023-03-03 05:45 UTC, SiebenSieben approved these changes

2023-03-03 07:20 UTC, Lacronts approved these changes

2023-03-03 07:43 UTC, reme3d2y approved these changes

2023-03-03 07:44 UTC, reme3d2y commented on packages/themes/src/mixins/button/corp.css
> -    --button-active-transform: none;
Только primary касается?

2023-03-03 09:48 UTC, CrybabyDanChan commented on .changeset/dirty-carrots-deny.md
> +'@alfalab/core-components-themes': major
норм, поменял)

2023-03-03 10:40 UTC, merged