feat(slider): added new props valueTo and behaviour
core-ds/core-components pull request #607
Opened 2023-03-28 07:05 UTC by churicheva-v

Добавлены новые пропс valueTo - второе значение диапазона  и behaviour - поведение ползунка

2023-03-28 09:31 UTC, Lacronts requested changes

2023-03-28 09:31 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +                    if (Number(newValueFrom) <= Number(newValueTo) || behaviour === 'tap') {
Давай вычисление числа в константу вынесем
```tsx
const sliderValues = slider.get() as string[];
const from = Number(sliderValues[0]);
const to = Number(sliderValues[1]);
```

2023-03-28 09:31 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +                        onChange({ value: Number(newValueTo), valueTo: Number(newValueFrom) });
А такое вообще должно происходить? что from > to?

2023-03-28 09:31 UTC, Lacronts commented on packages/slider/src/docs/description.mdx
> +С помощью слайдера можно указывать диапазон значений. Свойство `behaviour` определяет поведение ползунка.
Хотелось бы больше подробностей про behaviour. Абсолютно не понятно, что за поведение оно меняет

2023-03-28 09:36 UTC, Lacronts requested changes

2023-03-28 09:36 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +                    if (Number(newValueFrom) <= Number(newValueTo) || behaviour === 'tap') {
Ну и кажется, что || behaviour === 'tap' тут лишнее

2023-03-29 09:51 UTC, Valeri8888 commented on packages/slider/src/Component.tsx
> +                    if (Number(newValueFrom) <= Number(newValueTo) || behaviour === 'tap') {
исправила

2023-03-29 18:16 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +    }, [onChange, valueTo]);
Давай избавимся от valueTo в зависимостях, useEffect фактически смысл теряет тут

2023-03-31 06:51 UTC, reme3d2y commented on packages/slider/src/Component.tsx
> +    }, [onChange, valueTo]);
Если необходимо, то ты можешь завести bool переменную valueTo === undefined и добавить в зависимости уже ее

2023-03-31 07:41 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +    }, [onChange, valueTo]);
:)))
![Screenshot from 2023-03-31 14-41-28](https://user-images.githubusercontent.com/40845033/229056156-49673ec8-22ee-457b-908b-a46036f02c33.png)

2023-04-03 06:30 UTC, Valeri8888 commented on packages/slider/src/Component.tsx
> +    }, [onChange, valueTo]);
исправила

2023-04-03 06:35 UTC, Lacronts commented on packages/slider/src/Component.tsx
> +    const hasValueTo = valueTo === undefined;
Знак неверный. !== же должен быть

2023-04-03 06:56 UTC, Valeri8888 commented on packages/slider/src/Component.tsx
> +    const hasValueTo = valueTo === undefined;
нет, знак верный 
а вот название переменной надо изменить

2023-04-03 07:04 UTC, Valeri8888 commented on packages/slider/src/Component.tsx
> +    const hasValueTo = valueTo === undefined;
исправила имя переменной

2023-04-03 09:48 UTC, Lacronts approved these changes

2023-04-06 09:04 UTC, reme3d2y commented on packages/slider/src/Component.tsx
> +     * Значение инпута
тут бы дописать, иначе совпадает с value

2023-04-06 09:04 UTC, reme3d2y commented on packages/slider/src/Component.tsx
> +    const hasNotValueTo = valueTo === undefined;
не очень нравится название

2023-04-06 09:04 UTC, reme3d2y approved these changes

2023-04-06 12:03 UTC, Valeri8888 commented on packages/slider/src/Component.tsx
> +     * Значение инпута
исправила

2023-04-12 10:51 UTC, Oladii approved these changes

2023-04-12 15:34 UTC, SiebenSieben approved these changes

2023-04-13 08:58 UTC, merged