feat(textarea): updated textarea
core-ds/core-components pull request #613
Opened 2023-04-04 10:40 UTC by Valeri8888

https://jira.moscow.alfaintra.net/browse/PDS-546

2023-04-05 12:21 UTC, Lacronts requested changes

2023-04-05 12:21 UTC, Lacronts commented on packages/textarea/src/Component.tsx
> +                [styles.filled]: nativeScrollbar && filled,
Почему тут nativeScrollbar появился? Это ошибка?

2023-04-05 12:21 UTC, Lacronts commented on packages/textarea/src/__image_snapshots__/textarea-dark-preview-snap.png
Кажется что value слишком близко к Label стало. @Oladii

2023-04-05 12:21 UTC, Lacronts commented on packages/textarea/src/index.module.css
> +.scrollable {
Что то не то тут, я выпиливал эти стили, их быть не должно. Сейчас нет в компоненте класса scrollable

2023-04-05 12:21 UTC, Lacronts commented on packages/textarea/src/index.module.css
> +.scrollableWithLabel.filled {
Тоже нет

2023-04-06 12:55 UTC, Valeri8888 commented on packages/textarea/src/Component.tsx
> +                [styles.filled]: nativeScrollbar && filled,
ветвилась от старого мастера , потом влили пр с откатом , и после мержа обновленного мастера некоторый код перезатерся (
исправила

2023-04-06 12:55 UTC, Valeri8888 commented on packages/textarea/src/index.module.css
> +.scrollable {
исправила

2023-04-10 06:24 UTC, Lacronts approved these changes

2023-04-12 15:42 UTC, SiebenSieben commented on packages/textarea/src/index.module.css
> +    --textarea-xl-border: 24px;
Для чего выносить всё это в переменные? Может зашьём без переменных? Но если всё же выносить, то не хотим ли как-то иначе назвать? Свойство border, да, но по сути это хак вместо отступа, может что-то типа spacer?

2023-04-17 04:04 UTC, Oladii approved these changes

2023-04-18 07:43 UTC, Valeri8888 commented on packages/textarea/src/index.module.css
> +    --textarea-xl-border: 24px;
переменные нужны, тк они переиспользуются дальше по коду , если просто зашить, будет сложновато понять где править что при фиксах, а так изменил в одном месте и ок 
поэтому думаю для нашего удобства лучше оставить 
переименовала на spacer + добавила комент для чего нужен этот хак

2023-04-18 10:02 UTC, merged