feat(action-button): new component action-button
core-ds/core-components pull request #62
Opened 2022-05-30 08:16 UTC by blackraydev

Новый компонент Action Button

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.screenshots.test.tsx
> +            customSnapshotIdentifier: (...args) => `hover-${customSnapshotIdentifier(...args)}`,
```suggestion
            customSnapshotIdentifier: (...args) => `pressed-${customSnapshotIdentifier(...args)}`,
```

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +    size?: 's';
Будут еще размеры?

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +    href?: AnchorHTMLAttributes<HTMLAnchorElement>['href'];
там не просто string?

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +    colors?: 'default' | 'inverted' | 'static';
Кажется, что пора это выносить в отдельный тип

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +export const ActionButton = forwardRef<HTMLAnchorElement | HTMLButtonElement, ActionButtonProps>(
Мы очень сильно наелись потом с этим типом HTMLAnchorElement | HTMLButtonElement. Проверь плз, может получится заюзать без проблем просто HTMLElement или сделать дженерик 

@Lacronts у тебя был опыт с подобным?

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +        const showLoader = useMemo(() => loading || !loaderTimePassed, [loading, loaderTimePassed]);
Кажется, что можно это вынести в отдельный хук. Как минимум TODO'шку  можно поставить в коде

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/index.module.css
> +    &.disabled {
Лучше стили писать без лишних вложенностей, иначе бывает сложно потом переопределять по классу что-то

2022-06-07 01:26 UTC, reme3d2y commented on packages/action-button/src/index.module.css
> +    -webkit-line-clamp: 2;
IE? или не страшно?

2022-07-28 13:58 UTC, Oladii approved these changes

2022-08-01 08:46 UTC, reme3d2y requested changes
Давайте обсудим. Я посмотрел внимательнее — тут очень много копипасты из обычной кнопки, а по факту это она и есть. Надо сделать по-другому

2022-08-01 08:46 UTC, reme3d2y commented on packages/action-button/src/hooks.ts
> +export const useLoader = (loading: boolean, timeout: number) => {
Это ведь еще где-то точно есть. Надо вынести в utils

2022-08-01 08:46 UTC, reme3d2y commented on packages/action-button/src/Component.tsx
> +                <Circle
@CrybabyDanChan @Oladii 
Блин, а чет туплю, но зачем нам тут вообще Circle?

2022-08-03 17:45 UTC, CrybabyDanChan commented on packages/action-button/src/hooks.ts
> +export const useLoader = (loading: boolean, timeout: number) => {
в utils выносить в самой папке для данного компонента или utils в папке packages, или есть еще место для общих хуков в проекте?

2022-08-03 17:46 UTC, CrybabyDanChan commented on packages/action-button/src/Component.tsx
> +                <Circle
убрал, выяснили что аддоны c icon-view в спеке не используются

2022-08-05 08:40 UTC, CrybabyDanChan commented on packages/action-button/src/Component.tsx
> +export const ActionButton = forwardRef<HTMLAnchorElement | HTMLButtonElement, ActionButtonProps>(
Проверил HTMLElement, если вешать реф, то он будет ругаться конечно на те свойства, которые есть HTMLAnchorElement или в HTMLButtonElement, а какие проблемы вcтречались?

2022-08-05 09:24 UTC, reme3d2y commented on packages/action-button/src/hooks.ts
> +export const useLoader = (loading: boolean, timeout: number) => {
Да меня вообще смущает, что тут 90% это копипаста Button. Надо с этим что-то придумать

2022-08-05 09:50 UTC, reme3d2y approved these changes

2022-08-19 10:19 UTC, SiebenSieben commented on packages/action-button/src/index.module.css
> +    -webkit-box-orient: vertical;
Мы можем писать line-clamp/box-orient? Есть ведь autoprefixer для этого

2022-08-19 10:23 UTC, SiebenSieben commented
<img width="90" alt="image" src="https://user-images.githubusercontent.com/109410/185598797-3270c248-6b21-4243-a581-ef9dea7a9572.png">

Loader чуть левее центра, надо выровнять)

2022-08-22 07:48 UTC, SiebenSieben approved these changes

2022-08-22 09:44 UTC, Lacronts commented on packages/action-button/package.json
> +{
Нужно обновить package.json файл, он должен быть как в других пакетах.
1) удалить "files": ["dist"]
2) обновить команду postinstall
3) изменить main
4) добавить module
5) в publishConfig добавить directories
6) в peerDependenciesдобавить 18 реакт
7) Поставить актуальную версию @alfalab/core-components-loader

2022-08-22 09:48 UTC, Lacronts commented on packages/action-button/src/hooks.ts
> +            window.clearTimeout(timerId.current);
Очищать таймаут нужно в первом useEffect, а не на unmount

2022-08-22 09:50 UTC, Lacronts commented on packages/action-button/src/hooks.ts
> +    const showLoader = useMemo(() => loading || !loaderTimePassed, [loading, loaderTimePassed]);
Это не нужно мемоизировать

2022-08-22 09:53 UTC, Lacronts requested changes

2022-08-22 09:53 UTC, Lacronts commented on packages/action-button/src/hooks.ts
> +            window.clearTimeout(timerId.current);
Очищать таймаут нужно в первом useEffect, а не на unmount

2022-08-23 09:43 UTC, CrybabyDanChan commented on packages/action-button/src/hooks.ts
> +            window.clearTimeout(timerId.current);
Пофиксил

2022-08-24 09:52 UTC, Lacronts commented on packages/action-button/src/hooks.ts
> +            window.clearTimeout(timerId.current);
А ты проверял, сейчас это вообще работает? мне кажется, что нет))
Сейчас у тебя будет очищаться таймаут и соответственно функция никогда не выполнится, если изменится значение флага loading.

Сори, но кажется раньше все же было правильно сделано))
Я бы сделал так - 

`
  useEffect(() => {
        if (loading) {
            setLoaderTimePassed(false);

            if (timerId.current) {
                window.clearTimeout(timerId.current);
            }

            timerId.current = window.setTimeout(() => {
                setLoaderTimePassed(true);
            }, timeout);
        }
    }, [loading, timeout]);

  useEffect(() => {
    if (timerId.current) {
       window.clearTimeout(timerId.current);
    }
  }, [])
`

2022-08-29 05:26 UTC, Lacronts approved these changes

2022-09-09 06:06 UTC, merged