feat(link): implemented new view & updated styles
core-ds/core-components pull request #66
Opened 2022-06-01 03:50 UTC by blackraydev

Новая вьюшка у Link

2022-06-01 08:08 UTC, EGNKupava approved these changes

2022-06-07 01:28 UTC, reme3d2y approved these changes

2022-06-07 01:28 UTC, reme3d2y commented on packages/link/src/Component.tsx
> +     * @default true
у нас где-то есть jsdoc, а где-то нет. Надо определиться

2022-06-07 01:28 UTC, reme3d2y commented on packages/link/src/docs/Component.stories.mdx
> +import { StarSIcon } from '@alfalab/icons-glyph/StarSIcon';
она юзается?

2022-06-07 12:12 UTC, blackraydev commented on packages/link/src/docs/Component.stories.mdx
> +import { StarSIcon } from '@alfalab/icons-glyph/StarSIcon';
да, там ниже он используется

2022-06-10 09:07 UTC, EGNKupava commented
Посмотреть чего падают Скриншоты и обновить.

2022-07-26 11:21 UTC, Valeri8888 approved these changes

2022-07-29 09:10 UTC, Oladii commented
Над поправить в демке контейнер для маленькой иконки. С 18 до 16
<img width="590" alt="image" src="https://user-images.githubusercontent.com/70276579/181726122-39bfb53d-17e5-4839-ba51-6686106d2ddb.png">

2022-07-29 09:23 UTC, Oladii requested changes
Обновить иконку и или контейнер под иконку с 18 до 16

2022-08-03 15:00 UTC, Oladii approved these changes

2022-08-19 08:29 UTC, SiebenSieben commented on packages/link/src/index.module.css
> +    align-items: center;
А это ведь только для флексов имеет смысл, почему не ниже где withAddons?

2022-08-19 08:29 UTC, SiebenSieben approved these changes

2022-08-25 11:44 UTC, merged