feat(button): added mobile and responsive versions component
core-ds/core-components pull request #687
Opened 2023-05-26 05:58 UTC by Valeri8888

добавлены мобильная и адаптивная версии компонента

2023-05-26 10:01 UTC, Lacronts commented on packages/button/src/Component.responsive.tsx
> +>(({ children, breakpoint = 1024, defaultMatchMediaValue, ...restProps }, ref) => {
defaultMatchMediaValue в случае с кнопками не нужен

2023-05-26 10:07 UTC, Lacronts commented on packages/button/src/default.mobile.module.css
> +.accent {
Сейчас в двух файлах стили почти 1 в 1. Никак от этого не уйти?

2023-05-30 08:37 UTC, Valeri8888 commented on packages/button/src/default.mobile.module.css
> +.accent {
сделала через пропсу

2023-06-21 08:45 UTC, Oladii approved these changes

2023-06-22 10:08 UTC, Lacronts requested changes

2023-06-22 10:08 UTC, Lacronts commented on packages/picker-button/src/Component.mobile.tsx
> +            idMobile: true,
Лишнее?

2023-06-22 10:08 UTC, Lacronts commented on packages/themes/src/mixins/button/click.css
> +@define-mixin button-click {
Это нужно, чтобы для клика обе версии кнопки выглядили одинаково?

2023-06-22 10:08 UTC, Lacronts commented on tools/storybook/findComponentPath.js
> +        const mdxStory = glob.sync(
Откатить нужно и подлить мастер

2023-06-23 08:46 UTC, Valeri8888 commented on tools/storybook/findComponentPath.js
> +        const mdxStory = glob.sync(
фикс

2023-06-23 08:46 UTC, Valeri8888 commented on packages/themes/src/mixins/button/click.css
> +@define-mixin button-click {
да

2023-06-23 08:46 UTC, Valeri8888 commented on packages/picker-button/src/Component.mobile.tsx
> +            idMobile: true,
фикс

2023-06-23 08:46 UTC, Valeri8888 commented on packages/confirmation/src/components/screens/fatal-error/component.tsx
> +    const breakpoint = mobile ? breakpointProps : 1;
фикс

2023-06-23 08:46 UTC, Valeri8888 commented on packages/button/src/components/base-button/Component.tsx
> +                'cc-button',
хорошо

2023-06-23 08:47 UTC, Valeri8888 commented on jest.screenshots.config.js
> +        '@alfalab/core-components-(.*)/(.*)$': '<rootDir>/packages/$1/src/$2',
фикс

2023-07-14 08:26 UTC, SiebenSieben commented on packages/custom-button/src/component.screenshots.test.tsx
> +        'paddingRight:98px;transform:scale(2.3)',
Интересно почему приходится так смещать, может нужно origin указать

2023-07-14 08:29 UTC, SiebenSieben commented
Предлагаю добавить скриншот-тестов

2023-07-14 09:21 UTC, SiebenSieben commented on packages/picker-button/src/Component.tsx
> +            breakpoint: 1,
Что значит единичка?

2023-07-14 09:32 UTC, SiebenSieben commented on packages/system-message/src/__image_snapshots__/system-message-mobile-column-footer-snap.png
Интересно почему в мобильных сайдпанелях увеличиваем кнопки, а тут нет

2023-07-17 04:14 UTC, Lacronts approved these changes

2023-07-17 06:45 UTC, reme3d2y approved these changes

2023-07-17 08:33 UTC, Valeri8888 commented on packages/picker-button/src/Component.tsx
> +            breakpoint: 1,
breakpoint: 1 превратит респонсив кнопку в десктоп

2023-07-17 13:27 UTC, Valeri8888 commented on packages/system-message/src/__image_snapshots__/system-message-mobile-column-footer-snap.png
исправила

2023-07-17 13:27 UTC, Valeri8888 commented on packages/custom-button/src/component.screenshots.test.tsx
> +        'paddingRight:98px;transform:scale(2.3)',
исправила

2023-07-17 13:27 UTC, Valeri8888 commented
> Предлагаю добавить скриншот-тестов

добавила

2023-08-03 04:58 UTC, SiebenSieben commented
Заметил опечатку, которая не относится к этому реквесту:
<img width="540" alt="image" src="https://github.com/core-ds/core-components/assets/109410/46bdffbb-d2ee-40aa-a1da-dadf9262bce0">

2023-08-03 04:59 UTC, SiebenSieben commented on packages/picker-button/src/Component.tsx
> +            breakpoint: 1,
А почему единичка? Расскажи чуть подробнее на дейлике, пожалуйста

2023-08-03 05:15 UTC, SiebenSieben approved these changes

2023-08-04 06:29 UTC, Valeri8888 commented
> Заметил опечатку, которая не относится к этому реквесту: <img alt="image" width="540" src="https://user-images.githubusercontent.com/109410/258004231-46bdffbb-d2ee-40aa-a1da-dadf9262bce0.png">

фикс

2023-08-07 07:56 UTC, merged