feat(tag): added mobile and responsive versions component
core-ds/core-components pull request #700
Opened 2023-06-02 06:40 UTC by Valeri8888

2023-06-02 08:25 UTC, Lacronts commented on packages/pagination/src/components/tag/index.tsx
> +} from '@alfalab/core-components-tag/desktop';
Не понимаю почему тут десктопная версия

2023-06-02 08:26 UTC, Lacronts commented on packages/radio-group/src/Component.test.tsx
> +import { TagDesktop as Tag } from '../../tag/src/desktop';
И тут

2023-06-02 08:29 UTC, Lacronts commented on packages/tag/src/default.module.css
> +        &.hover:hover:not(:disabled) {
Может через media query это сделать?
```
@media(hover: hover) {

}
```

2023-06-02 08:32 UTC, Lacronts commented on packages/tag/src/docs/development.mdx
> +import { TagResponsive } from '@alfalab/core-components/tag/responsive';
Responsive быть не должно, он в индексе лежит. И responsive.ts тоже

2023-06-02 08:34 UTC, Lacronts commented on packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
> +              class="component component s outlined rounded hover borderRadius my-tag"
Откуда взялся borderRadius и зачем он нужен?

2023-06-08 07:12 UTC, Valeri8888 commented on packages/pagination/src/components/tag/index.tsx
> +} from '@alfalab/core-components-tag/desktop';
pagination переопределяются стили тега, поэтому думаю нет смысла тащить респонсив версию

2023-06-08 07:13 UTC, Valeri8888 commented on packages/radio-group/src/Component.test.tsx
> +import { TagDesktop as Tag } from '../../tag/src/desktop';
исправила

2023-06-08 07:13 UTC, Valeri8888 commented on packages/tag/src/default.module.css
> +        &.hover:hover:not(:disabled) {
исправила

2023-06-08 07:13 UTC, Valeri8888 commented on packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
> +              class="component component s outlined rounded hover borderRadius my-tag"
исправила

2023-06-08 07:13 UTC, Valeri8888 commented on packages/tag/src/docs/development.mdx
> +import { TagResponsive } from '@alfalab/core-components/tag/responsive';
исправила

2023-06-13 06:24 UTC, Valeri8888 commented on packages/tabs/src/components/tabs/Component.test.tsx
> +                dataTestId: 'KKK',
исправлю

2023-06-22 10:10 UTC, Lacronts commented on jest.screenshots.config.js
> +        '@alfalab/core-components-(.*)/(.*)$': '<rootDir>/packages/$1/src/$2',
Лишнее

2023-06-22 10:18 UTC, Lacronts requested changes

2023-06-22 10:18 UTC, Lacronts commented on packages/filter-tag/src/__image_snapshots__/filter-tag-main-props-click-snap.png
Почему тут цвет разный?

2023-06-22 10:18 UTC, Lacronts commented on packages/tabs/src/components/secondary-tablist/Component.desktop.tsx
> +    'tagSize' | 'isMobile' | 'breakpoint'
isMobile тут кажется лишний. Ну и везде в ПРе

2023-06-22 10:18 UTC, Lacronts commented on tools/storybook/findComponentPath.js
> -        const files = glob.sync(
откатить

2023-06-23 06:53 UTC, Valeri8888 commented on jest.screenshots.config.js
> +        '@alfalab/core-components-(.*)/(.*)$': '<rootDir>/packages/$1/src/$2',
фикс

2023-06-23 06:56 UTC, Valeri8888 commented on packages/tabs/src/components/secondary-tablist/Component.desktop.tsx
> +    'tagSize' | 'isMobile' | 'breakpoint'
фикс

2023-06-23 06:56 UTC, Valeri8888 commented on tools/storybook/findComponentPath.js
> -        const files = glob.sync(
откатила

2023-06-23 06:57 UTC, Valeri8888 commented on packages/filter-tag/src/__image_snapshots__/filter-tag-main-props-click-snap.png
починили view outlined

2023-07-17 04:58 UTC, Lacronts approved these changes

2023-07-17 06:45 UTC, reme3d2y approved these changes

2023-08-07 04:40 UTC, SiebenSieben commented on packages/tabs/src/__image_snapshots__/click-tabs-tabs-desktop-view-1-size-1-2-snap.png
На многих скринах теги с заливкой стали с обводкой. Почему так происходит?

2023-08-07 04:44 UTC, SiebenSieben commented on packages/tabs/src/__image_snapshots__/click-tabs-tabs-desktop-view-1-size-1-2-snap.png
Можем добавить кодмод?

2023-08-07 04:46 UTC, SiebenSieben commented on packages/tabs/src/__image_snapshots__/click-tabs-tabs-desktop-view-1-size-1-2-snap.png
И выглядит как будто не всё в ченджлоге написали

2023-08-07 08:33 UTC, merged