feat(input): added mobile and responsive versions component
core-ds/core-components pull request #716
Opened 2023-06-14 07:44 UTC by Valeri8888

2023-06-22 10:28 UTC, Lacronts requested changes

2023-06-22 10:28 UTC, Lacronts commented on jest.screenshots.config.js
> +        '@alfalab/core-components-(.*)/(.*)$': '<rootDir>/packages/$1/src/$2',
откатить

2023-06-22 10:28 UTC, Lacronts commented on packages/amount-input/src/Component.tsx
> +            breakpoint=1024,
что-то не то с форматированием

2023-06-22 10:28 UTC, Lacronts commented on packages/date-range-input/src/Component.mobile.tsx
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Лишний коммент выходит. Он тут был не просто та. Надо проверить типы в сборке

2023-06-22 10:28 UTC, Lacronts commented on packages/form-control/src/Component.responsive.tsx
> +        const getDefaultValue = () => (isClient() ? window.matchMedia(query).matches : false);
Тут это не нужно, лучше убрать

Вот так оставить - 
const [isDesktop] = useMatchMedia(query, defaultMatchMediaValue);

2023-06-22 10:28 UTC, Lacronts commented on packages/input/src/Component.responsive.tsx
> +        const getDefaultValue = () => (isClient() ? window.matchMedia(query).matches : false);
Аналогично

2023-06-22 10:28 UTC, Lacronts commented on tools/storybook/findComponentPath.js
> +        const mdxStory = glob.sync(
откатить

2023-06-22 14:25 UTC, Valeri8888 commented on packages/form-control/src/Component.responsive.tsx
> +        const getDefaultValue = () => (isClient() ? window.matchMedia(query).matches : false);
без getDefaultValue тесты ведут себя странно , по типу не проходят снапшоты или обрезаются пробелы 
<img width="1164" alt="Снимок экрана 2023-06-22 в 17 21 08" src="https://github.com/core-ds/core-components/assets/8725
<img width="750" alt="Снимок экрана 2023-06-22 в 17 21 33" src="https://github.com/core-ds/core-components/assets/87258678/02edf553-ef62-4d8a-9de9-64293b639d22">
8678/d20949d2-ee86-4398-94e3-8aab0d602faa">

2023-06-22 14:26 UTC, Valeri8888 commented on packages/form-control/src/Component.responsive.tsx
> +        const getDefaultValue = () => (isClient() ? window.matchMedia(query).matches : false);
![Uploading Снимок экрана 2023-06-22 в 17.21.33.png…]()

2023-06-22 14:31 UTC, Valeri8888 commented on jest.screenshots.config.js
> +        '@alfalab/core-components-(.*)/(.*)$': '<rootDir>/packages/$1/src/$2',
откатила

2023-06-22 14:31 UTC, Valeri8888 commented on packages/amount-input/src/Component.tsx
> +            breakpoint=1024,
исправила

2023-06-22 14:32 UTC, Valeri8888 commented on tools/storybook/findComponentPath.js
> +        const mdxStory = glob.sync(
откатила

2023-06-23 06:23 UTC, Lacronts commented on packages/form-control/src/Component.responsive.tsx
> +        const getDefaultValue = () => (isClient() ? window.matchMedia(query).matches : false);
Если это не убрать, то получим hydration mismatch в SSR приложениях

Тест же нее просто так падает, если он упал надо разбираться почему это произошло

Вот что в демке на < 1024 разрешении ![Снимок экрана 2023-06-23 062203](https://github.com/core-ds/core-components/assets/40845033/09032ae1-c3c1-4251-8cd0-81d39eb9bb25)

2023-07-10 09:10 UTC, SiebenSieben commented
@reme3d2y падают тесты, нужна помощь

2023-07-17 06:47 UTC, reme3d2y commented
> @reme3d2y падают тесты, нужна помощь

Подключусь сегодня

2023-07-18 07:21 UTC, Lacronts approved these changes

2023-07-24 04:35 UTC, Oladii approved these changes

2023-07-26 04:03 UTC, Oladii approved these changes

2023-08-07 04:50 UTC, SiebenSieben approved these changes

2023-08-07 09:10 UTC, merged