feat(intl-phone-input): added mobile and responsive versions component
core-ds/core-components pull request #748
Opened 2023-07-19 08:40 UTC by Motahard

2023-07-19 08:59 UTC, Lacronts requested changes

2023-07-19 08:59 UTC, Lacronts commented on packages/intl-phone-input/src/Component.responsive.tsx
> +    const [view] = useMedia<InputAutocompleteMedia>(
В новом коде используем useMatchMedia

2023-07-19 08:59 UTC, Lacronts commented on packages/intl-phone-input/src/components/select-mobile/component.tsx
> +export const CountriesSelectMobile: FC<CountriesSelectProps> = forwardRef(
Тоже копипаста

2023-07-19 08:59 UTC, Lacronts commented on packages/intl-phone-input/src/responsive.ts
> +export * from './Component.responsive';
reposnsive точки быть не должно, responsive должен экспортироваться из индекса

2023-07-19 08:59 UTC, Lacronts commented on packages/intl-phone-input/src/index.ts
> +export { IntlPhoneInputDesktop as IntlPhoneInput } from './Component.desktop';
Десктопный компонент должен экспортироваться из desktop

2023-07-19 08:59 UTC, Lacronts commented on packages/intl-phone-input/src/Component.responsive.tsx
> +export const IntlPhoneInputResponsive = forwardRef<
Экспортируемый Responsive компонент не доложен содержать в имени responsive, просто IntlPhoneInput

2023-07-21 12:54 UTC, Motahard commented on packages/intl-phone-input/src/Component.responsive.tsx
> +export const IntlPhoneInputResponsive = forwardRef<
исправил

2023-07-21 12:54 UTC, Motahard commented on packages/intl-phone-input/src/index.ts
> +export { IntlPhoneInputDesktop as IntlPhoneInput } from './Component.desktop';
исправил

2023-07-21 12:54 UTC, Motahard commented on packages/intl-phone-input/src/responsive.ts
> +export * from './Component.responsive';
исправил

2023-07-21 12:54 UTC, Motahard commented on packages/intl-phone-input/src/Component.responsive.tsx
> +    const [view] = useMedia<InputAutocompleteMedia>(
исправил

2023-07-21 12:56 UTC, Motahard commented on packages/intl-phone-input/src/components/select-mobile/component.tsx
> +export const CountriesSelectMobile: FC<CountriesSelectProps> = forwardRef(
оставил 1 селект

2023-07-27 05:11 UTC, Lacronts commented on packages/intl-phone-input/src/components/base-intl-phone-input/Component.tsx
> +    InputAutocomplete as DefaultInputAutocomplete,
Этот импорт нужно вынести в Desktop версию компонента, по аналогии с мобильной, иначе при использовании мобильной версии компонента в бандл будет попадать десктопный автокомплит

2023-07-27 05:15 UTC, Lacronts commented on packages/intl-phone-input/src/docs/development.mdx
> +import { IntlPhoneInputResponsive } from '@alfalab/core-components/intl-phone-input/responsive';
Поправить, такой точки входа нет

2023-07-27 05:16 UTC, Lacronts commented on packages/intl-phone-input/src/docs/development.mdx
> +    IntlPhoneInput: IntlPhoneInputDesktopTS,
И тут поправить

2023-07-27 05:17 UTC, Lacronts commented on packages/intl-phone-input/src/__image_snapshots__/intl-phone-input-dark-preview-snap.png
Скрины должны быть в LFS

2023-07-27 05:18 UTC, Lacronts commented on .changeset/two-pumpkins-crash.md
> +Для компонента IntlPhoneInput добавлены мобильная и адаптивная версии компонента. Responsive, desktop компоненты экспортируются из индексного файла
Поправить, десктоп из индекса не тянется

2023-07-27 05:20 UTC, Lacronts commented
И демку бы поправить, потому что поиск в bottom-sheet не работает

2023-07-27 06:41 UTC, Valeri8888 commented on packages/intl-phone-input/src/Component.responsive.tsx
> +export type IntlPhoneInputResponsiveProps = IntlPhoneInputDesktopProps &
думаю будет лучше изменить IntlPhoneInputResponsiveProps на IntlPhoneInputProps, чтобы соотносилось с названием компонента

2023-07-27 06:48 UTC, Valeri8888 commented on packages/intl-phone-input/src/docs/Component.stories.mdx
> +<Story name='IntlPhoneInputMobile'>
Надо добавить и десктопную версию компонента

2023-07-27 06:49 UTC, Valeri8888 commented on packages/intl-phone-input/src/docs/Component.stories.mdx
> +import { IntlPhoneInputMobile as IntlPhoneInputMobileTS } from '../Component.mobile';
это удалить

2023-07-27 07:06 UTC, Valeri8888 commented
https://github.com/core-ds/core-components/assets/87258678/f11454c2-ea92-41c7-8e5b-0a6e9924764d

если посмотреть на задний план инпут прыгает

2023-07-27 07:08 UTC, Valeri8888 commented
https://github.com/core-ds/core-components/assets/87258678/06ea4008-c540-475b-a228-90091ab6f146

инпут фокусируется при disabled

2023-07-27 07:11 UTC, Valeri8888 commented
https://github.com/core-ds/core-components/assets/87258678/fc236eb7-fa2d-463c-9fe5-0abe73aa38ae

не работает пропс clear

2023-07-27 07:28 UTC, Lacronts commented on packages/intl-phone-input/src/Component.responsive.tsx
> +export type IntlPhoneInputResponsiveProps = IntlPhoneInputDesktopProps &
Нужно вообще уходить от экспорта всего и вся, ИМХО плохая практика
export * from ./component -> export {ComponentName} from './component'

2023-09-05 09:16 UTC, Valeri8888 commented
Закрываем пр так как будет новый компонент IntlPhoneInput с учетом всех запросов на рефакторинг

2023-09-05 09:16 UTC, closed without merging