feat(markdown): added component Markdown
core-ds/core-components pull request #767
Opened 2023-07-27 12:30 UTC by wibimipi

Добавлен компонент Markdown

2023-07-28 08:30 UTC, Valeri8888 commented on .changeset/cyan-paws-rhyme.md
> +Добавлен компонент Markdown
при добавление компонента надо писать "Добавлен новый компонент ..."

2023-07-28 08:35 UTC, Valeri8888 commented on packages/markdown/src/docs/Component.stories.mdx
> +<Tabs description={<Description />} props={<ArgsTable of={Markdown} />} />
надо добавить changelog и development , пример можно посмотреть в кнопке

2023-07-28 08:40 UTC, Valeri8888 commented on packages/markdown/src/index.module.css
> +.component > :first-child,
нужен импорт @import '../../themes/src/default.css';

2023-07-28 08:43 UTC, Valeri8888 commented on packages/markdown/src/utils.tsx
удалить

2023-07-28 08:46 UTC, Valeri8888 commented on packages/markdown/src/typings.ts
> +    /**
отделяем стройкой описание пропсов друг от друга

2023-07-28 08:48 UTC, Valeri8888 commented on packages/markdown/src/example.md
> +# Заголовок первого уровня
зачем нужен этот файл?

2023-07-31 12:03 UTC, wibimipi commented on packages/markdown/src/example.md
> +# Заголовок первого уровня
удалил

2023-07-31 12:03 UTC, wibimipi commented on packages/markdown/src/typings.ts
> +    /**
поправил

2023-07-31 12:03 UTC, wibimipi commented on packages/markdown/src/utils.tsx
+

2023-07-31 12:03 UTC, wibimipi commented on packages/markdown/src/index.module.css
> +.component > :first-child,
добавил

2023-07-31 12:03 UTC, wibimipi commented on .changeset/cyan-paws-rhyme.md
> +Добавлен компонент Markdown
поправил

2023-07-31 13:39 UTC, wibimipi commented on packages/markdown/src/docs/Component.stories.mdx
> +<Tabs description={<Description />} props={<ArgsTable of={Markdown} />} />
добавил

2023-08-01 07:15 UTC, Valeri8888 commented on packages/markdown/package.json
> +        "postinstall": "node -e \"if (require('fs').existsSync('./send-stats.js')){require('./send-stats.js')} \""
удали плиз postinstall мы выпиливаем его

2023-08-01 07:16 UTC, Valeri8888 approved these changes

2023-08-01 08:37 UTC, SiebenSieben commented on packages/markdown/package.json
> +    "version": "1.0.0",
Для новых компонентов ставим нулевую версию, в момент релиза поднимется до 1.0.0

2023-08-01 08:42 UTC, SiebenSieben commented on packages/markdown/src/docs/description.mdx
> +Так как в тексте может попадаться маскированный номер карты со 6 звездочками, добавил пример 1212212**\*\***212121
```suggestion
Так как в тексте может попадаться маскированный номер карты с 6 звездочками, добавил пример 1212212**\*\***212121
```

2023-08-01 08:45 UTC, SiebenSieben commented on packages/markdown/src/index.module.css
> +    margin-bottom: var(--gap-s);
Почему где-то паддинги где-то марджины?

2023-08-01 08:49 UTC, Lacronts commented on packages/markdown/src/docs/Component.stories.mdx
> +import { Markdown, Meta, Story } from '@storybook/addon-docs';
В новых компонентах пишем стори в tsx формате. Пример в custom-button

2023-08-01 08:49 UTC, SiebenSieben commented
Это выглядит странно:
<img width="324" alt="image" src="https://github.com/core-ds/core-components/assets/109410/507ab0c1-1534-48b2-92ec-008de15465a5">

2023-08-01 08:50 UTC, SiebenSieben commented
Не будет возможности управлять отступами каждого элемента? Сейчас паддинг влияет на паддинги всех элементов и непонятно в каком случае можно будет этим воспользоваться кроме обнуления

2023-08-01 09:02 UTC, wibimipi commented
> Не будет возможности управлять отступами каждого элемента? Сейчас паддинг влияет на паддинги всех элементов и непонятно в каком случае можно будет этим воспользоваться кроме обнуления

Для этого есть класс у обертки. Там мы пишем & > h1 { padding:  } и так для любого элемента. Есть 2 способ в overrides указать для любого элемента какой тег ты хочешь применить и гибко его настроить

2023-08-01 09:07 UTC, Lacronts commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
Тут вместо паддингов может добавить класс каждому элементу?
           h1: (props) => (
                <Title
                    style={paddingStyles}
                    font={font}
                    className={cn(**'h1'**, styles.h1)}
                    tag='h1'
                    view='medium'
                    color='primary'
                >
                    {props.children}
                </Title>
            ),

2023-08-01 09:16 UTC, Lacronts commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
Тогда у разраба будет возможность для каждого элемента настроить все что он хочет

2023-08-01 13:17 UTC, wibimipi commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
добавил

2023-08-01 13:17 UTC, wibimipi commented on packages/markdown/src/Component.tsx
> +    platform,
добавил версии

2023-08-01 13:17 UTC, wibimipi commented on packages/markdown/src/docs/Component.stories.mdx
> +import { Markdown, Meta, Story } from '@storybook/addon-docs';
поменял

2023-08-01 13:17 UTC, wibimipi commented on packages/markdown/src/index.module.css
> +    margin-bottom: var(--gap-s);
поменял на марджины

2023-08-03 06:28 UTC, SiebenSieben commented on packages/markdown/src/docs/development.mdx
> +import { Markdown } from '@alfalab/core-components/markdown';
Тут надо разные версии добавить, см. как у других компонентов

2023-08-03 06:35 UTC, SiebenSieben approved these changes

2023-08-03 06:42 UTC, Lacronts commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
Проп paddings оставляем? Непонятно как и зачем его использовать, если он меняет отступы у всех элементов сразу

2023-08-03 06:44 UTC, Lacronts commented on packages/markdown/src/Component.mobile.tsx
> +    <Markdown {...restProps} platform='mobile'>
Компонент desktop, а platform mobile

И нет экспорта этого компонента, как и мобильного

2023-08-03 06:44 UTC, Lacronts commented on packages/markdown/src/Component.desktop.tsx
> +    <Markdown {...restProps} platform='desktop'>
тут тоже перепутано

2023-08-03 06:45 UTC, Lacronts commented on packages/markdown/package.json
> +    "dependencies": {
exports добавить нужно, примеры в открытых ПРах

2023-08-03 09:51 UTC, wibimipi commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
ну в дизайне он есть, тогда надо выкинуть оттуда сначала

2023-08-03 09:53 UTC, Lacronts commented on packages/markdown/src/hooks/use-overrides.tsx
> +        const paddingStyles =
Где посмотреть?

2023-08-03 10:00 UTC, Lacronts commented on packages/markdown/src/docs/development.mdx
> +import { MarkdownDesktop } from '@alfalab/core-components/markdown';
/desktop на конце должно быть и /mobile соответственно

2023-08-03 10:01 UTC, Lacronts commented on packages/markdown/src/index.ts
> +export { MarkdownMobileComponent as MarkdownMobile } from './Component.mobile';
Экспорт из mobile.ts

2023-08-07 09:37 UTC, Lacronts requested changes

2023-08-07 09:37 UTC, Lacronts commented on packages/markdown/src/Component.mobile.tsx
> +export const MarkdownMobileComponent: React.FC<MarkdownDesktopProps> = ({
Пропы неверный указаны MarkdownDesktopProps в мобильном компоненте

2023-08-08 08:53 UTC, wibimipi commented on packages/markdown/src/Component.mobile.tsx
> +export const MarkdownMobileComponent: React.FC<MarkdownDesktopProps> = ({
поправил

2023-08-08 10:24 UTC, Lacronts requested changes

2023-08-08 10:24 UTC, Lacronts commented on packages/bank-card/src/Component.test.tsx
> +
Лишник изменения, надо бы от них избавиться

2023-08-09 12:32 UTC, Lacronts approved these changes

2023-08-09 12:32 UTC, merged