fix(pure-cell): added tag ability select
core-ds/core-components pull request #939
Opened 2023-10-24 06:43 UTC by Valeri8888

2023-10-24 08:52 UTC, SiebenSieben approved these changes

2023-10-24 10:00 UTC, Lacronts requested changes

2023-10-24 11:50 UTC, Valeri8888 commented on packages/pure-cell/src/components/amount-title/component.tsx
> +    titleStyle?: TitleProps['view'];
фикс

2023-10-27 07:11 UTC, Lacronts commented on packages/pure-cell/src/components/amount-title/component.tsx
> +    titleProps = {},
Создавать пустой объект тут не нужно

2023-10-27 07:12 UTC, Lacronts approved these changes

2023-10-27 07:14 UTC, merged