fix(plate): button order changed
core-ds/core-components pull request #953
Opened 2023-10-30 12:26 UTC by Valeri8888

2023-10-30 14:47 UTC, Lacronts commented on packages/plate/src/components/base-plate/index.module.css
> +        order: -1;
Почему последнюю кнопку перетаскиваешь? ИМХО первую в конец надо. Только для первой же задан view='secondary'. Если будет три кнопки это не сработает.

Может вообще flex-direction: row-reverse сделать?

2023-10-30 14:47 UTC, Lacronts commented on packages/plate/src/components/base-plate/index.module.css
> +.order {
row-reverse?

2023-10-30 16:05 UTC, Valeri8888 commented on packages/plate/src/components/base-plate/index.module.css
> +        order: -1;
согласно дизайну там может быть только две кнопки 
но для перестраховки можно через flex-direction: row-reverse сделать

2023-10-30 16:55 UTC, SiebenSieben approved these changes

2023-10-30 18:09 UTC, Lacronts approved these changes

2023-10-31 03:34 UTC, Oladii approved these changes

2023-10-31 08:13 UTC, Lacronts requested changes
Сейчас проблема с отступами появилась

![Screenshot from 2023-10-31 15-13-23](https://github.com/core-ds/core-components/assets/40845033/aae24382-5570-49ce-b166-f092466aa06b)

2023-10-31 13:09 UTC, Valeri8888 commented
> Сейчас проблема с отступами появилась
> 
> ![Screenshot from 2023-10-31 15-13-23](https://user-images.githubusercontent.com/40845033/279302981-aae24382-5570-49ce-b166-f092466aa06b.png)

фикс

2023-11-01 05:06 UTC, Lacronts approved these changes

2023-11-03 04:03 UTC, merged